### ISSUE TITLE
connetion timed out

### ISSUE THREAD

**Issue by midnightstorm1000** [voidpet/bugs#10]
![image](https://user-images.githubusercontent.com/96018291/145722477-49732202-5252-4071-b79d-56460dd1d5b5.png)
says error 522 and says to try again in a few minutes, i have tried refreshing 6 times and its been a half hour

**Comment by maverick-dev-55** [comment]
https://discord.com/channels/815430930885115918/816110478429257768/919637167762968607 we all know ben sent a message in discord

**Comment by benawad** [comment]
fixed
