### ISSUE TITLE
Lost Supporter Badge with Secret

### ISSUE THREAD

**Issue by Skitcy** [voidpet/bugs#100]
I noticed that once I found the secret (I know that's vague I hope you understand the secret) it had removed my supporter badge.

**Steps to reproduce the behavior:**
1. Become a supporter by purchasing from the store
2. find the secret
3. cry internally as you misplaced the supporter badge

**Expected behavior**
Loosing a fun badge because your curiosity got the best of you.

**Video or Screenshots**
Before:
![Screenshot_20220205-154746_Chrome](https://user-images.githubusercontent.com/48242171/153702626-59f20de9-e61b-485d-850f-e49bbcae330e.jpg)
After:
![Screenshot_20220212-171708_Chrome](https://user-images.githubusercontent.com/48242171/153702651-2ea71c25-9d60-4162-a814-f9074a4abc51.jpg)

**Additional context**
I couldn't find this issue anywhere, so thought I'd report it in case it isn't known.

**Comment by benawad** [comment]
fixed
