### ISSUE TITLE
Am I IP-banned?

### ISSUE THREAD

**Issue by Kroppeb** [voidpet/bugs#101]
Just checking in, cause the error I get when visiting [api.voidpet.com](https://api.voidpet.com/) seems to be quite generic. 

> ## The page you were looking for cannot be served.
> If you are the application owner check the logs for more information.

I did hear some people were getting this error a few hours ago, but I only seem to be getting this error on my home wifi.

**Comment by benawad** [comment]
There was a few people banned today for sending too many requests, did you happen to have a bot pinging the api lol?
