### ISSUE TITLE
Icons overflow without scroll in link icon menu

### ISSUE THREAD

**Issue by myleskeeffe** [voidpet/bugs#105]
**Describe the bug**
In the links section when editing a profile, when you try to choose a different icon, all the icons overflow the screen and (on desktop at least) you can't scroll this menu, leading to some icons being unselectable.

**To Reproduce**
1. Have access to the profile links feature
2. Click edit profile
3. Click add link
4. Click the icon to the left of the 'subtitle' box

**Expected behaviour**
The box popup should be scrollable, with a UI/UX that also hints that it is scrollable.

**Video or Screenshots**
![image](https://user-images.githubusercontent.com/11828103/153808588-d5b9df0e-c776-432b-a7ed-407cb79ab89c.png)

If I manually zoom all the way out I can see the rest:
![image](https://user-images.githubusercontent.com/11828103/153808634-c7e71aaf-e5bc-43be-8db8-dfaf18fe42c9.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Browser: Firefox
 - Version: 96.0

P.S. Since this relates to a feature not publicly available - please remove (or dm me) if this should be here :). 
Pik#9102 on discord

**Comment by benawad** [comment]
fixed in next release
