### ISSUE TITLE
vivid Anger disappears during Explore

### ISSUE THREAD

**Issue by Vyrasla** [voidpet/bugs#108]
**Describe the bug**
My Anger  is a white vivid so  when  i talk o itt during exploring i see only  the eye

**To Reproduce**
1. Go to 'explore'
2. klick till you talk to your  pet

**Expected behavior**
well don't know a black outline?

**Video or Screenshots**
https://ibb.co/ZYYFwVX

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Opera GX
 - Up to date

**Comment by benawad** [comment]
fixed in next release
