### ISSUE TITLE
not a bug - food

### ISSUE THREAD

**Issue by atypica** [voidpet/bugs#110]
this isn’t a bug but idk the discord

i think it would be helpful to introduce a “food” activity with your voidpet as the game (?) leans towards emotions and mental health. 

i think “eating” with your voidpet and having them display happiness doing so would be beneficial for individuals who struggle with eating. 

even if your voidpet doesn’t necessarily need food i would love to see a feature like this or similar to encourage users to eat and develop a better relationship with food. 

it sounds cheesy but i do think it could help :)

**Comment by benawad** [comment]
noted
