### ISSUE TITLE
Grammar error while pressing "explore"

### ISSUE THREAD

**Issue by kwinyl** [voidpet/bugs#112]
Not exactly a large bug but it could be worth noting. When pressing "explore" in the menu, the image below shows up as usual for me. 

![Screenshot_20220218-072301](https://user-images.githubusercontent.com/99968620/154683104-05c698f6-b41b-442d-94cd-b01b8ef6ffa2.jpg)

However, there is an additional "at" underlined in this image. Thanks!

**Comment by benawad** [comment]
fixed
