### ISSUE TITLE
Bio and Bond Level Reset

### ISSUE THREAD

**Issue by FictionalFeline** [voidpet/bugs#115]
**Describe the bug**
When opening up the game I noticed that my void pet's bio and my bond level is different.
My Void Pet used to like to scream and now it says it like to drool. The number -1 has changed to 1. The emoji changed from a snake to a crown. The shield looking icon has changed. The element has stayed the same. I believe the height has changed from a 1.1ft to 1ft but do not remember the exact number. I am insure if the weight has changed. I am also unsure of the zodiac.
My bond level has also been reset back to zero. It was at 4 yesterday.
I do not know what has caused this.

**To Reproduce**
1. Open up the website
2. Click on Bio
3. See error

**Expected behavior**
For my Void Pet's bio to be the same as it has been since launching my account. My bond level at 4, height 1.1ft, snake emjoi, -1 number, shield symbol correct.

**Video or Screenshots**
I do not have a picture of my original stats but have provided a picture of the new ones.
![Screenshot_20220221-164814_Chrome](https://user-images.githubusercontent.com/100166677/155030048-5a169d6b-e665-4c10-9fa1-78d65a002c79.jpg)

**Additional context**
The name of my Void Pet and my days met are still the same.
Link to account voidpet.com/FictionalFeline

**Comment by Kroppeb** [comment]
According to my tool, both pets exists on your account, with the same name.
![image](https://user-images.githubusercontent.com/7889478/155030660-037f2f81-db7e-413f-89a8-e93bb41e98d4.png)
You might still be able to play with it using the following links
* [new](https://voidpet.com/o/pet/9a52dcca-5321-4e4f-8e91-2fd1f8171022/play)
* [old](https://voidpet.com/o/pet/f73a75b0-4780-4ce3-9fb2-03ac8b8b60d6/play)
In the mean time, I guess congrats on being the first to have 2 pets?

**Comment by Kroppeb** [comment]
It seems that only the old deprecated api (which this quick script uses) returns both pets, but the new api, only returns the first pet.

**Comment by benawad** [comment]
fixed
