### ISSUE TITLE
Logging into anothers account

### ISSUE THREAD

**Issue by ann1Anni** [voidpet/bugs#117]
So I went to make a second account for fun (since i like all the voidpets) and went to get started. I couldnt make a username since it said "Username cant be changed now". So I went back a page and it suddenly showed me a voidpet that I never had seen before. It was a sad voidpet even though my only ones were anxious and envy. I logged out of it since I wouldnt be able to do anything with it anyway and its not mine.

**Comment by benawad** [comment]
fixed
