### ISSUE TITLE
Avatar Back Customization button disappearing after paying for Giga

### ISSUE THREAD

**Issue by igd6695** [voidpet/bugs#118]
**Describe the bug**
After paying for Giga, I returned to the avatar customization page to add the wings to my character but found that the back customization button had disappeared. All other buttons are visible.

**To Reproduce**
1. Customize Avatar
2. Purchase Giga
3. Change avatar after purchase completes

**Expected behavior**
I expected the button to still be visible and for the Giga-only item to now be available to me.

**Video or Screenshots**
[https://cdn.discordapp.com/attachments/458329122389884929/947942275688849439/unknown.png](url)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 98 ?

**Additional context**
My site username is digitalbelle, if thats required for anything.

**Comment by benawad** [comment]
Sorry about that, you should have your wings now!
