### ISSUE TITLE
The Discord field in profile settings doesn't support Discord user tags

### ISSUE THREAD

**Issue by overlisted** [voidpet/bugs#12]
![image](https://user-images.githubusercontent.com/66535446/145722961-57184fcf-b124-4910-b8d4-1d057a200170.png)

Is this intentional? Wouldn't it be better if people who don't have their own Discord server could just use their handle?

**Comment by belovedhiraeth** [comment]
It's also happening to me at the moment.

**Comment by maverick-dev-55** [comment]
also can dsc.gg links be supported as well?

**Comment by Sadisticsins** [comment]
Also happening to me

**Comment by james-work-account** [comment]
Looking through the page source, the current regex for validating usernames seems to be `^(https?:\/\/)?(www.)?(discord.(gg|io|me|li)|discordapp.com\/invite)\/[^\s/]+?(?=\b)$` - this requires a URL (the `.../invite` stuff isn't optional). Changing the regex to include Discord usernames, such as including `^.{3,32}#[0-9]{4}$` (from https://ihateregex.io/expr/discord-username/) should remove the "invalid handle" error, as it would account for people only putting in Discord handles (not just full URLs).

So the full regex would be something like:

```
^(https?:\/\/)?(www.)?(discord.(gg|io|me|li)|discordapp.com\/invite)\/[^\s/]+?(?=\b)$|^.{3,32}#[0-9]{4}$
```

(very shoddily tested at https://regex101.com/r/6GxgYk/1 - obviously not very exhaustive tests)

**Comment by GabsMcStabs** [comment]
Having this issue as well

**Comment by benawad** [comment]
only want this for server invites at the moment, will add a better error msg

**Comment by DumbGameMaker** [comment]
> Looking through the page source, the current regex for validating usernames seems to be `^(https?:\/\/)?(www.)?(discord.(gg|io|me|li)|discordapp.com\/invite)\/[^\s/]+?(?=\b)$` - this requires a URL (the `.../invite` stuff isn't optional). Changing the regex to include Discord usernames, such as including `^.{3,32}#[0-9]{4}$` (from https://ihateregex.io/expr/discord-username/) should remove the "invalid handle" error, as it would account for people only putting in Discord handles (not just full URLs).
> 
> So the full regex would be something like:
> 
> ```
> ^(https?:\/\/)?(www.)?(discord.(gg|io|me|li)|discordapp.com\/invite)\/[^\s/]+?(?=\b)$|^.{3,32}#[0-9]{4}$
> ```
> 
> (very shoddily tested at https://regex101.com/r/6GxgYk/1 - obviously not very exhaustive tests)

regexes eee
