### ISSUE TITLE
Giga bug

### ISSUE THREAD

**Issue by nikbounty** [voidpet/bugs#120]
When I purchased the yearly subscription for Voidpet Giga, all buttons stopped working on my phone and in the browser. I would hit them to no response, and when they would respond I would get an infinite loading screen. 
![8BAAA229-EE7D-4C1B-AFD8-CF9C0A9F0DE7](https://user-images.githubusercontent.com/100625007/156050279-cabce15d-8784-43a1-92c0-21e26c1340ab.png)

**Comment by benawad** [comment]
I just reset a cache, does this happen in another browser for you as well?

**Comment by nikbounty** [comment]
Yes, I opened it on the browser as well and it does the same thing
![6C8DCF7D-607A-442E-A7AB-C4D5A7AFA603](https://user-images.githubusercontent.com/100625007/156054126-20806d33-c9ec-4c77-8b9e-3301e3f1d035.png)

**Comment by benawad** [comment]
What's your voidpet username? Could you try it on a computer as well? I want to try isolating whether its something with your specific account or device specific.

**Comment by myleskeeffe** [comment]
I haven’t been able to replicate this on my account (MylesK) - so likely something to do with account or device? I’ve got an iPhone XS on Safari - and checkout process & redirection back to app all appears to have worked with no issues :). Judging on the screenshot size - @nikbounty I’d hazard a guess that you’re using an iPhone 12 through to iPhone 13 Pro?

**Comment by benawad** [comment]
Should be fixed now
