### ISSUE TITLE
giga bug on browser.

### ISSUE THREAD

**Issue by Nuclearsmilz** [voidpet/bugs#121]
i went to voidpet.com/o/giga, and i bought the yearly subscription. then it redirected me to my profile, but without giga. i went to my profile and it asked me to pay for giga again

**Comment by benawad** [comment]
What?

**Comment by Nuclearsmilz** [comment]
sorry ben, it posted it right away with just the title

**Comment by Nuclearsmilz** [comment]
my voidpet name is the same as my github

**Comment by Nuclearsmilz** [comment]
my voidpet username is chronoblaze if you need it

**Comment by Nuclearsmilz** [comment]
@benawad should i buy the subscription again this time through my profile? or will you be able to tie the purchase to my account?

**Comment by benawad** [comment]
It's tied to your account, let me double check

**Comment by Nuclearsmilz** [comment]
thanks ben

**Comment by benawad** [comment]
Should be fixed now, thanks for being patient!
