### ISSUE TITLE
once character is created with the new update (? possibly before i can't confirm) scrolling using the scroll wheel does not work

### ISSUE THREAD

**Issue by Nuclearsmilz** [voidpet/bugs#123]
i have to use the scroll bar off to the right to see farther down than for example your social links for or another example i can't see the play with my voidpet option or more info.

**Comment by benawad** [comment]
Can you show me a screenshot/video

**Comment by Nuclearsmilz** [comment]
sure. its recorded from my phone.
https://drive.google.com/file/d/1gB4d1ba_9ikisZwXLQ7qmwXjDBYLbQ2I/view?usp=sharing

**Comment by Nuclearsmilz** [comment]
hey ben im stupid i realized what the issue was while scrolling through my extensions. i had smoothscroll installed on my browser. removed/disabled the extension for the site and scrolling works like normal again.
