### ISSUE TITLE
(Minor) Login or join button incorrect layer positions

### ISSUE THREAD

**Issue by myleskeeffe** [voidpet/bugs#124]
**Describe the bug**
When viewing a void pet players profile whilst not logged in, the “login or join” button seemingly floats and hides behind layers seemingly at random.

**To Reproduce**
1. In a private or not logged in browser, visit a void per players profile. [Example](https://voidpet.com/MylesK)
2. Scroll down the page, and take note on the layer heights/positions of the join button relative to the rest of the UI.

**Expected behavior**
I’m on mobile right now - so can’t verify for sure - but I’m taking a guess that the z index for a lot of these elements are quite different and messing with eachother. Ideally the button should render at a consistent layer compared to all the other elements, and likely be the very top layer.

**Video or Screenshots**
![2D5B3336-6A78-4E28-8B7A-7D33C724146D](https://user-images.githubusercontent.com/11828103/156070823-1afb9265-1730-490a-a1c4-39df511e5bb5.png)
![460E8196-5386-471E-B80E-9648ADF60065](https://user-images.githubusercontent.com/11828103/156070843-5312a7e1-ffd5-46a1-874f-b88c5da7dcec.png)
![9251F564-C9BA-4804-976D-48F0E0E6C841](https://user-images.githubusercontent.com/11828103/156070847-2f604fa2-42fd-427a-bc92-821bd3622342.png)
![6AAF62C1-185E-4E4E-9162-104FABE2B49A](https://user-images.githubusercontent.com/11828103/156070850-fadbf3ee-07ec-4dfa-b5fb-b086fab80294.png)
![17E598F1-EBC6-4C65-9BAD-90E7D2122D05](https://user-images.githubusercontent.com/11828103/156070853-9361f3d2-a06d-4194-989a-d4b9d9c79ed8.png)
![B277F9C7-6E3D-4150-B85E-9B4BF6425BC4](https://user-images.githubusercontent.com/11828103/156070857-2a5f52f3-8348-4e48-9ae4-06a841498561.png)

**Smartphone:**
- Device: iPhone XS A2097
 - OS: iOS 15.3.1 (19D52)
 - Browser: Safari
 - Version: Latest version for OS/phone
 - 
 

**Additional:**
May want to tag this low priority - it’s a completely cosmetic glitch which you can scroll into a good area to click on it again (i.e. doesn’t really effect gameplay in anyway)

**Comment by benawad** [comment]
fixed
