### ISSUE TITLE
(Minor) (Cosmetic) - Contrast between background & profile UI elements

### ISSUE THREAD

**Issue by myleskeeffe** [voidpet/bugs#125]
**Describe the bug**
Profiles which have light coloured background elements conflict with the UI elements of the same colour - making for a really low contrast (wcag) - but also just hard to read.

**To Reproduce**
1. Visit a profile with a background set: [Mine as an example](https://voidpet.com/MylesK)

**Smartphone:**
- Device: iPhone XS A2097
 - OS: iOS 15.3.1 (19D52)
 - Browser: Safari
 - Version: Stock/Latest for OS

**Expected behavior**
Not sure how the best way to get around this is - could potentially make the background slightly darker, or create a layer blur underneath the floating text/icons/profile picture. Another way could be to encase those in a card - but it would kind of detract from the look your were going for on the profile.

**Video or Screenshots**
![99A14A36-0A99-4E2B-AE44-0A6394EB605E](https://user-images.githubusercontent.com/11828103/156072970-bdb4f640-43b6-4b01-823d-41c04f1dcce1.png)

**Comment by benawad** [comment]
fixed
