### ISSUE TITLE
New users cannot sign up

### ISSUE THREAD

**Issue by axolotls99** [voidpet/bugs#126]
**Describe the bug**
*I personally do not have this problem. I am submitting this report on behalf of the 10+ users who have raised the issue in discord. The issue is that when attempting to sign up, users get the message "[sad face emoji] you can't change your username anymore]

**To Reproduce**
1. attempt to sign up
2. reach the choose or claim username screen
3. enter a username
4. see above error message

**Expected behavior**
be allowed to sign up

**Video or Screenshots**
![image](https://user-images.githubusercontent.com/98911210/156089596-889800ab-b66f-4a21-b01a-86c3c5b4c0c5.png)
(this is not my image it was submitted by ganyuubest on discord)

**Desktop (please complete the following information):**
so far as I know this is happening across all devices

**Additional context**
You probably already know about this but just in case

**Comment by benawad** [comment]
should be fixed now

**Comment by axolotls99** [comment]
works now thanks so much!
