### ISSUE TITLE
Bug/issue with purchasing membership

### ISSUE THREAD

**Issue by Dragonbane07** [voidpet/bugs#127]
**Describe the bug**
When purchasing the Void Giga (I chose the 39.99 version) there is no page confirming your purchase (other than an email but again, no pop-up saying that you made a successful purchase and youd get an email or that you made a purchase at all it just refreshes), nothing on the website other than the gifts you recieve (which I personally had to dig for) that tells you that you have the membership, you can purchase the membership multiple times.
**To Reproduce**
1. Go to the store page where you get the monthly $3.99 option or the $39.99 yearly option.
2. Click on either option, and go through as if youre purchasing it.
3. The page should refresh back to the page or to your void pet, but either way, the store page is the same as if you didnt get the membership or the purchase didnt go through.
4. You can also click the pretty swirly on top of your pet and the same thing happens.

**Expected behavior**
I expected a website to confirm my order, then another screen/pop-up stating my purchase was complete, and that Id get my invoice/receipt/something in my email saying my purchase was finished. I also expect maybe a badge or a pin on the website home page saying Im a member, and if I go to the store it says Im already a member (whether its Monthly or Yearly member) and that the option I chose is no longer able to be clicked, but if I wanted to upgrade/downgrade Id be able too.

**Video or Screenshots**
![Invoice 1](https://user-images.githubusercontent.com/100657979/156098471-9aab2f98-e627-4507-9331-f363a28c0fbc.jpg)
![Reciept 1](https://user-images.githubusercontent.com/100657979/156098478-6b3f5656-3ea2-4f86-8e04-ef7cbf8f60fd.jpg)
![Invoice 2](https://user-images.githubusercontent.com/100657979/156098485-ed3f9eac-2d7f-43a3-80c2-c722c4998fa9.jpg)
![Receipt 2](https://user-images.githubusercontent.com/100657979/156098494-6752b56e-ea2d-4faa-b595-46b22a9c00f0.jpg)
![Invoice 3](https://user-images.githubusercontent.com/100657979/156098534-b5235d5c-cfc8-49f0-a9bd-f2b5a094bb3e.jpg)
![Receipt 3](https://user-images.githubusercontent.com/100657979/156098542-43ced5f3-645d-484b-8afc-df9f5f047d0b.jpg)
![Discord message 1](https://user-images.githubusercontent.com/100657979/156099675-3910b080-a1e3-44fc-9e0d-147f417a74d3.jpg)
![Discord Message 2](https://user-images.githubusercontent.com/100657979/156099682-3ef878a7-a703-4816-a1cc-e67c778c78f0.jpg)

Its the current edition of the website, but regardless of device it probably would happen.

**Additional context**
I was actually sent here from creating a ticket in the discord server, and I had request/asked for a refund on 2 of the 3 options, but I didnt get a clear response. 

I was also instructed to provide my Voidpet name, which is Dragonbane07.

**Comment by benawad** [comment]
Sorry about that, just refunded 2 of the 3. Might take up to 5-10 days to reflect on your cc statement.

Feel free to reopen this issue if anything else comes up.
