### ISSUE TITLE
I joined before the update and my voidpet is bouncy for others but not me 

### ISSUE THREAD

**Issue by NexusRX** [voidpet/bugs#129]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by benawad** [comment]
What's your voidpet username? Did you create a starter before the update?

**Comment by NexusRX** [comment]
> What's your voidpet username? Did you create a starter before the update?

My username is "NexusRX" ive had an account since linda did verification through phone number, and i did create a starter day it updated for that.

**Comment by benawad** [comment]
If you change browsers does it bounce for you?

**Comment by NexusRX** [comment]
> 

what do you mean

**Comment by benawad** [comment]
Can you try downloading Chrome and seeing if your pet bounces there

**Comment by NexusRX** [comment]
> Can you try downloading Chrome and seeing if your pet bounces there

im on crome

**Comment by benawad** [comment]
Can you try firefox or safari and see if the pet bounces there

**Comment by NexusRX** [comment]
> Can you try firefox or safari and see if the pet bounces there

i think its working now, sorry if this was a bother idk what was wrong

**Comment by benawad** [comment]
No worries!
