### ISSUE TITLE
PLEASE READ BEFORE YOU MAKE AN ISSUE

### ISSUE THREAD

**Issue by DumbGameMaker** [voidpet/bugs#13]
### Some things to note before making issues:

1. If you get a 5xx error (i. e. 522), this is likely because there are too many people connecting. Be patient, it isn't a bug
2. Make sure bugs are relevant and descriptive, and put as much detail as possible in them. In addition, don't make issues that could come across as rude.
3. Please don't just make spam issues, such as issue #4
4. Passphrase is in the FAQ on discord
5. The game is in BETA - Bugs and incomplete features are to be expected. 
6. With this in mind, don't make issues just to be rude towards anyone (especially the devs or the game itself).
7. if your post is a *FEATURE REQUEST* please add [Feature Request] to the beginning of the issue
8. Make sure to check that  your bug hasn't been reported yet. I will try to keep an updated list of open bugs below, but also check the issues tab because this isn't updated that frequently.

#### Bugs that will NOT be fixed (intended/not a bug, or just not worth fixing):
- Discord field doesn't accept discord tags (#12)
- Usernames aren't verified on the store (#22)
- Weird behavior with multiple items on the store cart (#43, #42, #40)

This post will be updated as more bugs are created.

**Comment by overlisted** [comment]
"3. other stuff"

**Comment by DumbGameMaker** [comment]
> "3. other stuff"

yeah, i kinda was out of ideas for what to put, i replaced it with spam issues

**Comment by DumbGameMaker** [comment]
@benawad pin this?

**Comment by DumbGameMaker** [comment]
?
