### ISSUE TITLE
"Bought Merch" badge does not display on mobile

### ISSUE THREAD

**Issue by LunarMooon** [voidpet/bugs#131]
**Describe the bug**
I purchased merch many months ago, but the icon to show that I have only shows up on PC and not on mobile through Safari.

**To Reproduce**
1. Go to https://voidpet.com on Safari on mobile
2. Log in/click play
3. View profile

**Expected behavior**
I'm not sure if it was always like this and I only just noticed, but I expected the 'bought merch' badge to appear on my profile below my socials.

**Video or Screenshots**
![image](https://user-images.githubusercontent.com/101020534/156898902-712ab471-450b-4d01-9473-5a28151c5038.png)
![image](https://cdn.discordapp.com/attachments/828366310957908038/949764519943606332/IMG_7631.png)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser Chrome
 - Version 10

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS
 - Browser Safari
 - Version 14.8

**Comment by benawad** [comment]
fixed
