### ISSUE TITLE
Bugging out

### ISSUE THREAD

**Issue by Mikey0666** [voidpet/bugs#132]
It wont let me click on anything unless it's the play with your void pet or more about your void pet. Then it loads for awhile, not going anywhere. And theres a smaller picture of the void pet outside of the box and on my user name. The scribble is mine to cover the rest of my user name.

![20220305_225708](https://user-images.githubusercontent.com/101032514/156909856-bb76792b-d4a4-492a-bf6c-8114ccece5ea.jpg)

**Comment by Number-Serenia** [comment]
Mine is doing this too and my entire voidpet thing is un-accesible

**Comment by benawad** [comment]
Could you take a video of what happens when you try doing things

**Comment by Mikey0666** [comment]
I wish I can but I cant record it as it's on my phone and I dont know how to screen record. It looks like it clicks but it doesnt take you anywhere. And if it does it's the void pet loading screen forever.

**Comment by benawad** [comment]
Does it do that for you in a different browser?

**Comment by Mikey0666** [comment]
Yes, it does it to me on other browsers

**Comment by benawad** [comment]
Is only your avatar missing or if you go to https://voidpet.com/benawad or another persons page does their avatar show up?

**Comment by Mikey0666** [comment]
Yes, it also does it when I look at yours
![Screenshot_20220306-183343_Samsung Internet](https://user-images.githubusercontent.com/101032514/156949578-9e4ddbb5-39cf-4353-9873-1e9313b1155a.jpg)

**Comment by benawad** [comment]
Could you leave your profile sitting open on your phone for like 2-5 minutes and see if its a matter of time for the avatar to show up. I have a theory I'm testing.

**Comment by Mikey0666** [comment]
It didnt fix it, stayed the same

**Comment by benawad** [comment]
If you go to https://voidpet.com then hit play what happens?

**Comment by Number-Serenia** [comment]
Idk how mine fixed but its working now, but I did leave mine open for a few hours today! I also managed to get into the play with sector and earn points and it works now!

**Comment by Mikey0666** [comment]
I cant hit play, its stuck at this loading screen

![Screenshot_20220306-201717_Samsung Internet](https://user-images.githubusercontent.com/101032514/156956587-247e7026-a34c-4d56-bf41-bd531cf359cb.jpg)

**Comment by Mikey0666** [comment]
Maybe I can leave it on over night for it to fix

**Comment by Number-Serenia** [comment]
It seems to be a reoccurring issue among Android issues mainly from what I've seen!

**Comment by benawad** [comment]
I think it might have been caused be a funky caching issue. Can you try refreshing and see if it now works for you (also try incognito browser)

**Comment by benawad** [comment]
I cleared a cache thing on my side which I'm hoping gives you a different result when you refresh now

**Comment by Mikey0666** [comment]
It worked, thanks so much!
