### ISSUE TITLE
when you click ''explore'' it shows this {   "id": 0,   "layer": 1,   "zone": 2 }

### ISSUE THREAD

**Issue by beaniemeanie** [voidpet/bugs#134]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by benawad** [comment]
if you refresh does it still show this?
