### ISSUE TITLE
stuck in a battle.

### ISSUE THREAD

**Issue by Yomawmcentral** [voidpet/bugs#136]
I am stuck in a battle. The only moves i keep getting are gatekeep and my enemy only gets fume. There is also no way to _leave_ the battle which should 100% be added. Because of this I cannot go anything but gatekeep

**Comment by Yomawmcentral** [comment]
or atleast make it so that you can't get 4 of the same move

**Comment by Lazy-Neko** [comment]
I have the same issue but the enemy is stuck using 'Girlboss'
![Screenshot_20220320-175222_Chrome](https://user-images.githubusercontent.com/101967422/159153599-1069753b-da63-4493-9d0e-499781dab098.jpg)
![Screenshot_20220320-175339_Chrome](https://user-images.githubusercontent.com/101967422/159153601-abe241c0-150c-4f4f-ab11-7ba5561c282a.jpg)
![Screenshot_20220320-175347_Chrome](https://user-images.githubusercontent.com/101967422/159153603-72e4e9bf-a003-40a7-b89a-d923c5fd1ebc.jpg)
![Screenshot_20220320-175407_Chrome](https://user-images.githubusercontent.com/101967422/159153604-51f69900-e83e-4460-8134-6d22d4ff9317.jpg)
![Screenshot_20220320-180046_Chrome](https://user-images.githubusercontent.com/101967422/159153651-325e110c-e219-43c8-ad7f-b7e34d0ada20.jpg)

**Comment by LunaGx** [comment]
I have the same issue with the Gatekeep-Fume loop.  I would prefer an 'escape button' to at least be able to escape such situations.
![1,1](https://user-images.githubusercontent.com/101973525/159159148-f843ac0b-757c-496d-880e-fbba4e2ef0cf.png)
![1,2](https://user-images.githubusercontent.com/101973525/159159153-cd5472ca-0d8b-4f17-9014-df81fed417e3.png)

**Comment by Lazy-Neko** [comment]
An escape option would be great.
It seems like Gatekeep maybe the issue. As all of us so far have gotten stuck with 'Gatekeep'

**Comment by bingybpo** [comment]
I’ve been having this same exact issue as well, all I can do is gatekeep, and all my opponent can do is  girlboss

**Comment by benawad** [comment]
Next time you cast your moves you should get a fresh set.
