### ISSUE TITLE
I cannot click on one of the characters.

### ISSUE THREAD

**Issue by ghostyButter** [voidpet/bugs#139]
I just started game and finished creating look of my character. When i appeared in the Atrium pool i was not able to click on the character standing in front of me. While walking around the place i was able to click on anyone else and get some part of dialouge with them. Even after reloading the site i couldn't click n the black character.

**Comment by benawad** [comment]
This one?
<img width="284" alt="image" src="https://user-images.githubusercontent.com/7872329/159164312-8715362d-3382-4d46-8fe3-8f811e34f124.png">

**Comment by ghostyButter** [comment]
Yes this one

**Comment by benawad** [comment]
What icon does it have over its head?

**Comment by benawad** [comment]
And what browser are you in?

**Comment by ghostyButter** [comment]
I'm using firefox and it have red exclamation mark above

**Comment by benawad** [comment]
If you refresh, it should be fixed now
