### ISSUE TITLE
The fumes animation does not work all the time sometimes it only shows the bottom smoke no fire

### ISSUE THREAD

**Issue by Voidpe** [voidpet/bugs#140]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ArtifexLofix** [comment]
The same thing happened to me!

**Comment by benawad** [comment]
fixed
