### ISSUE TITLE
My void pet wont gain more battles levels and its at lvl 2

### ISSUE THREAD

**Issue by Citrushus** [voidpet/bugs#141]
**Describe the bug**I fought with my void pet for 8 minutes and every fight y void pet gains nothing

**Additional context**
![broken](https://user-images.githubusercontent.com/101984301/159169500-fb9a79e7-a0cf-4513-a6c7-6b3f0f7f56bf.png)
![broken](https://user-images.githubusercontent.com/101984301/159169
![broken](https://user-images.githubusercontent.com/101984301/159169500-fb9a79e7-a0cf-4513-a6c7-6b3f0f7f56bf.png)
![broken](https://user-images.githubusercontent.com/101984301/159169512-cda9b2c4-f3da-479d-be48-262f9aa01e0b.png)

**Comment by ArtifexLofix** [comment]
Same, I got stuck a little lower though

**Comment by benawad** [comment]
If you refresh, are you stuck at the same level?
