### ISSUE TITLE
Voidpet Girlboss Attack does no damage

### ISSUE THREAD

**Issue by Jqsephh** [voidpet/bugs#142]
At the very least on ghost road with envy pet when using the girlboss attack it only does the fumes animation with no damage whatsoever.

1. Go to the ghost road with envy pet.
2. Click on any enemy
3. Go through your turns until you get the girlboss attack and then use it
4. You'll then see the animation with no follow-up damage

https://user-images.githubusercontent.com/101985091/159170393-5ee9915a-c6b1-4df0-bf5b-ecddf9114585.mov

**Comment by benawad** [comment]
should be fixed now
