### ISSUE TITLE
Crossfire deals physical and mental damage when stated it deals physical damage twice

### ISSUE THREAD

**Issue by Cobblehstone** [voidpet/bugs#145]
Crossfire is dealing physical damage and then mental damage instead of physical twice, as stated. I may be wrong about how damage types are seen in game, but I'm pretty certain physical damage is red on hit while mental damage is blue on hit. The first screenshot is the damage that was dealt, the second is what is stated it deals.
![Screenshot (13)](https://user-images.githubusercontent.com/101987111/159172272-50096d3e-4cc1-4ca9-9476-626be6113952.png)
![Screenshot (9)](https://user-images.githubusercontent.com/101987111/159172284-4885d7b6-de3d-4bf9-a523-190d820b73dd.png)
.

**Comment by benawad** [comment]
should be fixed now
