### ISSUE TITLE
White shiny may need to be bordered...?

### ISSUE THREAD

**Issue by Cobblehstone** [voidpet/bugs#146]
When you click on the white shiny to fight it on Ghost Road, this happens.
![Screenshot (8)](https://user-images.githubusercontent.com/101987111/159172368-1630e72e-4d64-42cc-ba76-391648938bf2.png)
It doesn't cause any gameplay issues, it just looks interesting and I think it could be modified.

**Comment by squidee100** [comment]
Duplicate of #143
