### ISSUE TITLE
Big voidpets on the Horto West

### ISSUE THREAD

**Issue by ArtioStudioAlt** [voidpet/bugs#147]
I don't quite know how this happened but there you go, screenie.

I just went to battle with some pets and now there is one voidpet that is way too big.

![Screenshot_20220320-175148](https://user-images.githubusercontent.com/101988534/159173629-e83ea7b8-ffb9-40b0-b819-85f973afee11.png)

**Comment by benawad** [comment]
does the large voidpet persist if you refresh the page?
