### ISSUE TITLE
Big Sprites and they Keep Switchin’

### ISSUE THREAD

**Issue by EdgyCryptid** [voidpet/bugs#148]
**The Bug**
Friendly battle pets will suddenly be large with four to a page. It started when ‘King’ appeared.

**To Reproduce**
1. Go to explore and tap up to the friendly battle area
   - May need to be level 3 or close to level 4
2. Battles work normally, though each page tap changes the big sprite

**Expected behavior**
I think ‘King’ is the only one that’s supposed to be large, but the coding is selecting one of the other sprites (one at a time) to also be big

**Screenshot**
![C4647D11-84FD-4556-9C66-1168995949F0](https://user-images.githubusercontent.com/101988356/159173549-cb6205e8-e67a-4ea7-a8c6-6c787e7a89f3.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 10s
 - OS: iOS 15.3.1
 - Browser: Safari
 - Version: Unknown

**Comment by EdgyCryptid** [comment]
Update on ahorro East:

I believe the coding is just mixing up which sprites need to be where and when.

![2AB4043C-30EF-471F-B36C-05C5DB462111](https://user-images.githubusercontent.com/101988356/159174068-c35e37e4-1db0-44b8-b05f-67191345ca4f.jpeg)

**Comment by benawad** [comment]
does the large voidpet persist if you refresh the page?

**Comment by EdgyCryptid** [comment]
Occasionally! I’ll keep poking around to make sure and see if it persists. As of now, a refresh did fix it tho, so if I had to assume, the issue just comes when your pet levels up.
