### ISSUE TITLE
big pets in the garden

### ISSUE THREAD

**Issue by nicopetz** [voidpet/bugs#150]
**Describe the bug**
after i fought with checkers the one pet in the garden turned massive, when i looked at the other garden part the same happened. when i went back to the page the bug first occurred there were 4 pets instead of the usual 3 and one was big. i tried to fix it by dying to king but nothing changed 

**To Reproduce**
i have no idea, i just fought a pet and it occurred
![Uploading 7EE05504-20A3-4AB0-8983-26919D836A8D.png…]()
 

random pets will giantify once one has. 

working from safari in my phone

**Comment by benawad** [comment]
refreshing should fix. it
