### ISSUE TITLE
Internal errors?

### ISSUE THREAD

**Issue by Erifluffball** [voidpet/bugs#151]
I'm not sure what could be causing this, but I keep getting texts on the site of internal errors, like this one in the screenshot here
![image](https://user-images.githubusercontent.com/101990800/159176272-3714a096-4085-4cfe-b3ba-ceb34ec0f476.png)

Every time this happens it's a different code though, and it doesn't seem to actually affect much, but I'm still going to report it given that it's quite odd that I'm getting those error messages anyways

**Comment by benawad** [comment]
fixed
