### ISSUE TITLE
Large voidpets on Horto E/W

### ISSUE THREAD

**Issue by DavyMaldonado** [voidpet/bugs#152]
On the Horto E/W page, there's a 4th, giant voidpet in the top corner not moving.
![Screenshot_20220320-113507_Chrome](https://user-images.githubusercontent.com/89171952/159177324-d1dfcc95-e721-44d5-b8bd-f0031a97ab5c.jpg)
![Screenshot_20220320-113517_Chrome](https://user-images.githubusercontent.com/89171952/159177328-76c4f10b-be36-4617-acbe-afff8fcb7076.jpg)

**Comment by benawad** [comment]
try refrehsing
