### ISSUE TITLE
Pet no longer gaining experience 

### ISSUE THREAD

**Issue by Yeetn8do** [voidpet/bugs#153]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by benawad** [comment]
Does this persist after you refresh the page?

**Comment by Yeetn8do** [comment]
Yes it does. I’ve refreshed a couple times. Closed out completely and came back periodically. Pet is at lv 4 with no increase in exp

**Comment by benawad** [comment]
Lvl 4 is the current lvl cap we will be raising it next update
