### ISSUE TITLE
Huge voidpets in garden

### ISSUE THREAD

**Issue by AceIsC00l** [voidpet/bugs#154]
So in the garden there are huge voidpets and I mean like HUGE I’ll attach pictures somehow but nothing is wrong they just are really big and their hit boxes grew with them
![F6DA253B-E0AA-4011-9C96-7D246589F3C4](https://user-images.githubusercontent.com/101997146/159186323-cae1977e-63c1-4698-8eb6-f48e28aebe57.png)
![26784FAD-7B49-495E-8473-1B4FF72AC10B](https://user-images.githubusercontent.com/101997146/159186329-210e7bfa-3eba-4f7c-af0a-3bebc441c6ec.png)
![Uploading 388C63D4-323E-484E-9AF9-DC5F6F584202.png…]()

**Comment by benawad** [comment]
try refreshing
