### ISSUE TITLE
Cuddle button gone

### ISSUE THREAD

**Issue by asherwisco** [voidpet/bugs#156]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

I have an XR IPhone if that’s what the instructions wanted me to do. 

The bug is that I cannot cuddle with my voidpet, as the button is gone. 
![CDB7F1E0-0E3B-46B5-B6B4-730050A74D63](https://user-images.githubusercontent.com/102005869/159198790-bccef1e7-211e-48aa-9526-6bd9324a92a9.png)

I tried to add a photo there. In my screen it shows up as a link, I’m not sure if it will work.

**Comment by squidee100** [comment]
Could you provide a screenshot of the "Play with NAME" screen?

**Comment by benawad** [comment]
hover over the pet to pet it
