### ISSUE TITLE
Is it normal to not have a secondary element in my move set?

### ISSUE THREAD

**Issue by Zyrgil** [voidpet/bugs#157]
Aside from my own element (which is fire), I only ever see black colored moves while I can see that others have a second element that they can choose from in their move set (aside from their natural element and black). Is that intended? 

**Other's move set:**
![Screenshot_20220320-234919](https://user-images.githubusercontent.com/101995011/159207348-73dd221c-6f72-4cc6-bf64-c64be757b342.png)

![6aeb76a7af53e4e6d45fafdf4d970a32](https://user-images.githubusercontent.com/101995011/159207471-abba2994-2da8-4c53-9944-383e970cc616.png)

**My move set:**
<img width="529" alt="dasda" src="https://user-images.githubusercontent.com/101995011/159207507-72280b75-09f6-465c-8b63-84afb9ae79e2.png">

<img width="558" alt="sdda" src="https://user-images.githubusercontent.com/101995011/159207513-a31bb59d-b91f-4dbc-a66f-39cc07506c03.png">

**Comment by squidee100** [comment]
Fire only has the two elements.

**Comment by benawad** [comment]
Expected behavior
