### ISSUE TITLE
Pet is no longer gaining more experience regardless of which void I fight

### ISSUE THREAD

**Issue by ArtifexLofix** [voidpet/bugs#158]
**Describe the bug**

**To Reproduce**

**Expected behavior**
My pet should gain experience from each fight I win until level 4.

**Video or Screenshots**
![Uploading 789EE988-5A91-4C2B-A312-A5364BADCE26.
![CC785424-6152-427A-B6AD-672C1A6BD678](https://user-images.githubusercontent.com/101985943/159250431-ab4d298f-112e-4f83-827d-452cc65af0e8.png)
png…]()

![DA7756A3-5327-46E7-8EEA-453EB69ABDDB](https://user-images.githubusercontent.com/101985943/159251029-aa53f7b9-ccfb-4d47-ac75-5d2ce2a524d4.png)
![58288D1E-7519-465C-A1F1-9B6127D416FB](https://user-images.githubusercontent.com/101985943/159251046-3285d186-4d42-4552-8767-2ee94e79b591.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [iPhone 11]
 - OS: [iOS 15.3.1]
 - Browser [safari]

**Additional context**
When I was playing yesterday my anger suddenly stopped gaining any experience or levels from fighting. I refreshed the page and nothing happened so I decided to stop playing for the day. The issue persisted today so I chose to report it. My anger is level two and the max is four so I haven’t found a reason why they should have stopped levelling up.

**Comment by Ajoynes** [comment]
I am also having that same issue

**Comment by squidee100** [comment]
The two images you provided suggest that your pet **_is_** levelling up.

**Comment by benawad** [comment]
Try refreshing if you see it pause
