### ISSUE TITLE
XP not raising

### ISSUE THREAD

**Issue by marygrace1o1** [voidpet/bugs#162]
I have reached level 4 on my pet, but as I continue to fight and gain XP, the bar of my point level does not increase. 

1. Get to level 4 of XP
2. Go to explore
3. Click on fight (for any void pet)
4. Fight and win
5. See error in the XP bar

Images of examples:
<img width="481" alt="Screenshot 2022-03-21 150107" src="https://user-images.githubusercontent.com/102076291/159345192-5a24be6f-436d-40e4-a44e-908ea4ba1e89.png">
![image](https://user-images.githubusercontent.com/102076291/159346102-40f86459-dd3d-43c6-99a7-e0e8d42a7aa1.png)
![image](https://user-images.githubusercontent.com/102076291/159346138-b76fbbe7-e207-4027-8782-916a6388f8f3.png)

**Comment by marygrace1o1** [comment]
![image](https://user-images.githubusercontent.com/102076291/159345686-b6e9d5cc-1f52-419b-8947-d390c289671a.png)

**Comment by marygrace1o1** [comment]
![image](https://user-images.githubusercontent.com/102076291/159345961-6c8bd4ae-3024-47e3-8a8d-053a72da11bc.png)

**Comment by newtify** [comment]
Level 4 is the cap right now
