### ISSUE TITLE
Not reaching past lvl 2 during battle

### ISSUE THREAD

**Issue by lockqygen** [voidpet/bugs#165]
I have been doing the friendly battles with my voidpet and it reaches level 2 (102/102) and then resets that level. It's done this 3 times.

**To Reproduce**
I just beat other voidpets in battle multiple times and it continuously refused to give me my points.

**Expected behavior**
i expected it to continue leveling me up when I beat other voidpets in a friendly battle.

**Video or Screenshots**
![Screenshot_20220321-182126_Chrome](https://user-images.githubusercontent.com/102112076/159379598-97fae69d-f1b3-46d0-86c6-bb3e0b305b7d.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Samsung a10
 -
 - Browser: chrome
 - 

**Additional context**

**Comment by lockqygen** [comment]
my voidpet username is lockx

**Comment by benawad** [comment]
Blue bar is xp, green is health
