### ISSUE TITLE
No XP

### ISSUE THREAD

**Issue by Mvrkjr** [voidpet/bugs#167]
**Describe the bug**
On lvl of ur voidpet, XP is awarded but not xp shows up on the bar.

**Comment by v0idCactus** [comment]
When I earn xp,the xp bar doesn't move so I can't lvl up

**Comment by UserJHansen** [comment]
What level are you?

**Comment by mariepiercm2** [comment]
I am on lvl 4 and getting this issue as well

**Comment by UserJHansen** [comment]
Lvl 4 is the cap for now, he mentioned this in the discord announcement, but it might not be mentioned in the game?

**Comment by mariepiercm2** [comment]
Oh thank you UserJHansen I didn't know, all good on my part then :)

**Comment by UserJHansen** [comment]
all good, should be good to close this then

**Comment by sutomu** [comment]
I'm still in level 2. The Xp bar doesn't work :(
![IMG_20220324_191816](https://user-images.githubusercontent.com/102321150/159984297-e1c3ad26-6c57-48a0-abc6-29725aabc17e.jpg)

**Comment by UserJHansen** [comment]
It looks like it's working?

**Comment by sutomu** [comment]
Oh! Sorry, it works, but the process of leveling up is very slow, I had not realized that it progressed so slowly. I was hoping to level up faster. Sorry

**Comment by TheLostKitsuneNichizora** [comment]
It sayss i gain XP but it doenst show at all
