### ISSUE TITLE
Missing title for most pages

### ISSUE THREAD

**Issue by UserJHansen** [voidpet/bugs#168]
**Describe the bug**

The title in the browser just shows as the URL because it is not defined. 

**To Reproduce**
1. Go to voidpet.com
2. Click Play
3. See error

**Expected behavior**

There should be a proper title or even just keeping the simple [username] | Voidpet

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/47265397/159654516-7da9f4b8-a34a-48d2-b80c-cf0cac481de4.png)

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any
 - Version: Latest

**Smartphone (please complete the following information):**
None really because you don't really see the title

**Additional context**
Just some default <title> tags should fix it

**Comment by benawad** [comment]
fixed
