### ISSUE TITLE
Can't go to the other side of Battle area

### ISSUE THREAD

**Issue by Hundead** [voidpet/bugs#169]
I completed another battle and now the right button to go to the right side of the field, I completed about 4-5 battles before this happened.

**Smartphone (please complete the following information):**
 - Device: Motorola
 - Browser: Chrome

**Comment by benawad** [comment]
Could you screenshot it

**Comment by Hundead** [comment]
It fixed itself after refreshing but now the buttons take 2-3 clicks/taps before I actually move.
