### ISSUE TITLE
Battle Animations freezing 

### ISSUE THREAD

**Issue by Fungist** [voidpet/bugs#171]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by squidee100** [comment]
Could you provide a screenshot/screen recording or more info?

**Comment by squidee100** [comment]
That didn't come through. Try sending it through the issue page on the github website.

**Comment by Fungist** [comment]
Doesn’t seem to let me upload my screen recording here

**Comment by benawad** [comment]
should be much faster now, let me know if the problem persists
