### ISSUE TITLE
Time rewind bug

### ISSUE THREAD

**Issue by Dusk18** [voidpet/bugs#172]
**Describe the bug**
User storage was reset to about two days ago, multiple users had this problem, was fixed when resetting the website
**To Reproduce**
No steps needed, happened as website was opened
**Expected behavior**
Expected to have level four evolved envy

**Video or Screenshots**
two are to show as it happened and after resetting, king win is proof of being level four beforehand (and maybe to flex a little) (king win photo appears to not be showing, so just trust me)
![8CE141B0-6F0B-4F67-AB78-00DA6022A789](https://user-images.githubusercontent.com/102377073/160162040-117e2148-80f5-4c7a-95b6-83ac62335876.png)
![334A3A69-A190-484D-8B91-56E85423B307](https://user-images.githubusercontent.com/102377073/160162043-a4cc8f22-6115-4620-99cf-369fa9306b30.png)
![B30603AF-EF15-4C5A-BEB2-EF0422C6D9BF](https://user-images.githubusercontent.com/102377073/160162048-af138cd7-9a92-49e7-90bf-139dfe9b1b30.

**Smartphone (please complete the following information):**
 - Device: 2020 iPhone se
 - OS: iOS 15.4
 - Browser: Safari 
 - Version: unknown atm

**Comment by benawad** [comment]
closing in favor of #173
