### ISSUE TITLE
Rewind bug again

### ISSUE THREAD

**Issue by Dusk18** [voidpet/bugs#173]
I already submitted a bug report for this and it fixed itself, but now it’s reset again, 202 iPhone se, iOS 15.4, safari 
![02E10F56-A379-43A0-AA6A-19C14349B1C9](https://user-images.githubusercontent.com/102377073/160172457-73705b44-1641-44c3-a314-e44f644fe262.png)
![0D3BF625-7416-4D30-AE55-602021BDB86E](https://user-images.githubusercontent.com/102377073/160172460-cdea8e2d-ac96-40b7-a582-e0abeca71be0.png)
Please fix this soon, I want to increase my voidpet s bond level to 3 and I can’t really do that as of now

**Comment by Dusk18** [comment]
I went to settings and then delete account then went back to home and it was reset, I don’t know if that was because of timing or from manipulating the code through the screen initializations

**Comment by benawad** [comment]
Are you able to replicate the bug consistently? Or do you just sometimes see your pet as level 2?

**Comment by benawad** [comment]
should be fixed now
