### ISSUE TITLE
Limited selection of moves 

### ISSUE THREAD

**Issue by KeithyBoii** [voidpet/bugs#174]
**Describe the bug**
Whenever battling other voidpets, my voidpet only has the same selection of about 6 moves, and any other moves don’t show up.

**To Reproduce**
Getting into battle

**Expected behavior**
A larger selection of moves or an explanation on how the move/battle system 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone SE2]
 - OS: [e.g. iOS15.3.1]

**Additional context**

**Comment by benawad** [comment]
intended behavior
