### ISSUE TITLE
Little Green on the screen

### ISSUE THREAD

**Issue by DrGeinstkraft** [voidpet/bugs#175]
![kékécé](https://user-images.githubusercontent.com/102431502/160251939-7837b794-2525-43a7-baeb-c105b43f63c6.PNG)

i have a little question : what is that ?
I mean...I ONLY see on the ghost road....In all 3 case....But when you go on the caster or frendly zone...it disapear....whut ? what"s that ? Sombody 
btw, the game is really cool, i love him :) 

![1](https://user-images.githubusercontent.com/102431502/160252205-cf8d0423-b2a7-4c7a-9a66-ee2164d3972d.PNG)
![2](https://user-images.githubusercontent.com/102431502/160252207-a2c9415c-c825-4182-a457-2adb6cc637ee.PNG)

![3 Bis](https://user-images.githubusercontent.com/102431502/160252201-7c02e64e-b3b7-48cf-88c4-6554b569ff60.PNG)
![4](https://user-images.githubusercontent.com/102431502/160252202-0eaf343b-bedf-443e-a8e2-2c14b0947ca8.PNG)

![3](https://user-images.githubusercontent.com/102431502/160252199-f238e684-ca7a-4239-a523-25cd1c78c050.PNG)
?

**Comment by DrGeinstkraft** [comment]
ho and, btw, when a little pet pass on the green, it disapear too, like it whan on the decort and the pet ON the decord idk if you understand sorry...

**Comment by benawad** [comment]
easter egg :)
