### ISSUE TITLE
Animation Lag

### ISSUE THREAD

**Issue by Philotes05** [voidpet/bugs#176]
There has been an issue with the game recognizing the fighting animations with every battle I’ve had while playing. I’ve tried playing on both wifi and data to see if it was an internet issue on my end, but it was still doing it. My boyfriend, who I got to play the game with me, says he’s having the same issues on his end.

**Comment by Philotes05** [comment]
We both play on our IPhones btw. I don’t know if that’s important or not. But yeah.

**Comment by squidee100** [comment]
Potential duplicate #171

**Comment by benawad** [comment]
should be much faster now, let me know if the problem persists
