### ISSUE TITLE
Problem clicking menu button on explore page

### ISSUE THREAD

**Issue by squidee100** [voidpet/bugs#177]
**Description**
The title div blocks the menu button in the explore page, making part of the button un-clickable

**Steps to reproduce the behavior**
1. Go to the explore page
2. Click on the top half of the menu button in the top left
3. Cannot click button

**Expected behavior**
You would expect the button to not be blocked by the div and be clickable

**Screenshots**
![image](https://user-images.githubusercontent.com/29834597/160391652-006dbb11-36b1-4b0c-b885-deac8d10c852.png)
Title div blocking the button

![image](https://user-images.githubusercontent.com/29834597/160391708-b87e5512-64a8-420b-9ea6-58fe123fa24f.png)
Top half (default cursor)

![image](https://user-images.githubusercontent.com/29834597/160391726-be95379c-5676-4bb8-9671-192a0bff4ee0.png)
Bottom half (pointer cursor)

**Desktop**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 99

**Comment by benawad** [comment]
fixed
