### ISSUE TITLE
Battle Lvl glitch + evolution 

### ISSUE THREAD

**Issue by SleepySero** [voidpet/bugs#179]
**Describe the bug**
 After grinding up exp , my pet finally got to level 4 but when the blue/exp bar went up it just refreshed and went all the way back down to level 3 and 0 xp.. It’s done this twice now
 
![B5F92EFF-9631-4870-A765-8378E5F12300](https://user-images.githubusercontent.com/102610759/160652996-46b0ac16-b0b0-4f77-8ceb-fe60ac697b35.jpeg)

 - Device: [Iphone 8]
 - OS: [iOS 15.2.1]
 - Browser [safari]
 - Version [not sure?]

**Additional context**
Before the xp+ level restarted, it said something about evolving then before it finished the whole site just made me go back

**Comment by benawad** [comment]
Did refreshing fix it for you?
