### ISSUE TITLE
Not exactly a bug and it was my mistake

### ISSUE THREAD

**Issue by Croissantdepoisson** [voidpet/bugs#180]
I accidentally payed for giga for 2 years instead of 1 and I don't know who to contact about maybe getting a refund on 1 of them if possibly

**Comment by benawad** [comment]
I can refund you, what’s your voidpet username?

**Comment by Croissantdepoisson** [comment]
> Croissantdepoisson I think

**Comment by benawad** [comment]
Refunded, might take a few days to show up on your credit card
