### ISSUE TITLE
Jittering issue

### ISSUE THREAD

**Issue by ChaotixG** [voidpet/bugs#181]
When playing in exploring for a while the game starts jitering and animations start lagging. Ive only played it in chrome on my phone so im not sure if chrome is the cause. Im on an android s20 FE and the os is android 12.

**Comment by benawad** [comment]
How long is a while?

Does refreshing solve it?

**Comment by ChaotixG** [comment]
About 15 -25min and refreshing solves it

**Comment by benawad** [comment]
closing in favor of #307
