### ISSUE TITLE
Unable to Explore

### ISSUE THREAD

**Issue by CrypticBeast2** [voidpet/bugs#184]
**Describe the bug**
When opening the Explore menu, it doesn't open the explore at all, simply text.
![Screenshot_20220403-140023-199](https://user-images.githubusercontent.com/102921219/161441726-5a762c32-0793-487c-aa9d-3159fe59c2f5.png)

**To Reproduce**
1. Go to 'Explore'
2. Click on 'Explore'
3. See error

**Expected behavior**
A blank screen with text, unable to explore

**Smartphone (please complete the following information):**
 - Device: Moto G Stylus
 - OS: Android 11
 - Browser: Firefox

**Comment by benawad** [comment]
This is a caching problem.

1. Try refreshing
2. Try another browser
3. Try clearing the cache on your browser or  uninstalling/reinstalling your browser
