### ISSUE TITLE
Voidpet "Impossible State"

### ISSUE THREAD

**Issue by Honigbear** [voidpet/bugs#186]
I was playing Voidpet on my chromebook when I got this message and it told me to report it :
![Screenshot 2022-04-04 9 10 49 PM](https://user-images.githubusercontent.com/103012440/161665749-4ab54985-4685-4694-9900-a15a733a64f7.png)
)

**Comment by LightShade1301** [comment]
I just had the same issue

**Comment by benawad** [comment]
Does opening voidpet in a new tab fix it for you?

**Comment by Honigbear** [comment]
Why yes it does, thank you very much benawad!
