### ISSUE TITLE
"Impossible state"

### ISSUE THREAD

**Issue by gizmochloe** [voidpet/bugs#187]
Hello. When exploring the area a bit too much, I've reached this page. If I reload and login, it brings me back to this page. I hope you can help.

My username is sootwebs

![image](https://user-images.githubusercontent.com/103012437/161665828-28bcfa4b-c6b4-4b4b-a47d-237c3b62c703.png)

**Comment by benawad** [comment]
Does open voidpet in a new tab fix it for you?
