### ISSUE TITLE
Bug Report “Impossible State”

### ISSUE THREAD

**Issue by LightShade1301** [voidpet/bugs#189]
Had this pop up and was told to report it 
My username is LightShade
![Uploading 8FCAFE8A-A2A3-4B25-8E39-AD83B4F20629.jpeg…]()

**Comment by benawad** [comment]
Does open voidpet in a new tab fix it for you?

**Comment by LightShade1301** [comment]
> Does open voidpet in a new tab fix it for you?

Yeah it does
