### ISSUE TITLE
Impossible screen

### ISSUE THREAD

**Issue by JeZhang2** [voidpet/bugs#191]
**Describe the bug**

I pressed explore and ended up on a report bug screen

**To Reproduce**

Played with my pet, got most things to 100 except for dopamine, went back to hit explore, clicked explore, bug issue notice appeared.

**Expected behavior**
![Immpscreen](https://user-images.githubusercontent.com/70858304/161666641-daba12ee-a85f-44a6-99e7-cd7f8176f37a.PNG)

Continue to the explore world screen

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.
![Immpscreen](https://user-images.githubusercontent.com/70858304/161666641-daba12ee-a85f-44a6-99e7-cd7f8176f37a.PNG)

**Desktop (please complete the following information):**
 - OS: [Windows 11
 - Browser [Opera]
 - Version [LVL 3 core: 84.0.4316.52]

**Additional context**
![Immpscreen](https://user-images.githubusercontent.com/70858304/161666435-0805c9a4-9acb-4555-a827-2d98f230a218.PNG)

**Comment by benawad** [comment]
Does opening voidpet in a new tab fix it for you?
