### ISSUE TITLE
Logged out of voidpet, unable to log back in

### ISSUE THREAD

**Issue by TeSnurp** [voidpet/bugs#194]
Hello, I have an issue where I am unable to log back into my voidpet account. Everytime I try to log back in it says user not found.

![Screenshot_2022-04-05-10-23-24-61](https://user-images.githubusercontent.com/103013221/161667932-f2bc6164-e188-40c6-8d17-134d20007d41.jpg)

**Comment by benawad** [comment]
Should be fixed now

**Comment by TeSnurp** [comment]
Thank you!!
