### ISSUE TITLE
impossible state

### ISSUE THREAD

**Issue by Davs13** [voidpet/bugs#197]
![Screenshot_20220405_104535_com android chrome](https://user-images.githubusercontent.com/103013854/161669366-fa07e4d3-04b7-4114-a85b-39cf591a3f38.jpg)

**Comment by benawad** [comment]
Does opening voidpet in a new tab fix it for you?

**Comment by Davs13** [comment]
> Does opening voidpet in a new tab fix it for you?
yeah thanks✌️
