### ISSUE TITLE
no way to get off this screen

### ISSUE THREAD

**Issue by cloud222222** [voidpet/bugs#198]
<img width="1436" alt="Screen Shot 2022-04-04 at 10 56 24 PM" src="https://user-images.githubusercontent.com/103014263/161670509-0da4dfa2-faca-43cf-8525-8239ae951345.png">

no containers, no way to get off this screen

**Comment by benawad** [comment]
What's your voidpet username?

**Comment by cloud222222** [comment]
Lola thank you!!

**Comment by cloud222222** [comment]
lolav sorry about that

**Comment by benawad** [comment]
pushed an update for this, try refreshing if you don't see the button you can also try opening voidpet in a new tab
