### ISSUE TITLE
Inconsistent names of voidpets

### ISSUE THREAD

**Issue by rjmcf** [voidpet/bugs#2]
"Sad" and "Anxious" are both adjectives (e.g. "I am sad", "I am anxious"), while "Anger" is a noun (e.g. "I feel my anger"). I think if the name of the voidpet is the emotion, then they should all be nouns (i.e. "Sadness", "Anger", "Anxiety"), but I could see it working with adjectives too (i.e. "Sad", "Angry", "Anxious"), I just don't think the mix really works.

**Comment by benawad** [comment]
https://github.com/voidpet/bugs/blob/main/README.md#inconsistent-names-of-voidpets
