### ISSUE TITLE
Google allows users to bypass passphrase input

### ISSUE THREAD

**Issue by samuel0480** [voidpet/bugs#20]
When searching 'voidpet' on google, you can immediately bypass the passphrase requirement by clicking 'login with discord'.
![image](https://user-images.githubusercontent.com/6138209/145724869-32037550-d1d6-472f-97b4-9986ccd56a26.png)

**Comment by DumbGameMaker** [comment]
fix: robots.txt disallow the login page

**Comment by benawad** [comment]
I like leaving this hack in
