### ISSUE TITLE
hi, i reached an impossible state

### ISSUE THREAD

**Issue by somepersonidk** [voidpet/bugs#200]
**Describe the bug**
![Screenshot 2022-04-05 3 11 05 PM](https://user-images.githubusercontent.com/102134396/161671663-43b0f9a9-5a9d-4317-9b65-5389acdd6788.png)

**Additional context**
My discord was band for some shitty things i did, but voidpets hes still been running fine (nothing that directly harmed someone, i was just very active in a sh comunity on discord. i left the server and blocked everyone who was on it in my recovery. it still got band 7 months after i left. just so you know im not a complete dick)

**Comment by benawad** [comment]
Does opening voidpet in a new tab fix it for you?

**Comment by somepersonidk** [comment]
im dumb lmao, it does thanks :)
