### ISSUE TITLE
Pet switching issue

### ISSUE THREAD

**Issue by frickity-frack** [voidpet/bugs#201]
**Describe the bug**
I have a level 4 anger, and when i switch to my captured level 4 lonely, only the eyes swich, so it's the lonely eyes out of place on the anger's body

To reproduce
1. enter a fight that cannot be won using one voidpet
2. have first voidpet die
3. switch to level 4 lonely

The entire pet should switch over, but the lonely's body doesn't
*stats still do so the actual switching of the pet is evident, it's a purely visual issue*

![image](https://user-images.githubusercontent.com/103015157/161673056-aefd1ec1-a845-46ad-a533-7fbc14ef03ce.png)

**Desktop (please complete the following information):**
Microsoft windows on chrome (sorry i don't know much more than that)

**Comment by benawad** [comment]
fixed
