### ISSUE TITLE
“Impossible State Reached” Screen

### ISSUE THREAD

**Issue by ebooth24** [voidpet/bugs#209]
![639B2B33-2608-49A3-B9E4-702711D62B6F](https://user-images.githubusercontent.com/65963000/161745960-6490e62d-268b-4aed-985c-91b9bd04b3dd.png)

I’m using Google Chrome on an iPhone SE 2nd Edition, iOS 15.4.1

**Comment by benawad** [comment]
Does opening voidpet in a new tab fix it for your?
