### ISSUE TITLE
Username

### ISSUE THREAD

**Issue by Memergirl247** [voidpet/bugs#21]
When I first logged into the void pet site I used the username Memergirl247 and now when I come back from logging in with my discord and use my username it says that it has been taken. I don't know what to do now cuz it said that "if you already claimed a username, enter it and we'll verify that it's yours", but it still hasn't done anything :(

**Comment by benawad** [comment]
Pick a different username, tell me what it is and I'll switch it to `Memergirl247` afterwards

**Comment by Memergirl247** [comment]
It's just Memergirl and thank you for the help 😋

**Comment by benawad** [comment]
Try logging in with the discord `Memergirl247#3836`, not `Memergirl247#8461`
