### ISSUE TITLE
When trying to catch a wild voidpet i "lose" my account

### ISSUE THREAD

**Issue by ShadyStatistics** [voidpet/bugs#211]
I try to catch a voidpet (because of the quests) and when I try to name it, it says that there is an error which leads to me refreshing and then it takes me to the "password" screen. When I try to log in it says it can't find my account

1. Catch a wild Voidpet
2. Try to change name
3. Enter the name you want

![c](https://user-images.githubusercontent.com/103049092/161767003-457828f1-8b88-4fe6-8294-96f275f735fd.JPG)

 - OS: [Windows 10]
 - Browser [chrome]
 - Version [21H2]

**Comment by benawad** [comment]
Try refreshing this should be fixed now, unfortunately the bug lost the pet you tried to catch
