### ISSUE TITLE
Impossible State reached 

### ISSUE THREAD

**Issue by angrywafflle** [voidpet/bugs#213]
When i went to the court, I opened up to the furthest right section. I couldn't go left, so I went right and opened up to an impossible screen. 
![Screenshot 2022-04-05 10 13 48 AM](https://user-images.githubusercontent.com/103052176/161774893-fa12edaf-c928-453a-b39e-7294fe8897bc.png)

I expected to not be able to access the furthest right, or open up to a secret area

**Desktop (please complete the following information):**
 - Google Chrome O
 - Chrome
 -  99.0.4844

**Additional context**

**Comment by benawad** [comment]
Does opening voidpet in a new tab fix it for your?
