### ISSUE TITLE
Newly caught voidpets do not show 

### ISSUE THREAD

**Issue by squashku** [voidpet/bugs#222]
**Describe the bug**
When catching new voidpets, they either do not show up with my other voidpets (only displaying my first 3, the other two do not show up). For the quest to catch 20 of them, I had caught one that did not register as one of the twenty but the two I caught after did show up. However, I still cannot see any of the new voidpets I have caught. I named them and did everything normally. 

**To Reproduce**
1. Go to 'back home'
2. None of the other voidpets register besides my first three. 

**Expected behavior**
I thought it would show me all my new voidpet friends! But it only shows Wisp, Canary and Lou. 

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Microsoft surface laptop 3
 - OS: [e.g. iOS8.1] ?
 - Browser: chrome
 - Version [e.g. 22] ?

**Additional context**

**Comment by benawad** [comment]
Can you screenshot a picture of your memory page

**Comment by benawad** [comment]
checkout #223
