### ISSUE TITLE
Spacing on the bottom of the page while scrolling with the menu open

### ISSUE THREAD

**Issue by TCezarRod** [voidpet/bugs#23]
If we scroll the page while the menu is open, there will be an odd padding on the bottom of the main container until the scrolling finishes. Only then, the page will readjust to the full height.

I'm using Brave browser on an Android phone.

https://user-images.githubusercontent.com/9112403/145727595-cb0d38e5-ad2f-4a13-912f-4dfcad6f91b1.mp4

**Comment by DumbGameMaker** [comment]
related to #25?

**Comment by benawad** [comment]
I don't feel like fixing this
