### ISSUE TITLE
Cant have more than three voidpets and lost a cool colored one it was white

### ISSUE THREAD

**Issue by Jkraa** [voidpet/bugs#240]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Lilith-6** [comment]
I've been having the same issue, I also lost a white colored one and two "illusive" ones that were a blue/cyan color.

**Comment by benawad** [comment]
see #223
