### ISSUE TITLE
Internal error when swapping to a new pet

### ISSUE THREAD

**Issue by Miizzen** [voidpet/bugs#244]
I was fighting a voidpet to take a look at the one I just captured and it died, when I tried to swap to a new pet (that would be my old pet) it showed an internal error, I tried refreshing the page and going back to the menu but every time I open "Explore" again I'm stuck in that part of swapping the pet where the error happened

![image](https://user-images.githubusercontent.com/103066510/161820863-defdd776-821f-45c9-b51a-ef6bc5077ebd.png)
A screenshot of the moment it happened, the code kept changing every time I clicked tho

**Comment by Chaotic1234** [comment]
Im having the same issue
![Voidpet error](https://user-images.githubusercontent.com/103067058/161822974-bf1cd096-c20f-4876-8d70-61daa895cac4.PNG)
.

**Comment by benawad** [comment]
Could you trigger the error 1 more time

**Comment by Chaotic1234** [comment]
![Error 2](https://user-images.githubusercontent.com/103067058/161824504-0d0b2b43-1bfa-44ee-8a1d-4af29a580557.PNG)
![Error 3](https://user-images.githubusercontent.com/103067058/161824515-b16cbd54-9803-4041-9c37-e59a16e11d78.PNG)
![Error 4](https://user-images.githubusercontent.com/103067058/161824524-0f7a211d-5647-4444-8e62-78a66ed89806.PNG)
Heres a few more

**Comment by benawad** [comment]
I pushed an update to fix this next time you refresh.

You can also click on the pet before clicking the button

**Comment by Miizzen** [comment]
Now it worked, thank you! :)
