### ISSUE TITLE
Cant do anything

### ISSUE THREAD

**Issue by You6553** [voidpet/bugs#245]
I've had a voidpet account since I first saw it on tik tok last year. I keep seeing in the discord server that we can do things and that you can play with your voidpet and get new ones ect. I am unable to do any of this on my account and I have refreshed the page multiple times and signed out and back in again yet I'm still unable to do anything with my voipet

**Comment by benawad** [comment]
Have you played with your Voidpet? That is required to unlock explore

**Comment by You6553** [comment]
I'm unable to even do that. I have a friend who has an account and has showed me what they do to play with their voidpet and other things too and it shows they have a button saying 'play with *voidpet's name* ❤' but this button is non-existent when I open up my account.

**Comment by benawad** [comment]
Did you pick a start already? Was it envy? What happens when you click the hamburger menu and click home does it stay on this page?

**Comment by You6553** [comment]
Yes the starter pet I chose was envy and when I click on the menu and on home it stays on that screen

**Comment by benawad** [comment]
Could you try another browser real quick so we can isolate that that's not the problem

**Comment by You6553** [comment]
Sorry for the late reply I completely forgot about this but I will try immediately

**Comment by You6553** [comment]
It won't allow me as it keeps asking for a discord I've linked it too but I have not linked it to a discord account

**Comment by benawad** [comment]
We changed it so you will need to link your discord

**Comment by You6553** [comment]
I've managed to log in without it :)

**Comment by You6553** [comment]
![Screenshot_20220409-202631_Edge](https://user-images.githubusercontent.com/103062159/162588939-ded1d06f-71a3-4ba4-a397-e23b57222f07.jpg)

This one is from Microsoft Edge and the original one attached was from Google chrome

**Comment by benawad** [comment]
How do you login without it?

**Comment by You6553** [comment]
I typed in "voidpet.com/v0idpets" v0idpets is my user

**Comment by benawad** [comment]
you have 2 options
1. Create a new account with Discord and play on that 
2. Create a new account with Discord and I'll merge it with `v0idpets`

**Comment by You6553** [comment]
Ok Thank you I'll just make a new account as I won't have lost any progress and it will give me a chance to choose a different starter pet too.
