### ISSUE TITLE
Can't log in 

### ISSUE THREAD

**Issue by Kiwi1star** [voidpet/bugs#246]
I'm playing from an Android phone, I just got a new phone and now whenever I go to log into my account by pressing the "I already have an account button" I get sent to a screen that says this. 

`l
![Screenshot_20220405-115150](https://user-images.githubusercontent.com/103068873/161828617-c0e106ce-eb18-42c5-b925-af079a6611e4.png)

**Comment by benawad** [comment]
Looks like discord requires a different browser try installing the chrome app
