### ISSUE TITLE
Weird name bug in the memory

### ISSUE THREAD

**Issue by ZoranaDragon** [voidpet/bugs#247]
I forget a void and it shrinks the text boxes for the names. It's purely visual and fixes itself when the page refreshes.

I'm on an Android if that helps at all.

Video of what happens:
https://user-images.githubusercontent.com/101988644/161828658-7a5d2da7-2039-444e-9e20-16c934ba85a5.mp4

**Comment by benawad** [comment]
closing in favor of #348
