### ISSUE TITLE
Catching Glitch

### ISSUE THREAD

**Issue by vesp4** [voidpet/bugs#252]
https://user-images.githubusercontent.com/103070297/161832534-4480dbd1-d40c-4131-810b-b175c98dafe8.mov

Was in catch for illusive, first catch failed then subsequent catches would load but do nothing. Video attached, very sad. Was on data so shouldn’t be an internet issue, also on mobile iOS.

**Comment by benawad** [comment]
Did you say there was a video to see?

**Comment by benawad** [comment]
Were you playing on multiple devices or tabs by chance?

**Comment by vesp4** [comment]
no, i was only on my phone.

**Comment by vesp4** [comment]
hey so it happened again… with another vivid. i tried with a regular lonely right after and the catching works fine for them. i’ll attach the vids.

https://user-images.githubusercontent.com/103070297/161835587-739e7584-bd70-4b93-96f1-d47effddac0f.MOV

**Comment by vesp4** [comment]
heres with a regular lonely… this is pretty brutal. 

https://user-images.githubusercontent.com/103070297/161835744-ae356538-6ca7-40f1-95a6-04b85db94800.MOV

**Comment by Btsebast** [comment]
Also experiencing this on desktop only 1 tab

https://user-images.githubusercontent.com/63477111/161838624-fa88a30b-dfb9-4e9c-9b88-09a17dd58333.mov

**Comment by benawad** [comment]
should be fixed now
