### ISSUE TITLE
Overspawn

### ISSUE THREAD

**Issue by YeenOnABean** [voidpet/bugs#255]
**Describe the bug**
On ghost road there are 12 regular voidpets spawned, when usually there seems to be 3 or 4.

**To Reproduce**
I'm not sure

**Expected behavior**
3-4 voidpets

**Video or Screenshots**
![Screenshot_20220405-151217_Chrome](https://user-images.githubusercontent.com/103070446/161833670-640438e8-2464-4675-bed0-a9bd769777e9.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy s20 fe 5g
 - OS: android 12
 - Browser: chrome
 - Versio: no clue

**Additional context**
Refreshing doesn't help

**Comment by benawad** [comment]
intended
