### ISSUE TITLE
Catching Frenzy Quest is off by 1

### ISSUE THREAD

**Issue by Btsebast** [voidpet/bugs#258]
Caught 20 lonlies only shows up as 19 

21 voidpets - 1 starter = 20 lonlies caught
<img width="496" alt="Screen Shot 2022-04-05 at 3 20 07 PM" src="https://user-images.githubusercontent.com/63477111/161842629-0dc9fcea-2948-4784-a1cb-d6b673705dbb.png">

<img width="1680" alt="Screen Shot 2022-04-05 at 3 19 46 PM" src="https://user-images.githubusercontent.com/63477111/161842625-4174ec22-41bd-43ba-b8b5-84ac6ba634d8.png">

**Comment by benawad** [comment]
Did you complete the first catch before this?

**Comment by Btsebast** [comment]
yes

**Comment by benawad** [comment]
That has you catch 1 lonely so that should add up to 21 - starter - first quest = 19
