### ISSUE TITLE
Able to access other profiles + emoji not being rendered.

### ISSUE THREAD

**Issue by abhinavgeethan** [voidpet/bugs#26]
Don't know if this is a bug (since "Explore" is disabled as well) but, currently able to access other users' profiles by changing the username on the URL.

Screenshot: I'm logged in as **abhi** viewing **benawad**.
![image](https://user-images.githubusercontent.com/72859534/145730257-6f739397-471e-4705-82d9-a33f429bf3e7.png)

Additionally, saw this while exploring the same for user **ben**.
Screenshot: Character, possibly an emoji, not being rendered properly.
![image](https://user-images.githubusercontent.com/72859534/145730345-7d0af5e1-f552-4551-89da-0635f0c6a946.png)

Using Chrome on Windows.

**Comment by DumbGameMaker** [comment]
p sure this isn't a bug, and what you are doing is just manually doing what the explore page presumably would do.

**Comment by benawad** [comment]
profiles are intended to be public, idk if I can do anything about the emoji not rendering
