### ISSUE TITLE
Impossible State

### ISSUE THREAD

**Issue by Leggys** [voidpet/bugs#268]
**Screen during exploration went to a blank screen with text.

**

**To Reproduce**

Go to 'explore’2. Go left of the voidpet with coffee 3. Go up

**Expected behavior**
Exploring/battle area
**Video or Screenshots**
![Screenshot 2022-04-06 07 26 55](https://user-images.githubusercontent.com/103076161/161854563-2fa6349b-21c9-4d85-bf8e-b438282a48ae.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Chromebook

**Additional context**
[](url)

**Comment by squidee100** [comment]
Duplicate of #187
Check other issues before making your own.
