### ISSUE TITLE
Landing Page content being overlapped

### ISSUE THREAD

**Issue by abhinavgeethan** [voidpet/bugs#27]
Screenshot: Last section of landing page.
![image](https://user-images.githubusercontent.com/72859534/145730582-e45af762-5acc-4a29-9b89-10be6a4c1349.png)

Using Chrome on Windows.

**Comment by DumbGameMaker** [comment]
something to do with screen height or aspect ratio?

**Comment by james-work-account** [comment]
Putting a max-width of up to something like 1000px (62.5rem) on the `.landing-section-info` element seems to fix this up to a certain point. You'd need to align it centrally too - see image below.

![voidpet](https://user-images.githubusercontent.com/31282758/145733645-366e2fd5-da5b-487b-9b38-1537f00e3e70.gif)

Although at larger screen sizes this would still break. The more long-term solution would be to make different stalagmite and stalactite graphics for larger screens which are more shallow (don't take up as much vertical space).

**Comment by benawad** [comment]
done
