### ISSUE TITLE
White screen of death

### ISSUE THREAD

**Issue by Neonmoonlight** [voidpet/bugs#274]
**Describe the bug**
A white screen interfering with battle mechanics
 
**To Reproduce**
1. Go into a battle and fight 
2. "Application error"
3. Refresh the page enters the next part of the battle

**Expected behavior**
Next part of the battle
No white screen of death

**Video or Screenshots**
<img width="1516" alt="Screen Shot 2022-04-05 at 3 56 25 PM" src="https://user-images.githubusercontent.com/103079233/161864491-28eb073a-5bf0-404c-816a-ee7654102930.png">

**Desktop (please complete the following information):**
 - Browser chrome
 - Version [e.g. 22] Newest

**Additional context**

**Comment by benawad** [comment]
What's your voidpet username
