### ISSUE TITLE
Can't level up

### ISSUE THREAD

**Issue by supercool21** [voidpet/bugs#276]
**Describe the bug**
It says I have enough exp to level up, but when i reach max it just stays there or even goes down and I stay at level 2.

**To Reproduce**
1. Go to battle
2. Finish battle 
3. Collect exp and reach it to its max
4. You don't level up

**Expected behavior**
I expected to level up to level 3

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - Microsoft ( windows ten )
 - Chrome
 - 10

**Comment by benawad** [comment]
Can you record a video of this
