### ISSUE TITLE
Tiktok usernames not allowing the _ symbol

### ISSUE THREAD

**Issue by QuiGonFlynn** [voidpet/bugs#28]
Hey, 

The validation on the Tiktok username field is preventing me from adding my Tiktok to my profile. It's not allowing the _ symbol. 
Tiktok usernames can contain these, as mine does. :)
![Screenshot_20211213-013515](https://user-images.githubusercontent.com/96031390/145739658-9f543fc8-0d7f-4f56-8e5c-aa004b6df6d7.png)

Thanks,

**Comment by benawad** [comment]
done
