### ISSUE TITLE
Impossible State

### ISSUE THREAD

**Issue by MinecraftEgg** [voidpet/bugs#280]
Apparentley, I've reqched an impossible state.

I'm not even sure how it happened. I just tried to log on to my account and I got the error.

Smartphone
 - Device: Samsung S22
 - OS: Android 12 One U.I. 4.1
 - Browser: Samsung Internet
 - Version: 16.2.1.56
![Screenshot_20220405-175725_Samsung Internet](https://user-images.githubusercontent.com/103085972/161881611-aa7d0c7c-7137-4688-be39-8951398c2800.jpg)

**Comment by BlairShepherd** [comment]
Same
