### ISSUE TITLE
Occasional extra period in "sussing out..." description

### ISSUE THREAD

**Issue by LunarMooon** [voidpet/bugs#282]
**Describe the bug**
There's an extra period after “[voidpet name] sized up the Wild Lonely and finds that it likes to [...]” 

The other variations below only have one period. 
“[voidpet name] sized up the Wild Lonely and finds that it appears to be [...]” 
“[voidpet name] sized up the Wild Lonely and finds that it has a faint [...] 

**To Reproduce**
1. Click "Suss out" in the catching menu
2. See error

**Expected behavior**
One period

**Video or Screenshots**
![image](https://user-images.githubusercontent.com/101020534/161883591-500eb79a-eae0-4b5c-81ac-b372db753c27.png)
(it's the same for all variations that follow the "likes to [...]" template)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Laptop
 - OS: [e.g. iOS8.1] Windows
 - Browser [e.g. stock browser, safari] Chrome
 - Version [e.g. 22] Windows 10

**Comment by benawad** [comment]
thanks
