### ISSUE TITLE
Can't catch pets? 

### ISSUE THREAD

**Issue by Jorkii50** [voidpet/bugs#286]
When I opened a quest it told me to catch 1 voidpet. I cought 1 but it still didn't say I Finnished so I used the rest of my containers.  After that it still says I didn't catch any pet, and when I open my inventory it was all gone. I remember catching them and the screen telling me to name them appeared, so I know I got them but it still says I don't have any. Am I missing something? I'm out of containers and don't know how to get more because the quests won't work.

**Comment by benawad** [comment]
You forget to accept the quest, you can buy more containers from the vendor somewhere in the institute
