### ISSUE TITLE
Switch to twemoji or something similar

### ISSUE THREAD

**Issue by benawad** [voidpet/bugs#29]

**Comment by amitojsingh366** [comment]
personal opinion but twemojis seem a little bland, I prefer the apple emojis more. found one potential api that could let you use them, [emojipedia-api](https://emojipedia.org/emojipedia-api/) but it looks like they don't allow access to their API anymore

**Comment by Samuel-Martineau** [comment]
Have you considered [OpenMoji](https://openmoji.org/)?

**Comment by amitojsingh366** [comment]
what did you switch to?

**Comment by jpsxlr8** [comment]
wtf is going on??
