### ISSUE TITLE
Weird colour 

### ISSUE THREAD

**Issue by Quakedy** [voidpet/bugs#30]
Hello my username on void pets is Quakedy and when I chose my starter envy named nemis it was grey instead of black someone checked my account after I asked about it in questions and said that it was black isnt a big issue but here is a photo thank you
![Screenshot_20211213-001423_Samsung Internet](https://user-images.githubusercontent.com/96046224/145776819-af426a92-e633-4181-9751-4079e6e2ccaa.jpg)

**Comment by TheOtterlord** [comment]
Are you using any sort of extension that adds dark mode to websites?

**Comment by DumbGameMaker** [comment]
> Are you using any sort of extension that adds dark mode to websites?

i think some css implementations have an option to invert colors

**Comment by benawad** [comment]
we will be adding an official dark mode later

**Comment by Quakedy** [comment]
Thank you for that I dont have any of that turned on to my knowlage but it's probably on without me knowing
