### ISSUE TITLE
Failed quest completion

### ISSUE THREAD

**Issue by Eawol** [voidpet/bugs#302]
**Describe the bug** after obtaining the first aura container I went to ghost road and captured 3 void pets, two lonely and one angry after returning my quest was not acknowledged as complete and I was out of aura containers
**Expected behavior**
I expected my quest to be ended and to get the two other aura sphere types 

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - IPhone 11
 - Ios 15.4.1
 - Safari 
 - 1.2

**Additional context**

**Comment by benawad** [comment]
You forget to accept the quest, you can buy more containers from the vendor somewhere in the institute
