### ISSUE TITLE
Unable to complete invidere’s first quest

### ISSUE THREAD

**Issue by villosi** [voidpet/bugs#304]
**Describe the bug**
I’ve caught about 5 voidpets but i’m still unable to complete the first quest

**To Reproduce**
Steps to reproduce the behavior: Not sure how to reproduce it but it might have to do with my first catch being a vivid? Honestly no clue

**Expected behavior**
I expected to be able to complete the first quest once i caught a voidpet

**Video or Screenshots**
![5A43A1C3-D6AC-4A9E-955F-D4DCE07F944D](https://user-images.githubusercontent.com/103139846/162038027-5067fdd0-3acb-4565-93a7-d4b926b3d886.png)
![5DFC36AE-B17F-4336-BD83-B9B7B8301C7E](https://user-images.githubusercontent.com/103139846/162038041-601514dc-a532-4d8b-83d5-336d4d7641ed.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 15.1.1
 - Browser: Safari

**Comment by Jorkii50** [comment]
That happened to me, all I did was end up waiting a day and then catch one from ghost road north. Try that and if it doesn't work then idk

**Comment by benawad** [comment]
Try scrolling in the modal and clicking accept, I'll be fixing the UI soon to make it more intuitive
