### ISSUE TITLE
Entire game lags the longer you have it open

### ISSUE THREAD

**Issue by soapysaturn** [voidpet/bugs#307]
If you are playing the game for a long time, everything becomes very laggy. Animations are laggy, pressing buttons are delayed, etc.
This happens both on mobile (android) and pc (windows). The only way to fix it is to refresh, which makes it run very fast again.
I assume this occurs because something to do with switching rooms or voidpets respawning; some sort of process is running in the background that was supposed to be stopped when leaving or taking out a voidpet possibly?

**Comment by soapysaturn** [comment]
I got two videos of this, you can tell the animations and stuff go from being choppy to being fast when I refresh. On top of this, while not in the video, everything else like pressing buttons and new pages loading takes forever, but it goes super fast after you refresh.
For someone with a slow computer, it may be unnoticeable, but it's very clear especially when pressing buttons. 

(I apologize for the music in the background, I was listening to Spotify and I guess the recorder picked that up lol)

https://user-images.githubusercontent.com/103141680/162056417-11d9de67-86fd-48e9-9d3f-f495a7fd6691.mp4


https://user-images.githubusercontent.com/103141680/162056586-f40335d2-f8db-4442-9f52-6a4ceb039674.mp4

.

**Comment by benawad** [comment]
Next time this happens, can you hit the triple dots in chrome, more tools, task manager, then tell me the CPU of the Voidpet tab. I'm trying to narrow down if this is a CPU or memory problem 
<img width="684" alt="Screen Shot 2022-04-06 at 3 16 21 PM" src="https://user-images.githubusercontent.com/7872329/162063315-25512cab-9d32-4c42-ad4c-897695b05004.png">

**Comment by soapysaturn** [comment]
If I'm doing nothing, it rests at 150. If I press any button it goes up to about 170, and if there's a battle animation going on it gets over 200.

When I refresh it ranges between 10 and 40 depending on what's going on on the screen. (sometimes up to 55 during battle animations.)

**Comment by benawad** [comment]
pushed an update that should help with this, will reopen if continues to happen
