### ISSUE TITLE
Strange location

### ISSUE THREAD

**Issue by Discrowd** [voidpet/bugs#308]
**Describe the bug**
Catched 2 Wild voidlings, moved a bit around trying to find out how to play with them, then got back in Explore. Every direction seemed random, and some places where not accessible anymore. Finally found the strange place telling me to report the but

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem. (Screenshot below)

**Desktop (please complete the following information):**
 Chrome on Android

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy s32

![Screenshot_20220406-205601_Chrome](https://user-images.githubusercontent.com/103143443/162048811-43e3fe16-056c-4081-8b45-8817fd01ed5b.jpg)

**Comment by benawad** [comment]
Try opening voidpet in a new tab.
