### ISSUE TITLE
Easily Able to be Hacked

### ISSUE THREAD

**Issue by Gh0st3dd** [voidpet/bugs#31]
Hello I was playing around with the website and found out that just by inputing a different username on the website it is possible to hack any account as long as trhe username exists. It might not be a bug but I feel like its still important to patch this up.

https://user-images.githubusercontent.com/96066419/145832380-b96c57ae-e2a1-4a78-9107-2a0fee435fe5.MOV

**Comment by DumbGameMaker** [comment]
not a bug. you can't do anything with other people's accounts, you can just view their pets

**Comment by benawad** [comment]
profiles are intended to be public

**Comment by OkiStuff** [comment]
W
