### ISSUE TITLE
Bug with Celestial Evolve

### ISSUE THREAD

**Issue by PixlBab** [voidpet/bugs#314]
Not a huge gamebreaking issue, just a bug with how it looks.

My orange lonely went to evolve, but when showing me the screen it only showed his eyes and leftovers from my Envys evolution? It was pretty goofy 

hes fine after that, like i said, minor minor issue,

![Screenshot_20220406-172936_Chrome](https://user-images.githubusercontent.com/46435074/162075073-60b137b2-0298-417d-8986-0ec4a656c055.jpg)

![Screenshot_20220406-172945_Chrome](https://user-images.githubusercontent.com/46435074/162075083-77689d31-d458-481c-896d-e2884a25558f.jpg)

im on samsung mobile chrome

**Comment by benawad** [comment]
closing in favor of #257
