### ISSUE TITLE
All voidpets are white 

### ISSUE THREAD

**Issue by Mupester** [voidpet/bugs#317]
When I first played I thought it was normal for all the voidpets to be completely white but as I continued I realised that it wasn't supposed to look like this.
This is has been an issue from the very beginning for me.
I haven't seen anyone else with this issue.

![image_2022-04-06_231422](https://user-images.githubusercontent.com/103150710/162081216-7b4acd74-32ec-41b9-a218-589fecdca119.png)

It doesn't impact my gameplay too much apart from the fact that I can barely see them when on the roads.
The visuals of them game are impacted by the bug as the voidpets don't have visible eyes.
However this bug doesn't impact the variants from what I am aware as they appear to have some colour, however they do look different to other peoples.

![image_2022-04-06_231523](https://user-images.githubusercontent.com/103150710/162081346-103b883a-b172-4e66-b455-43d6f15a0319.png)

For reference, I chose anger as my starter so I wouldn't know if this bug would affect the other starters. The bug continued after my starter evolved as I thought that might've been the issue.

This issue can also be found on the information page as non of the voidpets appear black. 

![image_2022-04-06_231630](https://user-images.githubusercontent.com/103150710/162081485-f3218d5f-8cac-4960-8f58-26210017982c.png)

**Comment by benawad** [comment]
You have a dark mode extension or something similar on
