### ISSUE TITLE
Issue with white and blue void pets

### ISSUE THREAD

**Issue by felinepeachy** [voidpet/bugs#318]
In battle with other void pets, my white and blue void pets will appear glitched? 
Fundy and Bluey appear black and their eyes are glitched, otherwise they function totally normal. Only in battle will they appear this way.
![buginvoidpet](https://user-images.githubusercontent.com/103152701/162086874-ce249d3f-f0d5-400f-b94e-111d4196f9d5.PNG)
![buginvoidpet2](https://user-images.githubusercontent.com/103152701/162086876-5375e882-6995-44d1-9060-da651c33db5e.PNG)
![voidpet1](https://user-images.githubusercontent.com/103152701/162086907-7ad1d571-9a12-4090-9c5a-940df999c139.PNG)
![voidpet2](https://user-images.githubusercontent.com/103152701/162086909-272ef0ad-1b3d-4729-ab2a-75643acc6cf6.PNG)
![voidpet3](https://user-images.githubusercontent.com/103152701/162086910-f9a2d3ad-ad1f-4ca7-936a-13cd6c40487d.PNG)

**Comment by benawad** [comment]
should be fixed now
