### ISSUE TITLE
A space that isn’t covered by shaded overlay on shop

### ISSUE THREAD

**Issue by SeventyFox92475** [voidpet/bugs#32]
When on the ‘Reward your Voidpet account’ screen in the shop, there is an empty space that the shaded overlay doesn’t cover (mobile)
![22B112B7-308C-43DD-9DFD-D738BDC303FE](https://user-images.githubusercontent.com/45300419/145835043-494a3380-2f83-4a51-b0e7-52e1c164dc58.jpeg)

**Comment by GleamGar** [comment]
I don't think this is a bug, it might just be your device.

**Comment by Funnyman420** [comment]
> I don't think this is a bug, it might just be your device.

The design and website are supposed to be responsive. If that's happening on his device then it's not his device's fault. It is a bug but a very minor one.

**Comment by 911mateo911** [comment]
The new safari is terrible with this, basically when you scroll, and the bottom navigation dissappears, for some reason, sometimes, it doesnt update the screen to be 100vh, it seems dumb, and its not a problem with the page

**Comment by benawad** [comment]
keeping this bug
