### ISSUE TITLE
12 voidpets spawn on ghost road causing lag

### ISSUE THREAD

**Issue by tastryan** [voidpet/bugs#320]
**Bug Description:**
Sporadically on ghost road (the middle segment, not north or south), 12 voidpets will spawn rather than just 3. this causes everything to lag and i have to fight the majority of them for the lag to stop, but due to said lag, it takes a long time. this has happened about 5 times now, its very inconsistent on if it does or does not occur.

I don't know how to reproduce it, seeing as its so irregular, but it has happened on two separate devices (both apple laptops using chrome)

<img width="1389" alt="Screen Shot 2022-04-06 at 8 14 33 PM" src="https://user-images.githubusercontent.com/103155039/162095805-23382a71-6e11-4f70-a7a6-8a87675bd01e.png">
.

**Comment by Roosunix** [comment]
Hi there!
I just experienced this bug myself, and believe it may happen when defeating all the voidpets in Ghost Road North, Have you also been doing that?

**Comment by tastryan** [comment]
Oh yeah! That's probably the cause then. I didn't realize because it's so irregular on if it happens or not, but that's probably what's causing it.

**Comment by benawad** [comment]
feature
