### ISSUE TITLE
12 Voidpets spawn on Ghost Road

### ISSUE THREAD

**Issue by Roosunix** [voidpet/bugs#327]
**Describe the bug**
I was leveling up on ghost road north, as I clicked down to refresh the voidpets there I saw 12 lonely lvl2 voidpets, they're all moving and able to interact with.

**To Reproduce**
1. Go to 'Ghost Road North'
2. Click on 'Fight and fight and defeat all voidpets in the area)
3. Click on 'Down Arrow'
5. See error

**Expected behavior**
I expected to see three voidpets but seeing 4x as many isn't bad I guess lol

**Video or Screenshots**
(https://user-images.githubusercontent.com/103165184/162120487-507640af-31e2-4ab4-a824-1a671ca4d38d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version (i have no idea how to check but this happened 07/04/22 at about 5:30 AM (uk time) and is currently the latest version

**Additional context**
I'm considering this bug a voidpets gathering/dance party and I love that idea

**Comment by benawad** [comment]
feature
