### ISSUE TITLE
Voidpet bug 

### ISSUE THREAD

**Issue by TheTrueLE6END** [voidpet/bugs#328]
Idk what happened I just opened my voidpet and everything was basically gone and some of the starter voids were like messed up real bad like one was huge for no reason

![6C887EFA-F099-412C-8FDD-BE0C3388FE87](https://user-images.githubusercontent.com/103165657/162122678-eeb4366d-9b2d-4e73-b723-7f8c03e11686.png)

**Comment by benawad** [comment]
Try opening voidpet in a new tab.
