### ISSUE TITLE
Potential security issue - the mysterious _N_E folder

### ISSUE THREAD

**Issue by james-work-account** [voidpet/bugs#33]
Source code for the frontend of the website is publicly viewable (i.e. the `*.tsx` files), since there's a folder called `_N_E` in the Sources tab of Dev Tools. See gif below for what I mean.

![Right click -> Inspect Element -> Sources tab -> _N_E folder -> . folder -> profit](https://user-images.githubusercontent.com/31282758/145849214-3eba9e5f-8636-4378-973b-868ebe682cfc.gif)

I'm not sure what the fix for this is (or if it's even a concern) but thought it was worth raising if it hadn't been already. Things like node_modules, the source code, non-environment-variable Sentry config, etc are all public right now.

**Comment by benawad** [comment]
I turned off source maps
