### ISSUE TITLE
issues to get my account fixed 

### ISSUE THREAD

**Issue by meridagll** [voidpet/bugs#330]
**Describe the bug**
Sometimes voidpet bugs and then a new page shows up and told me to go on this website (screenshot below). It happens really frequently 

**Expected behavior**
What can be done to fix this? 

**Video or Screenshots**
![277596944_686027622548755_4537489407884112901_n](https://user-images.githubusercontent.com/103174856/162146577-59604119-b524-4ce2-ae22-bc0da35e6564.png)

**Desktop (please complete the following information):**
 only on safari 

**Smartphone (please complete the following information):**
 - Iphone 7 
 - Browser Safari

**Comment by benawad** [comment]
Try opening voidpet in a new tab.
