### ISSUE TITLE
Impossible state

### ISSUE THREAD

**Issue by LoukaStar** [voidpet/bugs#332]
So I was just going to play the game. I go into the game, but then I see that I just have one voidpet (my starter, back to envy one). I decide to press explore, and then a screen pops up, saying something like ”if you see this, congratulations. You’ve reached a impossible state. Report this as a bug” 
I refreshed the page and everything went back to normal. I’ve seen other bug reports about this so I don’t think it’s a big problem. Just wondering what it means

**To Reproduce**

**Expected behavior**

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by benawad** [comment]
Try opening voidpet in a new tab.
