### ISSUE TITLE
Impossible state

### ISSUE THREAD

**Issue by tridragons** [voidpet/bugs#334]
I went to just fight some void monsters and ended up walking into a place that didn't exist. :(

1. Go to Expore.
2. Go north until you hit the fields.
3. Go to the right.

I just wanted to explore the fields but it seems I just ended up in an error zone with no way back.

![SmartSelect_20220407-135943_Chrome](https://user-images.githubusercontent.com/103213134/162268226-70295a0e-07ee-4581-9d7f-ef8004f7d5e4.jpg)

 - Device: Galaxy S21 Ultra
 - OS: Android 12
 - Browser: Chrome
 - Version:  100.0.4896.79 

My user name is Dragons, so I can be sent out of the error zone and continue to play.

**Comment by benawad** [comment]
Try opening voidpet in a new tab.
