### ISSUE TITLE
it brought me to this when i tried to explore

### ISSUE THREAD

**Issue by CandyCat111** [voidpet/bugs#336]
Helppp it brought me to this 
Dunno what to do
![Uploading 2086EE88-59FD-4733-92BA-744953FE120A.png…]()
Ok so idk but the photo isnt showing up on my side but basically what it says is

If you see this screen, congratulations you've reached an impossible state. Take a screenshot and make an issue on https://github.com/voidpet/bugs/issues to get your account fixed.

{
  "id": 23,
  "layer": 1,
  "zone": 4
}

Help 😀

**Comment by benawad** [comment]
Try opening voidpet in a new browser

**Comment by CandyCat111** [comment]
> Try opening voidpet in a new browser

Thank u sm that worked
