### ISSUE TITLE
Reached an impossible state

### ISSUE THREAD

**Issue by GalaxyGlitch6** [voidpet/bugs#337]
**Describe the bug**

**To Reproduce**
1. Go into the game
2. Explore a bit
4. Reach an impossible state

**Expected behavior**
Explore and not be tossed into the folds of reality

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.
![0240078B-EC28-493F-812A-B1D1C516476B](https://user-images.githubusercontent.com/103217193/162283046-667a875a-f7c1-4504-9988-4518e57e0b5c.png)

**Smartphone (please complete the following information):**
 - Device: [iPhone XS Max]
 - OS: [15.4.1]
 - Browser [safari]
 - Version []

**Additional context**

**Comment by benawad** [comment]
Try opening voidpet in a new tab.
