### ISSUE TITLE
Possible Sine hair bug

### ISSUE THREAD

**Issue by FlamingFledge** [voidpet/bugs#338]
**Describe the bug**
Sine hair doesn’t show up in avatar customization, only in inventory, is this intentional?

**To Reproduce**
1. Go to String’s shop
2. Buy the “Sine hair”
3. Check avatar and it’s not there

**Expected behavior**
To be able to wear Sine’s hair

**Video or Screenshots**
![F619DF3B-C6A0-4E44-BDE2-564E8CAADBE9](https://user-images.githubusercontent.com/103221297/162323159-53431ff1-90f6-4d6c-b691-1206d6705c76.png)
![DF8306DA-0F71-4976-948F-57F4918652DE](https://user-images.githubusercontent.com/103221297/162323165-9d5486b3-4371-4748-9811-6cc75e21e68a.png)

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: 15.3.1
 - Browser: Safari
 - Version: if game then most recent, if ipad version then same as OS

**Additional context**
none

**Comment by benawad** [comment]
What's your voidpet username?

**Comment by FlamingFledge** [comment]
It appears to work now, thanks if you had fixed it, if it just fixed itself, sorry for wasting your time- 👍
