### ISSUE TITLE
Impossible State 

### ISSUE THREAD

**Issue by KittyClaw10** [voidpet/bugs#340]
**Describe the bug**
Impossible State

**To Reproduce**
1. Fight a wild lonely
2. Exit tab, with fight unfinished
3. Come back days later, beat lonely

I figured once I won the fight and clicked of the end screen, I'd get back to the area I was in

![Screenshot_20220407-184239](https://user-images.githubusercontent.com/54918911/162332454-aa1a8af4-e0f4-421b-969a-2bea3a42b301.png)

**Smartphone (please complete the following information):**
 - Device: Moto g play (2021)
 - OS: Android
 - Browser: Google
 - Version: 11

My username is VoidsRain. I'd appreciate being able to get back to my Voidpet.

**Comment by benawad** [comment]
Try opening voidpet in a new tab.
