### ISSUE TITLE
Impossible state

### ISSUE THREAD

**Issue by lylutat** [voidpet/bugs#341]
**Describe the bug**
Impossible state

**To Reproduce**
1 - Click on explore
2 - See error

**Video or Screenshots**

https://user-images.githubusercontent.com/103225309/162336061-5792861c-da5a-44cb-aead-351fdae1523a.MOV

**Smartphone (please complete the following information):**
 - Device: IPhone 12 Mini
 - OS: iOS15.2
 - Browser: Safari
 - Version: 15.2

Thank you so much for the help!

**Comment by benawad** [comment]
Try opening voidpet in a new tab.
