### ISSUE TITLE
Impossible state

### ISSUE THREAD

**Issue by tiredBotanist** [voidpet/bugs#343]
**Describe the bug**
Said i reached an impossible state.

**To Reproduce**
I can't get it to happen again, i was just moving around the explore area and all of the sudden the screen popped up
![Screenshot_20220407-233557](https://user-images.githubusercontent.com/103234704/162358376-19519f4f-a532-48aa-ac90-614db1ca0279.png)
.

**Smartphone (please complete the following information):**
 - Device: pixel 6
 - OS: android 12
 - Browser chrome

**Comment by benawad** [comment]
Try opening voidpet in a new tab.
