### ISSUE TITLE
Missing pets

### ISSUE THREAD

**Issue by tiredBotanist** [voidpet/bugs#344]
I caught a bunch of wild lonelys and only 2 of them are showing up? I just caught a bright pink one and i think it had purple eyes, pretty sure it was lvl 4, i named it Strawbby, and now they're nowhere to be found :(( i got really excited too :((  my username is tiredBotanist

**Comment by tiredBotanist** [comment]
Just happened again with a blue one

**Comment by idkfisk** [comment]
i also have This problem

**Comment by benawad** [comment]
see #223
