### ISSUE TITLE
I cant wear the hair i crafted

### ISSUE THREAD

**Issue by hepandeerus** [voidpet/bugs#346]
I can't equip the 'hyphen' hair. (i don't know if the same is with the other hairs

**To Reproduce**
1. Craft the Hair
2. Go to the Avatar Editor
3. Open the Hair Tab
4. The Crafted hair is not there

**Expected behavior**
You should be able to equip the hair

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version 100.0.4896.75 (Official Build) (64-bit)

**Additional context**
The Hair does show up in my inventory but I cant do anything with it

**Comment by benawad** [comment]
try refreshing, it should show up
