### ISSUE TITLE
ive reached an impossible page

### ISSUE THREAD

**Issue by ThornQueen** [voidpet/bugs#349]
**Describe the bug**
i went to battle with my voidpet and the arrows took me to the wrong place ,when I clicked to go right I got this page,what should I do?

![Screenshot (2)](https://user-images.githubusercontent.com/103274487/162483131-9904090b-ab64-4719-bbce-8e6fc28b1e1b.png)

**Comment by benawad** [comment]
Try opening voidpet in a new tab.
