### ISSUE TITLE
Impossible State

### ISSUE THREAD

**Issue by LastUnknown** [voidpet/bugs#360]
**Describe the bug**
While exploring, I got to this page: "If you see this screen, congratulations you've reached an impossible state. Take a screenshot and make an issue on https://github.com/voidpet/bugs/issues to get your account fixed."

**Expected behavior**
I was exploring and tried to move through the field, expecting a new room or continuation of the field.

**Video or Screenshots**
![Screenshot_20220409-171820_Chrome](https://user-images.githubusercontent.com/103338665/162593491-b5702027-f5b9-4089-8be5-def3f3901f73.jpg)

**Smartphone**
 - Device: Samsung Galaxy S22 Ultra
 - Browser: Chrome

**Comment by benawad** [comment]
try opening voidpet in a new tab
