### ISSUE TITLE
Scarf is not moving with my voidpet's (lonely 2) neck. It just stays in place

### ISSUE THREAD

**Issue by Quetzal05** [voidpet/bugs#361]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by benawad** [comment]
can you record a video of it

**Comment by benawad** [comment]
should be fixed now
