### ISSUE TITLE
Error container screen

### ISSUE THREAD

**Issue by Altairaeon** [voidpet/bugs#362]
The home screen is just fine. I went to the explore and then tried to catch a Voidpet, but got an error popup. I tried reseting the page, but now whenever I go to explore, that error popup appears.

![607DBDBB-5B91-46C4-896D-4965BC2D16AC](https://user-images.githubusercontent.com/103342080/162596732-cb981658-86d9-4316-bd68-294cc766c5c7.png)

**Comment by benawad** [comment]
try refreshing should be fixed now
