### ISSUE TITLE
Pets wearing scarves shrink and disappear during battles

### ISSUE THREAD

**Issue by RebekahAimee** [voidpet/bugs#363]
I'm using Firefox 98.3.0 on Android 11.

When I put the red scarf on my lead pet, pick a fight, select moves and then press the attack button, my pet shrinks quickly and disappears while the opponent pet grows slightly. Animation sizes are also affected.

The bug doesn't happen if the scarf is on a pet not currently battling, but does show up if you swap the scarf-wearing pet into battle (size change happens as soon as the turn starts, with the other pet attacking).

I've tried this on my Anxious and several different Lonelies, it's consistent. The game doesn't crash but it does seem to slow down a bit.

**Comment by benawad** [comment]
Could you record a video of this happening

**Comment by LJneko** [comment]
https://photos.app.goo.gl/XGRYE6pgeHUcsx7r5 Having this bug too, got a (crappy....) video of it! ^^

**Comment by benawad** [comment]
should be fixed now
