### ISSUE TITLE
Lonely 2 wearing a scarf duplicates scarf during battles

### ISSUE THREAD

**Issue by TangentOfTheCat** [voidpet/bugs#368]
**Describe the bug**
When I go into battles with my Lonely 2, the scarf it’s wearing replicates itself multiple times. The replicas all move independently.

**To Reproduce**
1. Enter any battle.
2. Switch to a Lonely 2 (mine is jaded) wearing a scarf (mine is an ephemeral scarf).
3. The scarf begins to replicate itself.

**Expected behavior**
The scarf should not replicate itself constantly.

**Video or Screenshots**

https://share.icloud.com/photos/0f1KWn1vAHj7oHQhnUfiAxr2g

**Smartphone:**
 - Device: iPhone6S
 - OS: iOS15.3.1 (I think?)
 - Browser: safari
 - Version 15.3.1

**Additional context**
I haven’t tried it with my other pets, but the scarf seems to work fine on my Anxious and the leaf works fine on the other Lonely I have.

**Comment by konekokuro** [comment]
I'm unable to take videos, but I have this issue as well. My lonely is ephemeral with a phantom scarf. Photo is attached! They move in opposite directions; one goes with the lonely and the other goes in the opposite direction.
![scarf glitch](https://user-images.githubusercontent.com/103346618/162600676-c1f49b0f-1d8e-42e0-a02a-d6a729230c54.png)

**Comment by submergedinmilk** [comment]
also experiencing this, does it on all the scarves i have (scarlet, maroon, ephemeral) and appears to specifically duplicate each time a new animation plays.
[here's a video i took.](https://media.discordapp.net/attachments/557729205597765656/962560351545724998/Screen_Recording_20220409-234040_Chrome.mp4)

**Comment by benawad** [comment]
should be fixed now
