### ISSUE TITLE
Dancing glitch

### ISSUE THREAD

**Issue by anarolol** [voidpet/bugs#372]
So there’s a bug with the dancing feature. Whenever I danced with my voidpet another bigger voidpet would appear in the screen and do the same actions as the voidpet below, but pulsing.

Steps to reproduce the behavior
1. go to voidpet.com, your account
2. Press the button “play with ___” 
3. Press the button “dance”
4. Press the button “vibe with ___”

What I expected was for it to just dance and not make another voidpet on top appear.

Video of the bug:

https://user-images.githubusercontent.com/103346098/162600402-2bd551eb-251e-4881-b79e-cb122198c473.mov

Smartphone
 - IPad mini 5
 - OS: iPadOS 15.1
 - Browser: Safari

**Comment by benawad** [comment]
should be fixed now
