### ISSUE TITLE
quest bug

### ISSUE THREAD

**Issue by tecalsky** [voidpet/bugs#374]
**Describe the bug**
I got the quest to catch a voidpet. I caught 3 using all 5 of my containers, and when i went to claim my rewards, it brought me to the "quest unfinished" screen thingy. and when i look at my quest log it says i still have to catch a voidpet, even though i've already captured 3.

**To Reproduce**
1. Get quest to catch voidpets
2. use all 5 of your containers
3. go to claim your prize
4. find out you still haven't completed the quest?

**Expected behavior**
I don't know if it's only me or something, but above is what I did and it happened. I also caught more than 1 voidpet if that's the issue.

**Comment by smit-sms** [comment]
I am having the same issue, tried to reset all the pets and re-catch 6 of them. But still, the quest was not completed. Hope @benawad patches this soon so we can get back to action! :)

**Comment by benawad** [comment]
Can you screenshot what your quest log looks like?
