### ISSUE TITLE
voidpet shrinking/disappearing in battle

### ISSUE THREAD

**Issue by wormapostle** [voidpet/bugs#375]
**Describe the bug**
So, I have this voidpet that is a pale blue with pale red eyes, and I put a scarf on them because I got excited about the new update, and went to farm items an void material. When I start a battle, the voidpet's there just fine, but as soon as he does his first attack he shrinks and disappears. After that he's gone till the end of the battle, then the issue repeats in any other fights. This is my first attempt at filling out a report- I hope I did it right!
**To Reproduce**
1. Go into battle
2. Click on my moves, n start the fight
3. voidpet shrinks
4. battle keeps going with invisible voidpet, or just so tiny I can't see him?

**Expected behavior**
When I normally put a voidpet into a fight, I can see it the whole time, so maybe this is because of the scarves? I am not sure.

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/103346977/162600943-1d3eb879-0c9c-4f3b-8239-3a64ab4dcb8f.png)
Here he is right at the start, and then in the next image, vanished! 
![image](https://user-images.githubusercontent.com/103346977/162600953-c008b2eb-6c3d-4794-8084-c81458821e02.png)
He shrinks into nothing and disappears- though I guess it's not that bad a bug because I can still play!
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] I'm on a windows laptop
 - Browser: FireFox
 - Version: Not sure but I update regularly

**Additional context**

**Comment by benawad** [comment]
Does this happen with all of your pets or just this one?

**Comment by wormapostle** [comment]
All of them if they have a scarf on!
Though I saw some other people reporting the same issue so I don't know if
it may already have been addressed or not.

**Comment by benawad** [comment]
Should be fixed now if you refresh
