### ISSUE TITLE
Scarf layers clipping when voidpet bounces

### ISSUE THREAD

**Issue by soupy227** [voidpet/bugs#376]
Went to go see my voidpet in home who was wearing the red scarf, only to see the scarf sprite kind of just not being a scarf. It looked like a separate scarf was moving slightly out of sync with the actual one

**To Reproduce**
1. Go to 'Home’
2. Scroll down to '. Third Voidpet, cryptic vivid lonely stage 2 wearing red scarf item
3. See error

**Expected behavior**
The specific scarf to move like the other ephemeral scarf of the void pet I also have in my home party

**Video or Screenshots

https://user-images.githubusercontent.com/103346963/162601064-61b4da06-ea43-40f9-98ee-d0f68be08dd5.MOV

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by soupy227** [comment]
Update: One of my other voidpets was doing it too with the ephemeral scarf. My lonely level 2 with the phantom scarf seems to be just fine 

Uploading IMG_1024.MOV…

**Comment by benawad** [comment]
should be fixed now
