### ISSUE TITLE
Scarf duplication

### ISSUE THREAD

**Issue by Xtremeturtle** [voidpet/bugs#377]
My cataclysmic vivid's scarf is duplicating

**To Reproduce**
Acquire cataclysmic vivid 
Equip with the celestial scarf
Preform an action, it will delay the scarf from the normal animation, and many clones will be created quite fast

**Expected behavior**
I expected the scarf to stay stained to this void of a reality, but it has not, ascending beyon what our feeble minds can understand, and reaching the point where a simple emotion doing a dance may create clones of it.

**Video or Screenshots**
I had an issue with the video, so if you need it, you can message me at Xtremeturtle#4266 on discord

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: 14.8.1
 - Browser safari
 - Version first clothing update (I don't know what version, but it is 30 minutes old)

**Additional context**
I wrote this twice, so sorry if I forgot anything.

**Comment by benawad** [comment]
should be fixed now
