### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by Zephyeran** [voidpet/bugs#378]
**Describe the bug**
After enjoying the game a lot, I attempted to move from phone to PC by logging in, using the only option avaliable, logging in with Discord. 
When attempted, it tried to force me to make a new account, as though no account was linked to my Discord.
I figured this may just be a matter of not having my account linked to my Discord, so I went to try and link them, but found no way to do so.
I signed up before the 'Login with Discord' option was added, and I believe this has left my account unable to login without a linking feature being added.

**To Reproduce**
1. Make an account around Feb 20th of 2022
2. Look up the code to access the game to avoid bothering S/O who got me interested
3. Enter code, make account, play for months
4. Decide today that I wanted to swap devices for the bigger screen on my laptop after seeing how the game looked different on the stream on PC
5. Click Login with Discord, give access, and get stuck on a screen prompting me to make a new account, which tells me my username is obviously taken because I want to log in and not sign up again
6. Get out of that screen finally, with no way to sign into my account on other devices.
7. Ask for help in Questions, assuming I just didnt know where the 'Link Discord' UI button was, get redirected here, as it may be a bug.

**Expected behavior**
I'd expected to click 'Login with Discord' and automatically get into my account, Zephyera, which I've had since about February 20th, where all my voidpets, like my starter Victor are.
I was instead sent to the 'pick a username' part of the process, as though I was signing up to link a new account with my Discord, meaning my current account, Zephyera, is somehow not linked to my Discord apparently, and I therefore cannot sign in.
I won't log out of my account on my phone, so I don't lose my account, but it's scary nonetheless because I was hoping to get a new phone soon, and now am afraid of being unable to get back into my account at that point.

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

**Smartphone/Desktop** 
- Device: Galaxy Note 10+/Acer Spin SP111-33
- OS: Android/Windows (Trying to log in on Windows)
- Browser: Chrome
- Version: 100.0.4896.79/93.0.4577.82 (Laptop needs the update, both use Chrome)

**Additional context**
I'm thankfully still logged in on my phone, didn't want to log out before logging in on my laptop, glad I listened to that intuition, but I think all that may be needed is a way to link some accounts to your Discord account, as there may be other old-ish accounts with a similar issue.
Had it not been an older account that I've gotten attatched to, I would've just started new, but I've over 1k void matter, 20+ pets that are mostly vivids, all quests except the recent outfit quests complete (yes, even the 'catch 20 voidpets' one before it got nerfed), and the half void matter hair, so I'm sad to think that I might lose it all.

**Comment by benawad** [comment]
Create an account where you login with Discord and pick a new username then tell me the username of both accounts (and the name you ultimately want) and I'll merge them together so you can login with discord in the future

**Comment by Zephyeran** [comment]
Got it, made an account by the name of Zephyeran linked to Zephyr Rōsuton#7244 on Discord just now!
I want to keep the username Zephyera, and the pets on that account of course, hah. No n at the end is all ^.^'
Thank you so so much!!! Sorry I had to bother y'all with this!

**Comment by benawad** [comment]
Looks like `Zephyera` has a Discord attached to it. Discord handle is `Zephie~#1171`, is that yours?

**Comment by Zephyeran** [comment]
OH
It's linked to my alt somehow?? That's an old account for when I get overwhelmed by friends but still want to see updates in discord servers for games and such, a
Ack, that's weird, good catch, a, not where it should be linked, hah. Is there a way to swap it to my main then? Should I delete the one I made on my main then, or?
You can slide a message for proof if you need to either, I don't mind, I just don't know how it got linked to that account, haven't logged into that one on my phone's browser in a long time, it should've been the other acct I mentioned, hah.

**Comment by benawad** [comment]
Ok I merged them, try logging in with `Zephyr Rōsuton#7244` discord and it should take you to main account
