### ISSUE TITLE
Void Pet Crystal color change

### ISSUE THREAD

**Issue by Rocksmasher228** [voidpet/bugs#379]
My void pet Tsuki used to have a blue crystal before the update and now they have a scarlet one

![image](https://user-images.githubusercontent.com/103347401/162601491-954b8bb3-cbff-4daf-9b58-e3e80118af7b.png)

![image](https://user-images.githubusercontent.com/103347401/162601499-e133374f-5de3-4a93-903d-2e7407266f00.png)

**Desktop (please complete the following information):**
 - OS: I've got a dell computer with an Intel I5 core if that helps
 - Browser Chrome
 - Version: Most recent version

**Smartphone (please complete the following information):**
 - Device: G7 Power
 - Browser Chrome

**Additional context**
It is changed on both my computer and my phone

**Comment by Liamdapotato** [comment]
Same thing happened to me I used to have wood now I have fire cristal
![7134037F-2679-4242-A017-BAFABE813A24](https://user-images.githubusercontent.com/103352236/162606193-83e60ec4-e892-4e4a-9247-fc9ce2cb7734.jpeg)

**Comment by benawad** [comment]
We started showing secondary element instead of primary
