### ISSUE TITLE
Bug with the Scarves

### ISSUE THREAD

**Issue by Tempast-real** [voidpet/bugs#380]
**Describe the bug**
With most/all of the scarves I've been using (Phantom scarf, daisy wreath, and pink retro scarf) they will glitch and duplicate on screen during attack sequences to create a weird many-scarf effect

**To Reproduce**
1. start a fight with any void pet
2. let them hit you
3. once they do, the scarf will lag behind the pet for a second before starting to glitch and duplicate
4. It will do this till the end of the fight

**Video or Screenshots**
![image](https://user-images.githubusercontent.com/103347944/162601726-40885afb-1492-4f48-a04f-64beb84a6642.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version latest version

**Smartphone (please complete the following information):**

**Additional context**
I love voidpets :) good job so far!

**Comment by benawad** [comment]
should be fixed now
