### ISSUE TITLE
Equipping accessories shrinks the voidpet

### ISSUE THREAD

**Issue by urlocalmadman** [voidpet/bugs#383]
**Describe the bug**
When i equip any accessory on my voidpet, it seems to shrink while in battle/while catching. Refreshing or anything doesn't fix it.

**To Reproduce**
1. Equip an accessory on the voidpet
2. Go to catch or fight a wild with your voidpet
3. Voidpet shows up shrunken

**Expected behavior**
Voidpet looks the same size as it did without the accessory

**Video or Screenshots**
without accessory
![image](https://user-images.githubusercontent.com/77184186/162602973-1f8935de-22d4-46a2-bda5-4b37a873c049.png)

with accessory
![image](https://user-images.githubusercontent.com/77184186/162602985-f6f4ab5d-89fb-420d-bb68-afa6b230cbef.png)

**Desktop (please complete the following information):**
 - Windows 10 64 bit
 - Firefox
 - 99.0 64 bit

**Additional context**
Haven't seen anyone else with the same problem but its persistent with me

**Comment by benawad** [comment]
should be fixed now
