### ISSUE TITLE
Scarf bug when playing with Voidpet

### ISSUE THREAD

**Issue by Liamdapotato** [voidpet/bugs#387]
**The scarfs are messed up when playing with the pet**
Idk if it happens with other objects but it does with scarfs. When I go to play with a pet the scarf is normal but the moment I interact with them the scarf is or double or tripled until I go back. It happens with any games, meditate, cuddle, dance,…
 
**to reproduce**
1. Go to play with pet
2. Click on any game (ex. Meditate)
3. The scarf is tripled 

**Expected behavior**
I guess it should just follow the neck and not teipple xD

Ah i can’t add image when editing I’ll put it in the comments

**Smartphone:**
 - Device: iPhone 8
 - Browser : Safari

**Comment by Liamdapotato** [comment]
The image that I couldn’t add
![32317CA6-540F-4C6B-A98D-E84B0D414932](https://user-images.githubusercontent.com/103352236/162612560-a5a9a75d-e664-41bf-9545-cfc8d042f348.png)
That’s before interacting

![D6EC1C9F-2F28-46B0-863E-F2B36ED3DC0F](https://user-images.githubusercontent.com/103352236/162612568-082c97b8-1d68-453b-8747-7a6bbc90179b.png)
After interacting

![2747BFAB-1A64-4411-BFFE-8CECADA44BE8](https://user-images.githubusercontent.com/103352236/162612574-d7851cb5-c03a-467f-8104-6f7abc012118.png)
And it works with any interactions

fights too but someone already mentioned it

**Comment by benawad** [comment]
should be fixed now
