### ISSUE TITLE
Voidpet looks mini sized

### ISSUE THREAD

**Issue by RachaelGodfrey** [voidpet/bugs#388]
One of my voidpets looks mini sized in battles and on the Home Screen despite actually being 3ft.

![FE459D7C-E23A-4134-B260-62B920D1968F](https://user-images.githubusercontent.com/103364816/162616454-3d80b3db-d0cd-4ac0-a781-8139d24e1011.png)
![523463DB-5FBA-4FBB-BE8F-14656FEF50FB](https://user-images.githubusercontent.com/103364816/162616912-2c750877-c99d-471b-a759-be3e2f75be66.png)
![99F091C7-F834-435C-BD9F-F0B7D3CB2AC6](https://user-images.githubusercontent.com/103364816/162616914-26c7b298-e032-44c8-89a9-bed5954cab28.jpeg)

However, when playing with it and standing next to my avatar, it does appear normal sized.

![BFE18EB7-5AFC-4B47-AA45-183AFEF17675](https://user-images.githubusercontent.com/103364816/162616464-ce548cbb-f9a3-4fb1-a260-14e36b83df46.png)
![80639A09-09D1-404E-8F43-379364B6E7F3](https://user-images.githubusercontent.com/103364816/162616627-47dc9228-50dc-47d4-ba22-cc84a628bed9.png)

iPhone XR - google chrome version 99.0.4844.59

**Comment by benawad** [comment]
You have a tall but skinny voidpet
