### ISSUE TITLE
Orange Butterfly Chain glitches in battle

### ISSUE THREAD

**Issue by freyarsenic** [voidpet/bugs#389]
The orange butterfly chain looks normal on the voidpet at home and everwhere except for the battles. It also makes the game run VERY laggy. I'm playing on pc.

![Opera Instantánea_2022-04-10_150945_voidpet com](https://user-images.githubusercontent.com/102683980/162619882-8e6ed6db-46ac-41b3-8ed9-6d503eebebe3.png)

**Comment by benawad** [comment]
should be fixed now
