### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by Fungist** [voidpet/bugs#390]
Device: iPhone 11 pro max
Browser: Chrome

Opened the voidpets page in my browser, and when clicking on the character (I’m forgetting the name) I received an application error page
![F55DB49C-6BF7-423D-850E-B6047BE39A3E](https://user-images.githubusercontent.com/102311976/162623862-49bd3bdb-c328-4782-83e4-205ff213d422.png)

https://user-images.githubusercontent.com/102311976/162623863-4cb1bae4-87aa-496f-b3db-b87c0d4feb0b.MOV

**Comment by benawad** [comment]
If you open voidpet in a new tab does accepting the quest work?
