### ISSUE TITLE
To many voidpets

### ISSUE THREAD

**Issue by Cece1357** [voidpet/bugs#392]
**Describe the bug**

**To Reproduce**
1. I have no clue I had just been farming for like 20 min

**Expected behavior**
I expected 3 voidpets like normal 

**Video or Screenshots**
 It is not letting me import the photo but if you need it you can message me at Cece#7189
**Ipad (please complete the following information):**
 - OS: iOS 
 - Browser safair

**Additional context**
There were like 20 voidpets on the screen and you could interact with them all

**Comment by benawad** [comment]
that's a feature
