### ISSUE TITLE
The accessories are glitching out on my pet(s)

### ISSUE THREAD

**Issue by Kai-Waznt-here** [voidpet/bugs#396]
https://user-images.githubusercontent.com/103384995/162636917-0cb58d77-0469-468b-9539-524b605d6f32.mp4

![unknown](https://user-images.githubusercontent.com/103384995/162636996-83e73065-5e9c-4c92-ae0c-a1052ad52063.png)

**Comment by benawad** [comment]
if you open voidpet in a new tab (to guarantee you get the latest version of the website) does that still happen?

**Comment by Kai-Waznt-here** [comment]
> if you open voidpet in a new tab (to guarantee you get the latest version of the website) does that still happen?

No, I guess I had it pinned so long it was out of date -.-
Thank you for helping!
