### ISSUE TITLE
Blue Butterfly Chain BUG

### ISSUE THREAD

**Issue by LeneShar** [voidpet/bugs#398]
**Describe the bug**
When the Blue Butterfly chain is on my Voidpet (Envy one) in combat it multiplies infinetly and makes the animations a bit slow and laggy.

**To Reproduce**
1. Equip Blue Butterfly Chain on Envy 1
2. Fight another Voidpet
3. See error

**Expected behavior**
[?]

**Video or Screenshots**
[None]

**Desktop (please complete the following information):**
 - Windows
 - Chrome
 - Windows 10

**Additional context**
[None]

**Comment by benawad** [comment]
if you open voidpet in a new tab (to guarantee you get the latest version of the website) does that still happen?
