### ISSUE TITLE
I received this message while exploring

### ISSUE THREAD

**Issue by dimethyl-cadmium** [voidpet/bugs#399]
![Screenshot_20220410-163645_Chrome](https://user-images.githubusercontent.com/103388804/162641018-67773417-29b6-47b0-b957-5cc757bd591f.jpg)
i had just finished making my character and went up twice and then to the right and recived this message (mobile- samsung galaxy s9+ android 10 on google chrome)

**Comment by benawad** [comment]
Try opening voidpet in a new tab
