### ISSUE TITLE
ben is horny

### ISSUE THREAD

**Issue by overlisted** [voidpet/bugs#4]
## proof
![benhorny](https://user-images.githubusercontent.com/66535446/145721782-f6465a6f-03bd-4441-b5e4-c4eccd42dd06.png)

**Comment by maverick-dev-55** [comment]
Please stop

**Comment by unusualifier** [comment]
yup

**Comment by gold-ly** [comment]
I can confirm this is a real bug

**Comment by IvanCodeslol** [comment]
Bug of top priority

**Comment by amitojsingh366** [comment]
@overlisted you're right

**Comment by maverick-dev-55** [comment]
Also why do you have that picture 👀

**Comment by IvanCodeslol** [comment]
@maverick-dev-55 it was an emoji in the doghouse discord server where he was an admin so from there probably

**Comment by maverick-dev-55** [comment]
> @maverick-dev-55 it was an emoji in the doghouse discord server where he was an admin so from there probably

ahhh

**Comment by overlisted** [comment]
ben probably won't close it @maverick-dev-55

**Comment by FrostenAKAturtle** [comment]
ben is bad, turtle is good

**Comment by maverick-dev-55** [comment]
You bad, Ben good 😭

**Comment by Staninna** [comment]
Love this bug
