### ISSUE TITLE
I received a message while exploring to go here

### ISSUE THREAD

**Issue by pedestrianbitch** [voidpet/bugs#400]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by benawad** [comment]
try opening vodipet in a new tab

**Comment by pedestrianbitch** [comment]
it works now thank you
