### ISSUE TITLE
Exp. frozen

### ISSUE THREAD

**Issue by SilverfirePuppies** [voidpet/bugs#402]
Exp points are not being added after reaching level five, have tried with 3 different pets

**To Reproduce**
1. Have a pet Reach level 5
2. Fight wild voidpet and win
3. The game will say you’ve earned however amount of exp but it does not reflect / add up under any pet

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: 14.7.1

**Comment by benawad** [comment]
The level cap is currently 5, we will raise it soon
