### ISSUE TITLE
Too many lonely little guys

### ISSUE THREAD

**Issue by Human-Shovel** [voidpet/bugs#403]
I completed the lonely quests and was fighting a lonely, I kept leaving and re-entering the site because I was texting a friend. After fighting the lonely I left and re-entered the area to see if any new pets were there (I wanted to catch something other than a lonely) and to my disappointment it was a weirdly large amount of lonelys instead.

I’m using a iPhone

![840BE563-9C7C-4D97-9D60-7D836F30399D](https://user-images.githubusercontent.com/103402584/162666505-a9e6070e-3663-4cdd-850f-3d8ce04f584c.png)

**Comment by You6553** [comment]
We can only catch lonlies so far we will be able to catch others in the future

**Comment by benawad** [comment]
That’s a feature, more species coming soon
