### ISSUE TITLE
Stats voidpets not working

### ISSUE THREAD

**Issue by Poetie** [voidpet/bugs#405]
On my game the leveling of stats has suddenly stopped working. At first this worked completely fine, I managed to level 1 stat of three different pets. But then the day after when I tried to do the same I did the day before it suddenly stopped working, my stats have been stuck on the same number for days now, even though they are boosted and I have been fighting a lot of voidpets.

I would really appreciate if this could be helped or if I could do anything about it. Because I love this game and am now missing out on so much.

 - Device: iPhone 11
 - OS: iOS 14.8.1
 - Browser: Safari

**Comment by benawad** [comment]
There is a limit

**Comment by Poetie** [comment]
Yes I am aware of that but is the limit for example 19?

**Comment by benawad** [comment]
In some pets, yes
