### ISSUE TITLE
Large unmoving Checkers stuck in top left corner

### ISSUE THREAD

**Issue by Roosunix** [voidpet/bugs#407]
(https://user-images.githubusercontent.com/103165184/162857502-e2fbb71b-1350-4a12-8e11-39e0aceaad23.png)
(also unable to go left)

**Comment by Roosunix** [comment]
...I'm reporting a bug so you guys can fix it??

**Comment by benawad** [comment]
It’s caused by having an old game client so this particular bug is somewhat unfixable besides refreshing to get the latest version

**Comment by Roosunix** [comment]
ah alright i understand, hope i didn't come off as rude

**Comment by benawad** [comment]
All good
