### ISSUE TITLE
Occasional lack of rewards after wild lonely battle

### ISSUE THREAD

**Issue by dragonheart42** [voidpet/bugs#408]
Sometimes, after fighting a wild lonely, there will be no void matter or drops.

**To Reproduce**
1. Go to Ghost Road
2. Fight a wild lonely voidpet

**Expected behavior**
I expected to receive some void matter, but instead I keep receiving none.

**Desktop**
 - OS on MacBook
 - Chrome

**Comment by benawad** [comment]
intended behavior
