### ISSUE TITLE
Dancing Bug

### ISSUE THREAD

**Issue by reallybelt** [voidpet/bugs#409]
**Describe the bug**
When you go to play with your voidpet and dance with it, the screen elongates and the sprite duplicates.

**To Reproduce**
1. Go to the homepage with your Avatar and voidpets
2. Scroll down to a select voidpet and press "Play with [NAME]"
4. Press on "Dance"
5. Press "Vibe with [NAME]"
6. See error

**Expected behavior**
Window with sprite doubles in height, the stars float up the screen, the sprite does its dance, but an opaque duplicate appears above it and pulses. It also follows the movements of the solid Voidpet beneath, but the pulsing continues until the dance ends, then the screen goes back to normal.

**Video or Screenshots**
![image](https://user-images.githubusercontent.com/103473168/162867200-8949d24e-d210-41c6-90d2-65c13bbe3116.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Microsoft Edge
 - Version: 21H1

**Additional context**
The Voidpet I use is a level 4 Angry. The problem persists with or without the accessories on the sprite.

**Comment by benawad** [comment]
if you open voidpet in a new tab (to confirm you have the latest version), does this still happen?

**Comment by reallybelt** [comment]
Just tried what you said, it fixed the issue. My apologies.

Thank you for the fast response
