### ISSUE TITLE
“Catch a voidpet“ quest bug *revised*

### ISSUE THREAD

**Issue by RNoodlez** [voidpet/bugs#412]
**Describe the bug**

Cannot accept the rewards for completing the “catch a voidpet” quest, you can tap it or click on it but it will not do anything, it appears completed when you go to the quest person and when you check the quest log. Not a very huge problem I just can’t catch some rare voidpets because I wouldn’t have the 8 containers the quest gives you.

**To Reproduce**
1. Go to the quest person and complete the catch a voidpet quest 
2. Click anywhere on the completed quest and it will not redeem

**Expected behavior**
The 8 capture containers and 800 will not be redeemed

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

https://user-images.githubusercontent.com/103501994/162947312-312af28b-9664-4eb8-bd40-bb0f23ed0710.MOV

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [microsoft edge]
 - Version [Idk]

**Smartphone (please complete the following information):**
 - Device: [iPhoneXr]
 - OS: [iOS 15.4.1]
 - Browser [safari]
 - Version [Idk]

**Additional context**

**Comment by benawad** [comment]
try scrolling in the modal, I'll do a better job to fix the UI for that in the future
