### ISSUE TITLE
Catching a VoidPet

### ISSUE THREAD

**Issue by Abaios** [voidpet/bugs#414]
**Describe the bug**
When you click the voidpet and then press Try to catch and then give up, it will make the voidpet disappear.

**To Reproduce**
1. Try to catch a voidpet
2. I used the Aura Container: orbit form.
3. Press give up.
4. Voidpet disappears without having to fight it or catch it. It's just gone.

**Expected behavior**
I expected the voidpet to be the same if I gave up, I would have assumed it would have just stayed there.

**Video or Screenshots**
[Video (google drive)](https://drive.google.com/file/d/1qqaYnJSqd-KJ6UysVnvq17eyJ8XYQuaz/view?usp=sharing
)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Version: 15.4 (safari)

**Comment by benawad** [comment]
intended behavior
