### ISSUE TITLE
It won't let me buy the fancy hair

### ISSUE THREAD

**Issue by Kwolfwolf** [voidpet/bugs#416]
**Describe the bug**
The game  simply wont let me buy the most expensive hair in the shop. I have enough coins(?) 

**Expected behavior**
Allow me to buy the hair.

**Comment by benawad** [comment]
Could you show a video

**Comment by Kwolfwolf** [comment]
@benawad 
https://drive.google.com/file/d/1mnspJRgYfrwjWQIWU2OCOWIAqn-4t88I/view?usp=drivesdk

**Comment by Kwolfwolf** [comment]
@benawad  Ii was able to buy a capsule thing. I will try on a different browser and report back.

**Comment by Kwolfwolf** [comment]
@benawad I not had a chance to try it and it worked. Thank you
