### ISSUE TITLE
More than 3 voidpets in one area

### ISSUE THREAD

**Issue by kocilla007** [voidpet/bugs#418]
**Describe the bug**
I was fighting with lonelys and when i went on difrent map i saw this. Im not sure what or how that happend but 12 wild voidpets spawn in one area. 

**Video or Screenshots**
![Screenshot_2022-04-12-12-45-55-55_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/103502127/163033199-9ec0a7f3-d8ca-4f0a-8765-9d56f43fb46b.jpg)

**Smartphone (please complete the following information):**
 - Device: Oppo reno5lite
 - Browser: Chrom
- Version: I dont know exacly but it happend 12/04/2022

**Comment by benawad** [comment]
that's a feature

**Comment by kocilla007** [comment]
Ohh ok i didnt know, im realy sorry for trouble then ^^'
