### ISSUE TITLE
Moves wont load

### ISSUE THREAD

**Issue by EndigoLikesArson** [voidpet/bugs#419]
When I tried to attack a wild voidpet, the moves wouldn't load. It said I used the points, but even though I waited a few seconds it wouldn't attack. I could still remove the moves used

**To Reproduce**
1. Attack a voidpet
2. try to use moves

**Video or Screenshots**

https://user-images.githubusercontent.com/103539773/163064022-23b6043d-b69d-4f3d-87e1-6b839f61d5cf.mp4

**Desktop (please complete the following information):**
 - Browser chrome

**Additional context**
I was clicking through rather fast, it might have something to do with it?

**Comment by benawad** [comment]
Are you stuck in this state after a refresh?

**Comment by EndigoLikesArson** [comment]
Nope. A refresh fixed everything!

**Comment by benawad** [comment]
Thanks I’ll look into this
