### ISSUE TITLE
Adding multiple of the same item to cart causes unusual behavior

### ISSUE THREAD

**Issue by SeventyFox92475** [voidpet/bugs#42]
When adding an item to the cart, instead of adding to the quantity of an already existing item of the same thing, sometimes it makes a whole new item in the cart. It's seemingly random on what it decides to do (add a new item or add to the quantity of an existing item)

![image](https://user-images.githubusercontent.com/45300419/146439404-3e6f20dc-d9d7-42a3-bde7-abb624a4ddd6.png)

**Comment by benawad** [comment]
fixed
