### ISSUE TITLE
Stat boosts

### ISSUE THREAD

**Issue by phospheur** [voidpet/bugs#424]
Never done a bug report before, so I hope I did this right. This is on mobile, Samsung Galaxy, and i use the Ecosia mobile browser.
As far as I know, when you boost a stat and knock out enough voidpets it's supposed to slightly raise that boosted stat permanently.
For my starter I had satisfaction boosted all the way, before the boost it was 67. I used said starter during tartarean day and I know I had played for 5+ hours knocking out almost every voidpet. Couple minutes ago today I played with my starter and of course it lost the boost, but it returned to 67.
I don't know how many you need to knock out and maybe I didn't reach that number, but I did bring it up in the Discord because this isn't the first time I've tried permanently raising stats and didn't succeed, which is why I'm making a bug report since a member suggested to do.

**Comment by benawad** [comment]
I can't explain how this works because it's a hidden feature that we want players to discover the ins/outs of, but the code seems to be working for it

**Comment by phospheur** [comment]
I understand that y'all want to keep some features hidden for players to discover on their own, but trying to permanently increase a stat for hours and still not having any progress, not understanding what you're doing wrong or what else you're supposed to do, is really frustrating and discouraging.
