### ISSUE TITLE
Exploration bug

### ISSUE THREAD

**Issue by Nike-Pithos** [voidpet/bugs#427]
**Describe the bug**
I'm very new to the game and after customizing myself was clicking up arrows to look around and got an error screen telling me to screenshot nd come here.

**To Reproduce**
1. Go to explore area- it was the school i believe and the "headmaster" was waiting in a pool area i think. 
2. Click on the up arrow a few times in a row

**Expected behavior**

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.
<img width="915" alt="sc-void-issue" src="https://user-images.githubusercontent.com/103593158/163226779-1c83f7b7-cee5-4187-956a-dd8dc8be4c23.PNG">

**Desktop (please complete the following information):**
 - OS: 64-bit operating system
 - Browser chrome
 - Version Version 100.0.4896.88 (Official Build) (64-bit)

**Additional context**

**Comment by benawad** [comment]
try opening voidpet in a new tab
