### ISSUE TITLE
Unable to load voidpets via laptop

### ISSUE THREAD

**Issue by v0xii** [voidpet/bugs#428]
I cannot open voidpet in any tabs, new or old.

Whenever I make a new tab and go to either voidpet.com or voidpet.com/o/explore, nothing works. For the regular voidpet link, anger is spinning, yet the top voidpets do not move whatsoever. For the voidpet explore link, anger spins, but nothing else happens.
I'm unsure if this is happening to anybody else but it hinders my ability to play voidpet comfortably, as only mobile works for me now.

**To Reproduce**
1. Open voidpet.com or voidpet.com/o/explore
2. You will view what is the loading screen, for 1st link instance, no sprites are moving except for the spinning sprite. For 2nd link instance, only the spinning sprite is present and working.
3. Those are the errors I view, unsure if this is going on for anybody else.

**Expected behavior**
I expected it to load, yet it pauses, refresh button on the top left corner showing it is able to refresh, not in the loading X that it should be.
**Video or Screenshots**
![nromal](https://user-images.githubusercontent.com/103593222/163232054-30f27623-026a-49b1-82cc-8f30e96ababe.png)
https://user-images.githubusercontent.com/103593222/163232161-fe2fd6c2-cca5-438f-9800-ea0604ab10f1.MOV
https://user-images.githubusercontent.com/103593222/163232133-f4c3f6be-ab89-4c39-9466-f1c8d982a10a.MOV

**Desktop (please complete the following information):**
 - OS: (could only find OS build) 19043.1645
 - Browser: Google
 - Version: 21H1

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: 15.3.1
 - Browser: Safari
 - Version: (could only find software version) 15.3.1

**Additional context**
This is only going on for my laptop, any other device is ok (such as my phone or iPad).

**Comment by benawad** [comment]
Someone had this before when a really old version got cached for some reason.

Could you try opening voidpet on a different browser on your computer to rule out that possibility

**Comment by v0xii** [comment]
Thanks for the tip, opened voidpet on microsoft edge and it worked!
