### ISSUE TITLE
I am unsure if im doing something wrong but i seem to be unable to level up 

### ISSUE THREAD

**Issue by ErrorSimp** [voidpet/bugs#429]
I have been playing for about a day now and I started to kill things at first it let me level up to level 4 and then it rarely gave me exp now it's giving me none I don't understand why and I'm unsure if I did something wrong 
(sorry if you cant see the video i had to record it on my phone because my pc wouldnt let me record) 
 - OS: windows
 - Browser: Brave 
 - Version: [1.37.111 Chromium: 100.0.4896.79](https://brave.com/latest/)

https://user-images.githubusercontent.com/103610576/163282641-e2e79e92-7f8e-4a79-a80c-53c1ccb98f1d.mov

**Comment by benawad** [comment]
You are getting XP, but 388 XP at Lv 4 won't move the bar much
