### ISSUE TITLE
A uncommon amount of lonely appeared at the ghost road

### ISSUE THREAD

**Issue by Lotch01** [voidpet/bugs#431]
Description:

About 12 lonely appeared at the ghost road. I could interact with them normally (fight, catch or scare away).

1. Scare away all the lonely void pets at the second ghost road
2. Go up
3. Get back to the second catching area

**Expected behavior**
There where supposed to be just 3 lonely voidpets

Screenshot:

![Screenshot_2022-04-13-21-32-47-709_com android chrome](https://user-images.githubusercontent.com/103614073/163293695-b150d5d5-0c34-4de2-bf22-bed0c0e001a2.jpg)

Smartphone :
 - Device: Redmi 8
 - OS:  Android 10
 - Browser: Chrome 
 - Version: 100.0.4896.88

**Comment by benawad** [comment]
feature
