### ISSUE TITLE
Arcane vivid in landing still has old name

### ISSUE THREAD

**Issue by soupy227** [voidpet/bugs#434]
Not exactly a bug, but while i was looking at the vivid chart in the landing as a checklist, i noticed that the Arcane variant was still labeled as Lucid. 

![Screenshot_20220414-152136_Chrome](https://user-images.githubusercontent.com/103346963/163462451-7d3f5235-0e05-4dab-8811-dbc62a30d8af.jpg)

**Comment by benawad** [comment]
fixed
