### ISSUE TITLE
Won’t let me access new update 

### ISSUE THREAD

**Issue by Kyanarsa** [voidpet/bugs#435]
I’m not really too active on this game because it was still a wip but when the new update came out for open world and I saw it on tiktok I was like “ooo Pokémon” /j and I got on my tablet to try and see what it was like but I went to click explore for the world and it just told me that there was a server related error on my side? I’m really confused and just wanna give Levi some buddies and cute hats

**Comment by benawad** [comment]
Could you screenshot the error

**Comment by benawad** [comment]
Try opening voidpet in a new tab

**Comment by benawad** [comment]
https://voidpet.com/o/version
