### ISSUE TITLE
Secret Bug

### ISSUE THREAD

**Issue by GatoThor** [voidpet/bugs#436]
I have completed the secret, but when I add my bio and things, I click save. But it does not save for some reason?

**To Reproduce**
1. Complete the creator secret thing in the source code analysis channel
2. Click on edit profile
3. Add stuff then click save
4. See error (stuff doesn't save and doesn't show your discord pfp)

**Expected behavior**
If you go to the source code analysis channel and go to pins and click on chapters, scroll down a bit he will link his profile there
and if you go to his profile it shows what was supposed to happen

**Video or Screenshots**
no can do

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Opera GX
 - Version 2022-04 Cumulative Update for Windows 11 for x64-based Systems (KB5012592)

**Additional context**
I spent 2 days looking for the secret, so I'm a little bit mad. /hj

**Comment by benawad** [comment]
Try it again, just fixed it

**Comment by GatoThor** [comment]
thx so much
