### ISSUE TITLE
Voidpet catch block

### ISSUE THREAD

**Issue by perihelion21** [voidpet/bugs#438]
Whenever I try to catch a wild Voidpet, no matter the level, it will say "Wild pet is too high to catch."

**To Reproduce**
1. Go to Ghost Road
2. Click on any wild Voidpet
3. Click "Try to catch"

**Screenshot**
![bug](https://user-images.githubusercontent.com/103702219/163494184-5423f753-4f15-4065-8ea7-2f37c9044e6e.PNG)

**Comment by benawad** [comment]
What's your voidpet username?

**Comment by perihelion21** [comment]
oktoes

**Comment by benawad** [comment]
Should be fixed now

**Comment by perihelion21** [comment]
Thank you!
