### ISSUE TITLE
Too many voidpets

### ISSUE THREAD

**Issue by greyrose315** [voidpet/bugs#439]
**Describe the bug**
The second tier of catchable voidpets has many more voidpets than is typical. Instead of three, there were twelve sprites on screen.

**To Reproduce**

**Expected behavior**
Three catchable voidpets sprites on each level

**Video or Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS:  iOS15.1
 - Browser: Safari

**Additional context**
Unsure of version information, unsure of utilization of screenshot function on device, unsure of life in general
I took one of the twelve before I realized there was an issue, a jaded one if you want it back (?) 
- Ro, Mari

**Comment by benawad** [comment]
feature
