### ISSUE TITLE
Clunky UX

### ISSUE THREAD

**Issue by saberelbah** [voidpet/bugs#44]
1. Once you go to the shop, you can't go back to home, unless you change the url in the address bar.
2. Why do you have a Discord input field in the Edit Profile menu, is the user here supposed to enter his Discord profile? if so, why the placeholder points to the voidpet channel? it does not make any sense!

**Comment by DumbGameMaker** [comment]
1. The shop is a separate website, similar to forums and docs websites which are linked to on the main page but dont have a link back
2. The discord field is intended for discord urls, like discord.gg/F5fqb7s3
