### ISSUE TITLE
Unable to equip hat to Anxious 2

### ISSUE THREAD

**Issue by BobHatchet101** [voidpet/bugs#441]
Under equipping accessories to pets, it is possible to see what it would look like to equip either the bees antenna or the ephemeral crown (the only head items I currently possess), but the "save" button won't allow me to keep it.

I am unsure if this is a mobile only issue, but I would like to be able to equip hats to my starter, lol.

**Comment by benawad** [comment]
Could you show a video?

If you refresh does it show up?

**Comment by BobHatchet101** [comment]
I'm not really sure how to take a video of it, but basically I select a hat
to equip to my Anxious, and the "save" button just doesn't work. If I
remove the hat it works just fine, but I can't leave with it equipped. I
can see it in the preview normally. There's no issue with any other
voidpets, just my starter.

**Comment by benawad** [comment]
Is your starter one of your 3 main pets?

If you make your starter not one of your main 3 pets does it work?

**Comment by BobHatchet101** [comment]
It normally is, ill test that right now

**Comment by BobHatchet101** [comment]
No difference either way, I just tap on the save button and it doesn't
react until I remove the hat.

**Comment by benawad** [comment]
Are you able to equip this hat to other pets and not just your starter?

Do you think the problem is with the hat or the starter?

**Comment by BobHatchet101** [comment]
It is definitely the starter, my only hats are 2 ephemeral crowns, and the
bees antenna, all of which do not work on my starter, but are currently
equipped to other voidpets. I have even tried unequipping all other
accessories, then trying to equip hats to it, but i just can't select save.
There is no issue with scarves either, just hats

**Comment by benawad** [comment]
So when you save it doesn't close the picker window?

**Comment by BobHatchet101** [comment]
I just can't select save at all. The button is there, but it only works if
i unequip the hat. It doesn't even do the little press animation.

**Comment by benawad** [comment]
Just pushed an update that should fix it, refresh and try again

**Comment by BobHatchet101** [comment]
All in order! Thank you, and I love the game so far.

**Comment by BobHatchet101** [comment]
Refreshing doesn't change anything, I've tried since accessories came out,
but I didn't know how to report it till now.
