### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by YourLocalFailure** [voidpet/bugs#444]
**Describe the bug**

**To Reproduce**
1. Go to Heal Pets
2. Click on Right
3. Click on the void matter seller
5. See error
Also several pets in horto east were oversized
![Screenshot_20220416-143841_Chrome](https://user-images.githubusercontent.com/103852170/163687586-477be036-0ce7-4db6-a417-4e34263b9526.jpg)

**Expected behavior**

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [Samsung A12]
 - chrome
 - version: newest

**Additional context**

**Comment by benawad** [comment]
https://voidpet.com/o/version
