### ISSUE TITLE
Element change 

### ISSUE THREAD

**Issue by Gingerre** [voidpet/bugs#447]
**Describe the bug**
My envy was metal. Now its water.

**To Reproduce**
Idk

**Expected behavior**
It's just water element now, not metal anymore

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.
No
**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] chrome and on my phone. Everywhere, it changed across all devices

**Smartphone (please complete the following information):**

**Additional context**

**Comment by benawad** [comment]
we started showing secondary element instead of primary
