### ISSUE TITLE
Hoards of Lonely

### ISSUE THREAD

**Issue by Space-Nexus** [voidpet/bugs#449]
I'm not sure if this is a bug or a natural occurrence, but I checked with my friends who play the games and they haven't encountered this either. 

While hunting items for the most recent event, on the second Ghost Road area, numerous amounts of Lonely appear as opposed to the normal 3. They all function and act normally and after clearing them all the page returns to normal. While it has no functional issues I wasn't sure if the devs intended it to be intentional. I've encountered this occurrence twice in the same place.

Timestamped Proof for devs:
[Occurrence 1](https://cdn.discordapp.com/attachments/450307808970407936/965276926644224042/unknown.png)
[Occurrence 2](https://cdn.discordapp.com/attachments/450307808970407936/965284916910772285/unknown.png)

**Comment by benawad** [comment]
rare feature
