### ISSUE TITLE
Incorrect YouTube URL validation

### ISSUE THREAD

**Issue by alii** [voidpet/bugs#45]
Hey team, congrats on the launch! Noticed a bug on the edit profile page.

The URL `https://youtube.com/mrelec1000` is perfectly valid as a YouTube channel URL. Whilst this is just my page, usernames like `https://youtube.com/pewdiepie` so would be cool to have this as a valid URL. 

Thx! 💖

**Comment by lpatmo** [comment]
Seeing the same error on the edit profile page. Thanks!

**Comment by DumbGameMaker** [comment]
pretty sure you're supposed to use youtube.com/c/mrelec1000

**Comment by alii** [comment]
It's best to support as many formats as possible so users aren't confused @DumbGameMaker 🙂

**Comment by benawad** [comment]
done
