### ISSUE TITLE
This happened while exploring

### ISSUE THREAD

**Issue by ashtynrayn** [voidpet/bugs#450]
I was exploring and doing the void pet battles, I went up a few times past the witch lady and then it said I had reached an impossible state. 

 - Device: iPhone 12 Pro Max 
 - OS: iOS 15.4
 - Browser: Safari
 - Version: I don’t know
 
![1FF2EA36-41D3-4117-993D-37F508DCFEC7](https://user-images.githubusercontent.com/103894978/163723393-94b40ac8-9a9f-4b73-abf7-b4b0f72a2861.png)

**Comment by benawad** [comment]
https://voidpet.com/o/version
