### ISSUE TITLE
Basically can’t play normal anymore

### ISSUE THREAD

**Issue by SusAmogus12** [voidpet/bugs#452]
So I was playing void pets with my friend and I lost all my capsules and I couldn’t catch the void pets or play normally and it was basically impossible to earn the things to craft them!!And if I wanted to I probably would’ve had to buy the giga

**Comment by benawad** [comment]
Giga does not help you progress in the game.

You'll need to defeat some wild voidpets to collect void matter and buy some new capsules

**Comment by Justiniscoding** [comment]
> 

How do you buy the capsules?
