### ISSUE TITLE
12 Wild Lonelies on Ghost Road

### ISSUE THREAD

**Issue by amelia-aliyah** [voidpet/bugs#455]
After refreshing Ghost Road, 15-20 wild Lonelies are present, instead of the regular 3.

All Lonelies can be interacted with.
![BF359130-6B85-4127-976B-9A5DECD1F7E7](https://user-images.githubusercontent.com/103952493/163839474-841ac658-0da7-483e-9003-de2b588e7452.png)

**Comment by benawad** [comment]
Feature
