### ISSUE TITLE
Reached an ‘impossible state’

### ISSUE THREAD

**Issue by mnw2014** [voidpet/bugs#457]
**Describe the bug**
I was playing the game moving around the rooms after just setting up my character. I finished battling 5 friendly voidpets and swiped to the right and this popped up saying to report an issue to get my account fixed. Now when I try to explore this is all I see.

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 15.4.1
 - Browser: Safari
 - Version: I don’t know

![86A28BE7-2289-440E-BFBA-5292494954B5](https://user-images.githubusercontent.com/103966034/163878956-7089c495-2efe-4a38-b01d-047f5e086729.png)

**Comment by benawad** [comment]
https://voidpet.com/o/version
