### ISSUE TITLE
Voidpet turn

### ISSUE THREAD

**Issue by 20Ash02** [voidpet/bugs#459]
**Describe the bug**
A white screen with text in it, saying to come here to get it fixed

**To Reproduce**

**Expected behavior**
Get my account on this web game fixed so that I can continue playing 

**Video or Screenshots**
![CE203B04-B5D2-4D6D-BF7E-B9F13553BB6F](https://user-images.githubusercontent.com/103995746/163971909-c5193a6e-b8ad-4356-8dcf-10c1a245d841.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: 15.3.1
 - Browser: Safari
 - Version: ??

**Additional context**

**Comment by benawad** [comment]
https://voidpet.com/o/version
