### ISSUE TITLE
"impossible screen" in explore area

### ISSUE THREAD

**Issue by dogcrapp13** [voidpet/bugs#460]
I pressed the right arrow while in the west wild area, and it took me to an "impossible screen"
to replicate it, press right arrow in the west are with the wild voidpets.
![image](https://user-images.githubusercontent.com/104046849/164135683-e672d3ec-54cb-41ae-9c2c-91663b6804b9.png)

**Comment by benawad** [comment]
https://voidpet.com/o/version
