### ISSUE TITLE
scare away button disappearing and reappearing

### ISSUE THREAD

**Issue by loadingding** [voidpet/bugs#463]
**Describe the bug**
sometimes the scare away button disappears for hours or a day or two and then comes back for a while. 

**To Reproduce**
i have no idea how it disappears :,)
(or how to make it come back T-T)

**Expected behavior**
i expected the button to be there?? idk if its just been taken out for bug fixes and stuff but it'd be nice for it to be there

**Video or Screenshots**
![7A5AC904-4A61-42A1-BDBA-CF3F968BC09C](https://user-images.githubusercontent.com/104099040/164305685-6e32a4ff-6342-4eb1-aa97-73aeae5968ba.png)

**Smartphone (please complete the following information):**
 - Device: iphone 11
 - OS: ios 15.4.1
 - Browser: safari
 - Version: 15.4.1? idk what this means ehehe

**Additional context**
no more context needed i guess

**Comment by benawad** [comment]
Whenever it doesn’t show up, could you go to https://voidpet.com/o/version and see if it’s related to be on an old version
