### ISSUE TITLE
Void pets not recieving EXP

### ISSUE THREAD

**Issue by plantladie** [voidpet/bugs#464]
I know the game is incomplete, but i wanted to grind and level up my pets anyway. I've been defeating other monsters, but no EXP is being received.

After the battle, it does say they gain X amount of exp, but the bar doesn't move. I just wanna see my babies evolve :(

**Comment by benawad** [comment]
Level cap is 5, we’ll be increasing it soon

**Comment by plantladie** [comment]
> Level cap is 5, we’ll be increasing it soon

My monsters are lvl4 and under

**Comment by benawad** [comment]
Then they are still gaining XP, but killing voidpets may not give you much. More quests are coming soon!
