### ISSUE TITLE
Bug while walking through the game

### ISSUE THREAD

**Issue by Bango44** [voidpet/bugs#465]
Was walking through the game and this message popped up

**Video or Screenshots**
![Screenshot_20220421-001550_Brave](https://user-images.githubusercontent.com/104104638/164325529-91f7d80e-37d6-4c24-9470-c2eaeb9c95f4.jpg)

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy A51
 - Browser

**Comment by benawad** [comment]
https://voidpet.com/o/version
