### ISSUE TITLE
A lot of wild lonelies spawned in Ghost Road and a weird square is around one of them

### ISSUE THREAD

**Issue by BananeBleuet** [voidpet/bugs#466]
**Describe the bug**
11 lonelies on Ghost Road and a weird square surrounding one of them

**To Reproduce**
1. Go to Ghost Road
2. Click on a wild lonely
3. Square?

**Expected behavior**
I expected only a couple of lonelies since I only ever get two or three lonelies at once

**Video or Screenshots**
![image](https://user-images.githubusercontent.com/104111417/164347637-11f962d7-6a87-472d-99ef-191e32a1487c.png)

**Desktop (please complete the following information):**
 - OS: Chrome OS?
 - Google Chrome
 - ?

**Comment by benawad** [comment]
Feature
