### ISSUE TITLE
Too many Spawns on Ghost Road

### ISSUE THREAD

**Issue by D3nDraws** [voidpet/bugs#467]
12 Different Wild Lonelys spawned on Ghost Road

**To Reproduce**
1. Go Ghost Road
2. Scare Away all 3 Wild Lonelys
3. Leave ghost road by going up, and Scare the other Wilds
4. Return to Ghost Road and 12 

**Expected behavior**

**Screenshot**
![24349B5E-ECAF-4353-9D79-FD6A37A09F4C](https://user-images.githubusercontent.com/87205876/164358140-a994bb11-a1e3-49e1-add4-e681b9980ed9.png)

**Smartphone (please complete the following information):**
 - Device: Iphone XR
 - OS: iOS 15.4.1
 - Browser: Safari
 - Version: Most recent Version (0.11.0)

**Additional context**
I was trying to encounter cooler voidpets.
Glitch also appears on different device on safari in the same account. They are able to be scared away, Fought, and Caught. When all have disappeared, leaving ghost road and returning with spawn the normal amount of wild lonelys 

**Edit**
I was able to recreate the glitch on an Ipad (7th Generation) on IpadOS 15.4.1, on safari.

**Comment by benawad** [comment]
This is a feature
