### ISSUE TITLE
Glowing white boxes in fight with Angy

### ISSUE THREAD

**Issue by VampireSpirit** [voidpet/bugs#468]
**Describe the bug**
When I'm in Horto West and fight Angy all the attack boxes are surrounded by a white glow. So far this seems to be the only battle with the white glowing boxes.

**To Reproduce**
1. Go to 'Horto West'
2. Click on 'Angy'
3. Click on 'Ask Angy to Battle'

**Expected behavior**
No glowing white boxes

**Video or Screenshots**
![ehe](https://user-images.githubusercontent.com/104150217/164477207-8b7cce89-258e-4163-8d66-b47ca5c80192.png)
![hmm](https://user-images.githubusercontent.com/104150217/164477235-992784d7-4367-4ba4-a8b9-511b6de75fcb.png)

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Version 21h2

**Comment by benawad** [comment]
this indicates the attacks will hit harder because of your type advantage
