### ISSUE TITLE
Can't leave the Atrium

### ISSUE THREAD

**Issue by marialoureir0** [voidpet/bugs#469]
**Describe the bug**
Im uncapable of advancing the game and cant go anywhere other then Atrium and Taberna. I'm on the first quests and have no way to do them because i cant move to the places they are set. I've clicked anywhere possible and didnt find a way out of this loop of going up and to the side in the Atrium/Atrium Pool/Taberna.

**To Reproduce**
1. Go to 'explore'
2. Click on 'the arrows up and right'

**Video or Screenshots**
![image](https://user-images.githubusercontent.com/104174322/164566316-6a054d4a-e76a-4605-8a0d-fa0518d09500.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [ 100.0.4896.127]

**Additional context**
I havent found a way to get out of this place, im not giga but i belive that since i have quests open i should be able to do them without it.

**Comment by benawad** [comment]
What happens when you keep going forward from `Atrium Pool`?

**Comment by marialoureir0** [comment]
Hello, thank you for your quick response! I don't know what happened but
the option to keep going up from the Atrium pool appeared now! I can see
the rest of the map no problem, sorry for taking up your time with this.
I'm not sure if i just didn't notice the opacity of the button correctly or
it really wasn't working but thank you for your help anyways.

Em qui., 21 de abr. de 2022 às 21:07, Ben Awad ***@***.***>
escreveu:
