### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by jwlexi** [voidpet/bugs#47]
Allow users to delete their account, remove their phone number as well so they can create a new account if they wanted to

**Comment by DumbGameMaker** [comment]
hey, can you please edit this so it has [Feature request] in the title? just because this is not really a bug and to make it more clear. Thanks!

**Comment by DumbGameMaker** [comment]
Also, you could have combined this with #46 as well

**Comment by benawad** [comment]
https://voidpet.com/o/account/delete
