### ISSUE TITLE
Hiya, I'm sorry it's not a bug.

### ISSUE THREAD

**Issue by Chalaske** [voidpet/bugs#470]
I just started and when I made my pet I gave him the name Mr. Top Hat, but it autocorrected to Me. Top Hat, a significantly less cool name. I was hoping there was some way I could change it? Your game looks so good so far, it's incredible what you’ve done.

**Comment by benawad** [comment]
I changed the name for you

Renaming pets is a Giga feature https://voidpet.com/o/giga
