### ISSUE TITLE
Impossible state

### ISSUE THREAD

**Issue by coldgranite** [voidpet/bugs#473]
I'm stuck on the "impossible state" and I tried all the things to get out of there. Refreshing the tab, opening vp in another tab, it doesn't work.

**To Reproduce**
1. You can't really reproduce the behavior of this bug.

**Expected behavior**
Get taken to the new update?

**Video or Screenshots**
![image](https://user-images.githubusercontent.com/100749687/164845061-8a39ad3d-ca89-40ba-ae5a-7215292b0601.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: -

**Additional context**
Account - https://voidpet.com/Flamingoo

**Comment by dysdipity** [comment]
yeah it seems a lot of people including me are having the same issue :/
