### ISSUE TITLE
I cant play the game

### ISSUE THREAD

**Issue by Dragondoodle** [voidpet/bugs#477]
**Describe the bug**
I was playing thr game and this error came up. I did all that it asks but it still has issues. I was trying to complete one of the first quests the game gives you, to catch a lost pet and I guess I went too far because then the error came up.

**Smartphone (please complete the following information):**
 - Device: Samsung note 20
 - OS: I'm not sure 
 - Browser:chrome 
 - Version I'm not sure
![Screenshot_20220422-210204_Chrome](https://user-images.githubusercontent.com/104238950/164845545-b88eeacc-99cb-449d-974d-945bb9cc3587.jpg)

**Comment by benawad** [comment]
try again
