### ISSUE TITLE
I looked at the perks and prices of becoming mega, pressed "back" and it gave me the bug screen, did the things it recommended and it didn't work, I'm on a galaxy S9 android v10 using the "internet" app on the phone, with the duckduckgoose browser, not sure of the version but the most recent one on 22nd of April 2022, sorry

### ISSUE THREAD

**Issue by salsa2444** [voidpet/bugs#478]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![Screenshot_20220422-210108_Samsung Internet](https://user-images.githubusercontent.com/104238948/164845138-5ddf8438-62ea-48f3-9161-09d937e74091.jpg)

**Comment by benawad** [comment]
try refreshing update should be out now
