### ISSUE TITLE
Void Matter Color not Changing

### ISSUE THREAD

**Issue by Theonlywayne** [voidpet/bugs#480]
I was able to get the void matter color called stygialis and when I went to select to change it from infernalis, then click save, it brings you out of the menu but does not save the changes and the color sticks to infernalis. I've only seen this not update with the color stygialis. This bug persists on mobile and desktop.

To Reproduce:
1. Go to explore
2. Click on avatar
3. Scroll to void matter color 
4. Change the color to something other than infernalis
5. Click save
6. Click on avatar again
7. See error

Smartphone information
 - Device: Samsung Galaxy s8 
 - Browser: Google Chrome
 - Version: N/A

**Comment by benawad** [comment]
just fixed, try refreshing
