### ISSUE TITLE
I can't click flowers

### ISSUE THREAD

**Issue by Starrdome** [voidpet/bugs#484]
One of the quests is to collect 10 flowers - yet I can't seem to click and collect the flowers. It is very frustrating and leaves me unable to complete the quest.

1. Go to Something Park
2. Find flower (they appear and disappear very quickly) 
3. Click on flower

Expected behavior
The flower will enter my inventory and I'll be able to complete the quest. 

Desktop
 - Dell

**Comment by benawad** [comment]
Are you clicking on pink flowers and not yellow ones?

**Comment by benawad** [comment]
added an update so it should be easier to get now
