### ISSUE TITLE
Void matter colour customisation

### ISSUE THREAD

**Issue by Lazy-Neko** [voidpet/bugs#486]
Void matter colour customisation does not save. Tried changing colour and when I save and go back in it is back to the default colour.

![Screenshot_20220423-201616_Chrome](https://user-images.githubusercontent.com/101967422/164890386-a2a72ef2-b33d-4f2d-ba97-02d0e16ae9f5.jpg)
![Screenshot_20220423-201622_Chrome](https://user-images.githubusercontent.com/101967422/164890390-91f135b0-dc9c-42ea-bf58-9c90fcb788c5.jpg)

**Comment by benawad** [comment]
try refreshing, should be fixed now
