### ISSUE TITLE
Invalid input error when adding moves

### ISSUE THREAD

**Issue by jazzyd6099** [voidpet/bugs#487]
**Describe the bug**
I got a new book move for one of my lonely voidpets but whenever I add the move then save and I exit out of the menu, I get an invalid input error.

**To Reproduce**

Go to 'Change moves' on a pet lonely 
Click on ‘+' on the move you want to change
Click ‘Save’ then exit out
See error: Invalid Input appears at the top

**Expected behavior**
I expected for the move to be added to the moves menu and be able to use it in battle.

**Video or Screenshots**
![F7D43C7F-005E-40F9-B84B-FC43D8AD37DE](https://user-images.githubusercontent.com/41112271/164893179-489a6c86-362a-4a7c-8a93-100f9692b20a.jpeg)

**Smartphone (please complete the following information):**
 - Device: Iphone XS Max
 - OS: IOS 15.5
 - Browser: Safari
 - Version: 15

**Comment by benawad** [comment]
What's your voidpet username?

Which pet?

Which book?

**Comment by benawad** [comment]
should be fixed now
