### ISSUE TITLE
Pink Dandelion

### ISSUE THREAD

**Issue by scdfgvvh** [voidpet/bugs#490]
**Describe the bug**
I can't seems to be able to pick up dandelion, even is they are not near pavillon that allow us to descend, it's been like since a flower pop near the entrance, after that I wasn't able to pick any dandelion

**To Reproduce**
1. Go to 'Something Park Pavillon'
2. Click on 'a dandelion near the center pavillon'
3. See error : you won't be able to pick up any dandelion for now

**Expected behavior**
I expected to pick up a dandelion for the mission that the girl with blue hair gave us

**Video or Screenshots**
I don't know how to had a screenshot or a video sorry

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Besides this bug i just wanted to say that your game is really cool and simple to understand, good work 👍

**Comment by benawad** [comment]
Do the other areas work for you?

**Comment by benawad** [comment]
added an update so it should be easier to get now
