### ISSUE TITLE
Dandelion Quest Bug- Flowers Sometimes Unclickable

### ISSUE THREAD

**Issue by AnBlackRose** [voidpet/bugs#493]
I see other bugs posted with this, but thought providing more data would be better than not.

There seems to be an issue with the flower quest- they spawn in places that you wouldn’t  be able to click on them in or in places you should be able to, but I was unable to for some reason.

The main ability to reproduce this bug is to have them spawn in the lower part of the screen. More often than not, if it is within the bottom of the screen that has the movement buttons, it is un-clickable. I do have one screenshot of one that was not this case (the last screenshot), so I am unsure of what occurred there. I have circled where the flower has spawned in each instance to make it easier to see.

<img width="1680" alt="Screen Shot 2022-04-23 at 10 58 05 AM" src="https://user-images.githubusercontent.com/104270350/164915051-651ee486-7602-45fa-9fb3-d8f352270bf4.png">
<img width="1680" alt="Screen Shot 2022-04-23 at 11 18 49 AM" src="https://user-images.githubusercontent.com/104270350/164915056-fc500c20-4610-46f5-b843-eaf1fb13975e.png">
<img width="1680" alt="Screen Shot 2022-04-23 at 11 19 42 AM" src="https://user-images.githubusercontent.com/104270350/164915059-60e4ae86-d673-4100-8374-5dfe25716547.png">

Issue is on a Macbook Pro, on Chrome, latest version.

**Comment by benawad** [comment]
thanks, added an update so it should be easier to get now
