### ISSUE TITLE
Spawn glitch

### ISSUE THREAD

**Issue by Blonchman** [voidpet/bugs#498]
Occasionally 12+ wild voidpets will spawn at once and it causes some lag.

**To Reproduce**
not sure how to reproduce

![Screenshot (3)](https://user-images.githubusercontent.com/104274563/164941684-d47d0b5d-65d7-4d4a-9ee7-18c7bbea30be.png)

**Desktop (please complete the following information):**
 - OS: x64
 - Chrome
 - Version 100.0.4896.127

**Comment by NaeNate** [comment]
I believe this happens on purpose.
