### ISSUE TITLE
Cannot Pick Pink Dandelions Blocked by UI

### ISSUE THREAD

**Issue by TangentOfTheCat** [voidpet/bugs#500]
**Describe the bug**
I couldn’t pick any dandelion that was too far down beneath the UI.

**To Reproduce**
1. Accept Hypen’s Quest
2. Go to the Something Park and start looking for Pink Dandelions
3. Any dandelion that’s too far down in the screen can’t be picked up

**Video or Screenshots**

(here’s one I couldn’t pick up)
https://share.icloud.com/photos/09fbXXR42LXQof0lIAdp1tNzQ

**Smartphone:**
 - Device: iPhone6S 
 - OS: iOS15.4.1
 - Browser: safari
 - Version: 15.4.1

**Additional context**
I found a dandelion that wasn’t covered by the movement controls but was on the lower part of the screen where the controls are; I also couldn’t pick that up. I could pick up dandelions that were slightly *above* the controls though, such as a dandelion whose bottom half was blocked by the up arrow but not it’s too half.

**Comment by benawad** [comment]
should be fixed now
