### ISSUE TITLE
Could not find user. 🧐

### ISSUE THREAD

**Issue by Fipo07** [voidpet/bugs#505]
When I join I'm directed to a page with "Could not find user."

I was playing the update and heard about the "black market", while trying to join it, the game froze and when I tried to rejoin the same thing would happen.

I am using google Chrome 

I hope this is fixed, I've been really looking forward this update (23/04), and now that this has hapened I'm afraid I won't be able to play any longer.
![Sem Títul2o](https://user-images.githubusercontent.com/104279416/164946550-e6077b58-58b8-4a86-bdd1-5ff3ffb086d1.png)

**Comment by benawad** [comment]
What's your username?

What happens when you go to https://voidpet.com and hit explore?

**Comment by Fipo07** [comment]
Sorry for the delay, my username is "Fipo", but to my surprise, the bug was fixed and I can now play normally.
When trying to go to anypage the same message would appear, except for the front page https://voidpet.com ; in this page it wouldn't show me an option to explore but one to log in with discord(which if I did, would lead me to the same bug message).
