### ISSUE TITLE
Tilde’s “Just say hi” Button Does Not Work

### ISSUE THREAD

**Issue by TangentOfTheCat** [voidpet/bugs#506]
**Describe the bug**
The “Just wanted to say hi!” button doesn’t work when interacting with Tilde.

**To Reproduce**
1. Go to Tilde’s room
2. Click on Tilde to interact with them
3. Click on the button labeled “Just wanted to say hi!”
4. Button will “bounce” but it won’t do anything else. It also seems to reset to slightly higher than it’s supposed to when it does that.

**Expected behavior**
I believe it’s supposed to close the interface for interacting with Tilde.

**Video or Screenshots**

https://share.icloud.com/photos/0a4qFM8SpiPeUnLF7ZQmKFnGg

**Smartphone:**
 - Device: iPhone6S
 - OS: iOS15.4.1
 - Browser: Safari
 - Version: 15.4.1

**Additional context**
I believe it’s only Tilde’s button that doesn’t work. The problem of buttons shifting out of place may happen with the others though, I’m not sure.

**Comment by benawad** [comment]
should be fixed now
