### ISSUE TITLE
Too many lonelies spawned on ghost road

### ISSUE THREAD

**Issue by frickity-frack** [voidpet/bugs#508]
**Describe the bug**
instead of the usual 3 lonelies, there are 9

**To Reproduce**
I dont know if it had anything to do with it, but I had just descended the pavilion all the way and defeated poki for the quest for Char, and was coming back down to accept my rewards

**Expected behavior**
there should only be three

**Video or Screenshots**
![image](https://user-images.githubusercontent.com/103015157/164954507-1464e31d-5eb8-4d17-a0d1-8b0460bc78bb.png)

**Desktop (please complete the following information):**
 Windows on chrome (sorry idk anything more than that)

**other information**
I don't know if this helps, but all of the lonelies that spawned were defeatable and dropped drops properly.
This game is turning out so well, I was so excited about the update!!!!

**Comment by benawad** [comment]
intended
