### ISSUE TITLE
Error message when boosting stats very high

### ISSUE THREAD

**Issue by Jervogel** [voidpet/bugs#509]
Bug description:
After using Manifestation to boost yours stats to 1658599748 no more moves are possible. When Attack is clicked, an error message pops up. When refreshed, the sote transports you out if the fight and all fight progress is lost.

1. Be in a fight 
2. Repeatedly use Manifestation to boost yours stats until they are at 1658599748
3. Try using any move
4. See error message
5. Refresh page and be transported out of the fight

Expected behavior:
I should still be able do do a move, any move, but that's not the case. When refreshing I should still be in the fight

Footage:
<img width="1348" alt="171A51B1-DD24-4BB9-B102-C91D1D926471" src="https://user-images.githubusercontent.com/104302495/164972910-34d01b44-39e5-4c88-80cc-d3aa8e01d539.png">

I think the reason for the issue is that if I were to go any higher, the damage would exceed 2,147,483,647, which is the largest possible value that a signed 32-bit integer fiel can hold

 - Device: iPad Pro
 - OS: iOS815.3.1
 - Browser: Safari

**Comment by benawad** [comment]
Should be fixed
