### ISSUE TITLE
"Invalid input" when adding moves to paranoia 

### ISSUE THREAD

**Issue by GoroTheThing** [voidpet/bugs#512]
**Describe the bug**
When adding moves they "save" but when exiting the screen it says "invalid input" and the moves did not save on the paranoia 

**To Reproduce**
1. Go to 'Change moves'
2. Select the moves you wanted to add 
3. Save
4. Exit
5. See error

**Expected behavior**
To add the moves 

**Video or Screenshots**
![Screenshot_20220424-063307_Chrome](https://user-images.githubusercontent.com/62208621/164979670-f47ba1e9-7d3b-4106-bc5b-adbe22693e6c.jpg)

**Smartphone (please complete the following information):**
 - Device: Android Galaxy A51
 - Browser: Chrome
 - Version: 0.12.0 (if u don't mean the games version then idk)
 
**Additional context**
It seems to only be the paranoia since it works fine when I add moves to other vps just not with them

**Comment by benawad** [comment]
what's your voidpet username and what's the pets name?

**Comment by GoroTheThing** [comment]
> 

User is: Gondso 
Vps name: Slip

**Comment by benawad** [comment]
Should be fixed now
