### ISSUE TITLE
Wrong Quest Given

### ISSUE THREAD

**Issue by KitKattBar** [voidpet/bugs#513]
**Describe the bug**
When asking Char about his arm, he told me to anger Tilde. After agreeing, I got the Spiteful Basement quest.

**To Reproduce**
1. Go to Char's room
2. Click on Char
3. Talk to Char about his arm, and where to get it
4. Agree to anger Tilde
5. See error

**Expected behavior**
Recieving a quest to anger Tilde and help evolve her Angy

**Smartphone (please complete the following information):**
 - Device: iPhone12 mini
 - OS: iOS 15.4.1
 - Browser: Safari
 - Version: 15.4.1 

**Additional context**
This was the first time interacting with Char, and I have not yet tested if I need to anger Tilde or if I need to go to the basement.
![D0C185D4-6D4A-4C09-9558-848646372B1C](https://user-images.githubusercontent.com/104314611/164984969-49683bd7-4173-487a-b462-6d4dc22139d5.png)

**Comment by KitKattBar** [comment]
I did need to defeat Poki, so it gave me the wrong quest entirely.

**Comment by artacat** [comment]
It didn't really help because Char is not letting me talk to him unless I finish the quest (i dont know how to upload a screen but it basically says "Hmm...
It doesn't look like you've finished your quest yet.")

thx hope you can fix it

**Comment by benawad** [comment]
You'll need to kill poki

**Comment by artacat** [comment]
but he doesn't exist

**Comment by benawad** [comment]
you can ask in the discord how to find poki https://discord.gg/voidpet
