### ISSUE TITLE
I can't give my pets new moves

### ISSUE THREAD

**Issue by Sadnessbaguette** [voidpet/bugs#514]
I have the books for the pets but after goung into customize moveset, pressing the + sign and saving it, it doesn't actually save and goes back to default when I check it again. Turns out this only happens to me, what do I do? 

I also have a video of the problem but it wouldn't let me attach it.

**Comment by benawad** [comment]
does this happen to all of your pets or only 1 of them?

**Comment by benawad** [comment]
should be fixed now
