### ISSUE TITLE
I got a pet sad 2, 155 days ago and I've been playing with it almost everyday and it says its adding bonding amount but it never goes up from

### ISSUE THREAD

**Issue by MasterCyborg612** [voidpet/bugs#526]
**Describe the bug**
I got a pet sad 2, 155 days ago and I've been playing with it almost everyday and it says its adding bonding amount but it never goes up from the amount in the screenshot

**Expected behavior**
I expected it to add more bonding level and possibly even level up to 7 but it hasn't yet and I've been trying for weeks now. It hasn't moved once it got to that spot

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.
![Screenshot 2022-04-25 6 10 40 PM](https://user-images.githubusercontent.com/104277227/165183462-6ba54338-923b-4c8d-aea7-7f50b2e4e5d3.png)

 - Device: [Chromebook]
 - Browser [Google]

**Comment by benawad** [comment]
It may not always visually look like it's increasing, but it still is
