### ISSUE TITLE
new pet lost after catch

### ISSUE THREAD

**Issue by 2CPU4U** [voidpet/bugs#527]
EDIT! solved my own problem! the following description still outlines my confustion however.
Pet is FOUND. it's just in the "memory"
I did not realize only 3 pets are in the party at once

**Describe the bug**
Pet does not show in collection. The "Success" animation was not shown, instead pet seemed to be caught as the next screen was the option to name the new pet. Issue was with a wild lonely on ghost road south

**To Reproduce**
1. Go to 'ghost road south'
2. Click on 'wild lonely' (do not remember which lvl this particular pet was, 1 or 2)
3. Click on 'try to catch'
4. Suss out
5. try to be friends
6. skips right to naming
7. ERROR friend gone )-:

**Expected behavior**

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - chrome Version 100.0.4896.127 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by benawad** [comment]
thanks for clarifying, I'll make that more clear
