### ISSUE TITLE
Pink dandelion quest issue with the inventory

### ISSUE THREAD

**Issue by VictoireA** [voidpet/bugs#532]
**Describe the bug**
On the quest of the pink Dandelion we had to collect ten of them. That is what I did. I went into Hypen room's to receive the prize of my quest and they told me I did not have the right amount of flowers.

**To Reproduce**
1. Go to 'Institute Hyphen Room'
2. Click on 'Hypen'
3. Click on 'the reward'
5. Click on 'Choose a reward'
6. See error

**Expected behavior**
Claim my prize 

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.
![Capture d’écran 2022-04-26 à 15 05 00](https://user-images.githubusercontent.com/104460387/165373652-db127351-90f1-46ba-af0f-abb5d42b09c0.png)
![Capture d’écran 2022-04-26 à 15 07 52](https://user-images.githubusercontent.com/104460387/165374107-5bda11da-d131-4b7c-935f-09adf3d5f55a.png)

**Desktop (please complete the following information):**
Safari browser

**Comment by benawad** [comment]
Do you have 10 in your inventory? Did you put one on your pet?

**Comment by CrabsterCrabby** [comment]
happen to me too
