### ISSUE TITLE
My voidpets aren't evolving

### ISSUE THREAD

**Issue by UoOOoOOh** [voidpet/bugs#534]
I have this voidpet sonder, right now is at the limit of level 7 but it's still a sonder one and none of the new voidpets that I've managed to catch in the new update have managed to evolve anymore, i evolved my sadness one to a sadness two and some loneliness before, but after the last update nothing has managed to evolve anymore

It is just me? It's just  a thing about the last update? Did I miss something? Can somebody tell me please I just want to know

**Comment by soupy227** [comment]
If its past level 4, it will be categorized as a Late Bloomer. You cant evolve these yet, its not a bug.
