### ISSUE TITLE
‘’congratulations, you have reached an impossible state’’

### ISSUE THREAD

**Issue by Darklight-999** [voidpet/bugs#535]
**Describe the bug**
I trully have no idea what happened at that moment but it crashed before i could capture an elemental pain so that sucks…
**To Reproduce*
Go from something park pavillion to something park north when it is empty
Be (un)lucky
???
Crash

**Expected Behaviour**
It could be pretty cool to fix this issue so it doesnt happen to anyone else

**Ipad**
 - IpadOS15.4.1
 - safari

**Additional context**
Nah, nothing else to say, anyways have a nice day!

**Comment by Darklight-999** [comment]
![8A9EEF4D-DBB3-4299-B71B-FEA1927DEE08](https://user-images.githubusercontent.com/104480571/165439100-d102c05e-0c81-4502-aa70-492be85207a4.jpeg)

**Comment by benawad** [comment]
https://voidpet.com/o/version
