### ISSUE TITLE
Memory has duplicates of pets

### ISSUE THREAD

**Issue by Fog-magic** [voidpet/bugs#539]
**Describe the bug**
In my memory I noticed that three of my pets in a row were duplicated again- pansy, Sondra and Tiny. They aren’t vivid, but they’re still cute. 
There are two other void pets in between the duplicates. They are in the same order. They are an anxious sondra and lonely so not related to the type- not sure how you code them. It’s not level either, but might be bond strength? 

**To Reproduce**
1. I don’t know if it’s something that i can reproduce- i was forgetting a few emotions- the weaker doubles of some vivid types (😭 I’m sorry)  and I just noticed that i had two pansy and then the other ones. At first I was just like- oh man i named them the same that’s silly- but I immediately came to report the problem but my phone won’t let me have this part up and also backtrack to the memory, it’s like it’s own app (ios)

**Expected behavior**

… for there to be no duplicates 

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

![EF155577-1BB8-455C-81BF-7062C1D9AE66](https://user-images.githubusercontent.com/104515795/165557266-b0682cc3-3f77-45b4-b7a5-d37f7739ef98.png)

Dunno if you can see that at all

**Smartphone (please complete the following information):**
 - Device: iphone 11
 - OS: iOS 15.4.1
 - Browser saved as app
 - Version 1

**Additional context**

ok so i went back( i opened up this ticket in safari because I couldn’t download pictures) and those three pets are no longer duplicates but!! They are the last ones before the (load more) button so it’s probably related. I bet the ones I deleted before moved them up in the list so they showed up on the first page as well as the second, where they were before. So it’s probably an issue with the database pull for each page of pets flowing together.

**Comment by Fog-magic** [comment]
Username DuCali

**Comment by benawad** [comment]
fixed
