### ISSUE TITLE
‘’Could not find this user 🧐’’

### ISSUE THREAD

**Issue by Darklight-999** [voidpet/bugs#540]
So, i went to the ‘’nice friend’’ npc and spammed the ‘’yes’’ option, the game’s red you are doing that too much popup then appeared, i got logged off, logged back onto voidpet with my discord account and then i got this (see attached) screen
![7AE7C86B-8CEC-41B6-9995-89DAE563D02B](https://user-images.githubusercontent.com/104480571/165655111-13066f94-f54c-4aff-ab18-cf386fc885ee.png)
i tried again on google, duckduckgo, safari, logging off and on, refreshing, waiting and nothing seems to fix this…

Did i just get shadowbanned???

(my ign is darklight999 and discord is darklight999#7895)

followup would be much apreciated! have a nice day

**Comment by benawad** [comment]
You probably hit the rate limit, you'll be blocked for 1 hour. 

Note: if you are spamming with a script/bot, there's bot detection that will permaban your account.
