### ISSUE TITLE
Too many wild voidpets on one map

### ISSUE THREAD

**Issue by UnknownEmotions** [voidpet/bugs#542]
**Describe the bug**
When I went into Ghost Road I found that there were 9 wild lonelies instead of 3

**To Reproduce**
Steps to reproduce the behavior: (I’m not sure if it was random or if this will actually work)
1. Go to Somewhere Park
2. Fight some wild voidpets
3. Go back down to Ghost Road quickly
4. See bug(?)

**Expected behavior**
I expected to see the regular 3 voidpets that appear on each map

**Video or Screenshots**
![D39A33D4-965C-4AC3-A7D4-18DC7EEA635E](https://user-images.githubusercontent.com/104575265/165767428-e8ab8f59-38d7-4780-88bf-bd19ab7531a7.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 15.4.1
 - Browser: Safari
 - Version: 15

**Additional context**
It may be because I’ve had the tab up for a while (about a week), or because at the time I was on finicky Wi-Fi

**Comment by YeenOnABean** [comment]
That's called a raid, it's a feature not a bug
