### ISSUE TITLE
Users Pages Not Showing

### ISSUE THREAD

**Issue by pastelunicorneater** [voidpet/bugs#545]
**Describe the bug**
I'm not sure if the not being able to see users pages while not logged in part is intentional or not, but any time I try to pull up a users voidpet page while not logged in, it returns an error.

**To Reproduce**
1. Go into incognito mode or log out of voidpet
2. Go to voidpet.com/*any username*
3. See error

**Expected behavior**
Before 0.13.0 it was possible to go to users pages and see them as you still can when you're logged in even when you weren't logged into voidpet.

**Video or Screenshots**
![image](https://user-images.githubusercontent.com/104607739/165877353-a96b8e0b-ff26-450e-bd92-200df31a1883.png)
The error and page that shows up when trying to view a users page when not logged in.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 100.0.4896.127

**Comment by benawad** [comment]
fixed
