### ISSUE TITLE
Cannot read properties of null (reading 'getAvatarItems')

### ISSUE THREAD

**Issue by battboxx** [voidpet/bugs#549]
The hair choices are no longer showing up in String's Workshop and whenever I try to buy rice or containers I get the message "Cannot read properties of null (reading 'getAvatarItems')" at the top

**Comment by battboxx** [comment]
To Reproduce Steps to reproduce the behavior:

Go to 'String's Workshop'
Click on 'Craft'
See error
A red banner should appear at the top of the screen with "Cannot read properties of null (reading 'getAvatarItems')" written on it

![image](https://user-images.githubusercontent.com/93595818/165989102-88bd00af-99bc-4cc2-b852-3ce22029c9ad.png)


Desktop (please complete the following information):

OS: [e.g. iOS]
![image](https://user-images.githubusercontent.com/93595818/165989534-c94bf868-1dff-4fd3-9fdf-8620071055a2.png)

Browser chrome
Version 100.0.4896.127 (Official Build) (64-bit)

**Comment by benawad** [comment]
does refreshing fix it for you?

**Comment by benawad** [comment]
should be fixed now

**Comment by battboxx** [comment]
> should be fixed now

Thank you, the part about buying containers and rice is fixed but the purchasable hair choices are still no longer showing up

**Comment by benawad** [comment]
Check the avatar editor, we moved it there

**Comment by battboxx** [comment]
oh! thank you and sorry
