### ISSUE TITLE
Cannot Complete Poki Quest

### ISSUE THREAD

**Issue by magpiemid** [voidpet/bugs#552]
**Describe the bug**
The quest to "Stop Poki" is the only quest left for me to do to move forward, but I no matter how much I try I can't find Poki. I have defeated all of the "uncatchable" characters in case something happens after that, but I still have had no luck. 
**To Reproduce**
I'm not sure there is a specific way to replicate this bug, nor am I sure if this specific thing is happening for others in the first place.

**Expected behavior**
I expected that, once I accepted this quest, that I would find Poki under the pavillion as described. After I attempted that, I defeated all of the "uncatchable" characters, as I had read someone else saying you had to defeat them to activate a ladder, so I expected the ladder to appear for me to complete this quest.
**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Samsung S22 Ultra
 - OS: [e.g. iOS8.1] not certain
 - Browser [e.g. stock browser, safari] Chrome
 - Version [e.g. 22] also not certain

**Additional context**

**Comment by GleamGar** [comment]
basically to find poki you need to go into the pavillion basement and then kill everything inside then a ladder will appear and then it takes you to pavillion basement 1 then rinse and repeat until you get to pavillion basement 4 then poki will be there

**Comment by magpiemid** [comment]
ah thank you! :D didn't realize I could tap the pavillion lol
