### ISSUE TITLE
voidpet giga issue

### ISSUE THREAD

**Issue by KitApparently** [voidpet/bugs#553]
I accidentally signed up for giga twice, and so I cancelled one of the subscriptions but kept the other- I was charged for giga this month but I don't have any of the features anymore?
![Screenshot_20220429-145308_Firefox](https://user-images.githubusercontent.com/104652470/166060590-a0657ea3-0ef3-412b-8941-d6cbfd0867df.jpg)
![Screenshot_20220429-145433_Gmail](https://user-images.githubusercontent.com/104652470/166060609-32797c75-7e6b-4ba0-91da-92dcc2cdd1ab.jpg)
No creature bounce and etc

**Comment by benawad** [comment]
Fixed and refunded for the duplicate payment
