### ISSUE TITLE
Guild Members hair color

### ISSUE THREAD

**Issue by Cacticusi** [voidpet/bugs#554]
When in the guild member screen guild members with the same type of hair of your avatar will also have the saim hair color.
This changes whenever you put a new color on.
![image](https://user-images.githubusercontent.com/96020368/166083885-7e087bcc-5d7c-4c40-b754-4e2fec2fa189.png)
![image](https://user-images.githubusercontent.com/96020368/166083929-422c1fe4-6974-4828-8db4-c8ce0cf63864.png)
Not a big bug just thought I would report it

**Comment by DragonWyvryn** [comment]
I have also seen this bug. Pics below. This also affects the void matter color.
![GlitchHair2](https://user-images.githubusercontent.com/63828437/167327247-157a5fba-8b09-4cbf-b3e4-88cbd684fbb4.png)
![GlitchHair1](https://user-images.githubusercontent.com/63828437/167327249-9b979383-7a74-47ca-9a9c-e51de0eb2324.png)
