### ISSUE TITLE
The arrows apperd 

### ISSUE THREAD

**Issue by ImPaRiUos** [voidpet/bugs#556]
**Describe the bug**
The arrows apper while catching and it dosent let me catch and now I can’t do anything 

**To Reproduce**

**Expected behavior**

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by benawad** [comment]
should be fixed now
