### ISSUE TITLE
Everytime I click "Explore" a "click me" button appears

### ISSUE THREAD

**Issue by Pr3st0nn** [voidpet/bugs#557]
**Describe the bug**
So,everytime I try to click explore when I log into voidpet,a screen that says "something went wrong,press this button to reset your state" appears with a "Click me" button under. Everytime I click the button,nothing happens
**To Reproduce**

**Expected behavior**
When I clicked the button,I thought the screen would reload and everything would go back to normal

**Video or Screenshots**
![Screenshot_20220430-002538](https://user-images.githubusercontent.com/104437527/166093796-0f7e03c1-a6f8-4faa-ba46-e0166ce4c7c3.png)

**Desktop (please complete the following information):**
 - OS:Chromebook
 - Browser:Chrome
 - Version:N/A

**Smartphone (please complete the following information):**
 - Device:Samsung
 - OS:LGK51
 - Browser:Google
 - Version:11

**Additional context**

**Comment by benawad** [comment]
What's your voidpet username?

**Comment by Pr3st0nn** [comment]
> 

Pr3st0n

**Comment by benawad** [comment]
can you try pushing the button again now and see if it works for you?

**Comment by Pr3st0nn** [comment]
> can you try pushing the button again now and see if it works for you?

It works now,thank you!
