### ISSUE TITLE
Missing Quests

### ISSUE THREAD

**Issue by mothnmoon** [voidpet/bugs#560]
**Describe the bug**
I'm not actually sure if this is a bug or not, if not I apologize! I've seen a lot of people do both the poki and dandelion quest. I kinda happened to find Poki on my own and defeated it already then found out about the quest afterwards, same with the dandelion one. It hasn't come up for me at all yet !

**To Reproduce**

**Expected behavior**
I kept going Cogito and the other npc yet nothing is shown. I have nothing in my quest log as well.

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser: Opera, using Google for search engine
 - Version (Game ver is the most current one)

**Smartphone (please complete the following information):**
 - Device: [Galaxy S20 FE 5G]
 - OS: [Android 12]
 - Browser [Google Chrome]
 - Version [Most recent ver.]

**Additional context**
N/A

**Comment by benawad** [comment]
Look around the institute and you should be able to find them
