### ISSUE TITLE
Explore buttons not working

### ISSUE THREAD

**Issue by nancydoan** [voidpet/bugs#561]
I'm on chrome book, and when I click on explore I'm not able to click on the "call out for help" or "go back" buttons, but there's arrows on top of them that I can click on but don't do anything. 
![Screenshot 2022-04-30 10 25 56 AM](https://user-images.githubusercontent.com/92058924/166115962-64b16d74-f77a-4714-aabd-f59756460818.png)

**Comment by benawad** [comment]
make sure your on the latest version, it should be fixed now https://voidpet.com/o/version
