### ISSUE TITLE
Starter Pet Not Counted in Pet Log

### ISSUE THREAD

**Issue by smlchrry** [voidpet/bugs#563]
**Describe the bug**
Starter pet is not included in the pet log. If you have not count the same emotion, it shows 0 caught, and if your starter is a vivid, it doesn't show in the correct square (mine is an anxious phantom). May not be noticeable if multiple of the same pet have been caught.

**To Reproduce**
Go to pet log, chose your starter pet emotion.

**Expected behavior**
I thought the starter would show in the pet log.

**Video or Screenshots**
![image](https://user-images.githubusercontent.com/104696492/166121457-05249914-39f0-4b56-a4bd-2d80b291a13b.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by yellowkryptonite** [comment]
Also does not show evolution
![photo_2022-05-01_21-31-54](https://user-images.githubusercontent.com/48806491/166171437-df16e376-2ee6-48e1-a744-21cf4ecce2f3.jpg)
![photo_2022-05-01_21-31-54 (2)](https://user-images.githubusercontent.com/48806491/166171438-66b19a21-b7ea-4b1b-b273-108a72b0a20f.jpg)
s

Cellphone :
OS: Android
Browser: Chorme

**Comment by benawad** [comment]
starters not counting is intended
