### ISSUE TITLE
Game lags after moving between a few different areas

### ISSUE THREAD

**Issue by jpj46** [voidpet/bugs#564]
**Issue:** 
When I am exploring the map and I transition to different areas, after a little bit the game will start to lag. This happens for every "new" area I visit before the lag starts (for example, if I start without lag in the Institute and move north towards Ghost Road and to Something Park, each area along the way may slow down the game. I call them "new" areas because they haven't been visited since resolving the lag issue). The way I resolve this is through either reloading the game or catching/fighting a voidpet. I have attached a video in which you can see the issue occurring. This also shows the games performance returning to normal after an interaction with avoid pet (scaring away does not fix it). These are the only ways that I have found to restore the game's performance after it starts to slow. The game does start to slow down once I reach the new area in my video, but it does occur in any area. I also press the navigation arrows fairly quickly in the video, but this is not the issue either because I have had it happen when I am pressing the navigation arrows slowly.

**Environment:** 
![Screenshot_20220430-140837_Chrome](https://user-images.githubusercontent.com/48301533/166122789-2223f006-ee1d-4559-9063-da25b2682e43.png)

**Steps to replicate:**

1. User should have an existing voidpet account and have access to the game
2. User should be logged in and on the map (Explore)
3. User should press the navigation arrows to change areas
4. User will notice after a few transitions to different areas that the game speed slows down, which increases with each subsequent area visit

**Comment by jpj46** [comment]
Had issues attaching video, here is a link to it: https://file.io/qJPw0NQ0Lkpb

**Comment by benawad** [comment]
I changed it so animation lag is reset on location change
