### ISSUE TITLE
Giga and didnt pay

### ISSUE THREAD

**Issue by rubynia** [voidpet/bugs#565]
I wanted to buy Giga with my card, and when I clicked to buy it, it refused my card.
So I basically gave up and didn't try to fix it. Later I got an email that the purchase failed.
Later when I logged into voidpet I saw that I had Giga. I checked my bank account and no money was removed.
My name on Voidped is "Rubynia" so you can remove my subscription..

**Comment by benawad** [comment]
thanks for being honest, fixed
