### ISSUE TITLE
Guild president gives me officer role but I can’t invite

### ISSUE THREAD

**Issue by Lampyridaes** [voidpet/bugs#568]
Howdy! I’m a member of the guild Cult of God Complex Having Gays, and despite being approved as an officer I do not show up with the role on my end nor can I invite others. We’ve tried removing the role from me and readding, I’ve looked at the guild screen on both mobile and desktop, and we’ve also had me leave and rejoin to try and get it to work. I’d really like this to be fixed so I can stop forwarding all the ids I get to the guild president :(

**Comment by benawad** [comment]
I made you an officer
