### ISSUE TITLE
Anxious Army and The spiteful Basement 

### ISSUE THREAD

**Issue by SpickyToadBitch** [voidpet/bugs#570]
I can’t find Poki in Something Park or anywhere around there. I also can’t find any wild anxitys. I’m on an iPhone 11 Pro and I e been trying to complete these quests for like two days pretty intensely. 
![779E8B84-A3D7-47F0-8C4D-D5BD63908E93](https://user-images.githubusercontent.com/104730024/166155839-e5a9d606-c228-4cc0-85c6-1258cdfbed6d.png)
It also won’t let me progress until I complete these…

**Comment by benawad** [comment]
try asking in the discord for help https://discord.gg/voidpet
