### ISSUE TITLE
Opponents attacks heal your pet upon switching pets

### ISSUE THREAD

**Issue by MelbearX** [voidpet/bugs#571]
After switching your void pet out in battle, the damage from the opponents attacks heal your voidpet

**Comment by Liamdapotato** [comment]
I thought too but i think it’s cus when u change voidpet the hp bar updates itself by going higher when being attack (that is why u still have less than 100%). In simple the pet u chose has more hp than the one u switched with so when it updates itself it looks like it’s healed. If I’m thinking about the same thing that I thought too
