### ISSUE TITLE
Tons of Lonlies

### ISSUE THREAD

**Issue by patfr8** [voidpet/bugs#572]
A lot of lonlies appeared out of nowhere and there are like 15 of them in Ghost Road, it was funny to see honestly

**Comment by Uuscid** [comment]
Yeah, I had the same bug. [Screen Shot as well]
<img width="1103" alt="Screen Shot 2022-05-02 at 11 19 41 AM" src="https://user-images.githubusercontent.com/104780623/166261456-f37b48e7-6b4a-4543-a3e4-a94d3048e8fd.png">

**Comment by benawad** [comment]
feature
