### ISSUE TITLE
It won’t allow any of my void pets to go past level 9

### ISSUE THREAD

**Issue by Angelbitch1417** [voidpet/bugs#577]
I’ve tried a couple different ways but every time it says I earned xp it doesn’t show up in the progress bar 
![40A97BCF-1CD9-4A41-9148-4A8276B96AEB](https://user-images.githubusercontent.com/104746387/166406606-414b15a8-ec36-4538-9c39-fd687b9fff5c.png)

**Comment by benawad** [comment]
Level cap is currently 9, we will be raising it soon
