### ISSUE TITLE
Stuck at lvl 9 pets

### ISSUE THREAD

**Issue by rueroo3** [voidpet/bugs#583]
I have gotten a few of my pets to level nine but it seems to be stuck there. I was thinking maybe it just takes extra points to show, but it’s been awhile. 
Still love the game though! 
**Smartphone (please complete the following information):**
 - Device: iPhone 11

**Comment by Stairintothevoid** [comment]
I've had this issue as well, but maybe they just havent added in further levels yet

**Comment by benawad** [comment]
level 9 is the current cap, we will be increasing it in the future
