### ISSUE TITLE
When doing the "collect 10 pink dandelions" quest you become unable to collect a reward even after completion

### ISSUE THREAD

**Issue by Stairintothevoid** [voidpet/bugs#585]
**Describe the bug**
Even after you have collected 10 pink dandelions it will tell you that you don't have enough dandelions
**To Reproduce**
1. Collect the 10 pink dandelions
2. Speak to the mint haired npc with the pink dress 
3. choose which reward you want, and click complete
4.You get a red notification at the top of your screen telling you that you don't have enough pink dandelions even if you do have the correct amount of pink dandelions

**Expected behavior**
The quest is supposed to let you choose 1 of 3 flower hats but it will not let you claim your reward after completing the quest 

 - Chrome

**Comment by benawad** [comment]
make sure you didn't put some on your pets
