### ISSUE TITLE
Dead end quests

### ISSUE THREAD

**Issue by Momo8510** [voidpet/bugs#586]
Can’t complete quest to collect daggers, after I collected 4 no new ones have appeared even though I’ve defeated about 20 spites at this point. This quest doesn’t even show up on my log.

In addition I can’t find Poki. I defeated all the spites in the basement and the quest hasn’t completed. 

I’m on an iPhone 13

**Comment by benawad** [comment]
What's your voidpet username?

**Comment by Momo8510** [comment]
LightShadow

**Comment by benawad** [comment]
Looks like you completed the dagger quest, for Poki try asking in the discord for strategy
