### ISSUE TITLE
every time i press play with voidpet it comes up with this

### ISSUE THREAD

**Issue by Cubiipusad** [voidpet/bugs#59]
![image](https://user-images.githubusercontent.com/83727352/152066925-0bfe9f40-4c79-4f0c-9b6f-c77461ac0a22.png)

also when i try to learn more it comes up with the same thing
here's the link, if its important at all https://voidpet.com/o/pet/b3e1b78e-90e8-433f-bf51-182e6b906bf2/settings

**Comment by TMShader** [comment]
The site is currently down, please wait a few minutes and try again

**Comment by benawad** [comment]
plz reopen if this continues to happen
