### ISSUE TITLE
animations

### ISSUE THREAD

**Issue by sheepboy78** [voidpet/bugs#590]
**Describe the bug**
I'm not sure if this is a feature or not but the animations of my caught pets aren't showing up? I check on them frequently and fight with them a lot, but I don't see their animations other than their fighting and playing with them. I can see wild pet's animations just fine, but no my caught ones.

**Desktop (please complete the following information):**
 - OS: Chromebook
 - Browser: Google
 - Version: Latest I believe

**Comment by benawad** [comment]
That's a giga feature https://voidpet.com/o/giga
