### ISSUE TITLE
XP bug?

### ISSUE THREAD

**Issue by angel-hauraki** [voidpet/bugs#591]
Im aware that the level/xp cap is level 9. But all of my voidpets arent leveling up. I will get given xp but it doesnt contribute to my pets level. This is for all of them. I will have some pets st level 5 and when I supposedly gain xp, there is no contribution. Not even a small movement.

Sorry if this isnt a bug or has already been resolved. Thank you :)

**Comment by squidee100** [comment]
Can you send an image of the pause menu before a fight and after a fight?

**Comment by angel-hauraki** [comment]
Sure thing! 


![Screenshot_2022-05-10-21-20-38-45](https://user-images.githubusercontent.com/103228712/167617500-d14dbcff-3f02-4d50-a381-a12a3d3bbead.jpg)

![Screenshot_2022-05-10-21-21-14-96](https://user-images.githubusercontent.com/103228712/167617469-6857ae2e-00ea-4acf-bb4c-22da6683efab.jpg)

Let me know if it is a bug, or if my eyes are playing tricks on me and that the xp bar is subtly moving up. :).

**Comment by angel-hauraki** [comment]
Sure thing, I just tried to post it but accidentally posted the wrong thing. One moment :)

**Comment by angel-hauraki** [comment]
For this specific situation, only one of the voidpets has gained xp (in the screenshot). In some cases all of my voidpets dont gain xp. In other cases only one does.

![Screenshot_2022-05-10-21-24-28-26](https://user-images.githubusercontent.com/103228712/167618207-f7f8db46-1b1e-4253-8f1e-3cc640dc6359.jpg)

![Screenshot_2022-05-10-21-25-50-95](https://user-images.githubusercontent.com/103228712/167618223-cfde940f-3a90-449f-8c1e-cf113a505ddc.jpg)


Let me know if it turns out I just couldnt notice the change/gain in xp or if it is a bug. If it isn't a bug, sorry for wasting your time :)

**Comment by angel-hauraki** [comment]
Sorry a made a typo I meant 2* voidpets

**Comment by squidee100** [comment]
As you said, 2 voidpets gained XP but Banana didn't gain any, which is obviously odd.
Might have to wait for Ben to check out this bug. Please add to this issue if you have any updates.

**Comment by angel-hauraki** [comment]
I will :) thank you. As I said before. Sometimes i won't ever get xp gain and other times I will. I have noticed that when I do get xp gain is when I log in and out of the game a few times and then it will start working.

**Comment by benawad** [comment]
If a pet dies in battle, it doesn't get XP
