### ISSUE TITLE
Shrink Attack

### ISSUE THREAD

**Issue by CaptainOnlySophrie** [voidpet/bugs#593]
Everytime my voidpet attacks both my voidpet and the wild pet shrink. Although funny, it has started to become troublesome as it has gotten so small during a battle you could no longer see them. It does reset after every battle, so once you win or lose the next battle they will be regular size then shrink after attacking. Hope you guys figure it out. Good luck and have a nice day.

**Comment by CaptainOnlySophrie** [comment]
> could you show a video

I cannot since it is on my phone, I have no way of recording it. I apologize

**Comment by CaptainOnlySophrie** [comment]
> > could you show a video
> 
> I cannot since it is on my phone, I have no way of recording it. I apologize

I can take a screenshot here ya go
![Screenshot_20220513-093935_Firefox](https://user-images.githubusercontent.com/105299795/168296399-c14232b5-9010-4330-8e43-32f15fd9b5dd.jpg)

**Comment by CaptainOnlySophrie** [comment]
New screen shot, this bug is still there
![Screenshot_20220516-072830_Firefox](https://user-images.githubusercontent.com/105299795/168583498-27f2c5bf-5b2f-4da2-b831-7be159748020.jpg)

**Comment by benawad** [comment]
What browser is that?

**Comment by CaptainOnlySophrie** [comment]
> What browser is that?

Firefox mobile version

**Comment by lilpuppers** [comment]
![Screenshot_20220516-143049_Firefox](https://user-images.githubusercontent.com/105671014/168659445-31ff2bde-8a97-4bfe-89ed-71383dff98d5.jpg)
This happens to me every time I navigate away from the page on Firefox (mobile) for any period of time. Both get smaller and smaller until they are invisible (attached image).

**Comment by benawad** [comment]
Pushed an update that should fix this, try refreshing and battling again

**Comment by CaptainOnlySophrie** [comment]
Thank you wonderful people for fixing this!

**Comment by lilpuppers** [comment]
> 

Thank you so much for the fast fix!
