### ISSUE TITLE
9 Sprites On A Page

### ISSUE THREAD

**Issue by SkylinerWalker** [voidpet/bugs#594]
**Describe the bug**
There are 9 lonelyone sprites on my page for ghost road.
**To Reproduce**
I am unsure how to reproduce this behavior. 
**Expected behavior**
I expected only 3 sprites to appear as per usual. 
**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.
![Screenshot_20220512-085606](https://user-images.githubusercontent.com/105439446/168093664-3a1b38e1-2283-4bca-a290-4dcc4873e42a.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Motorola G Stylus 5g
 - OS: [e.g. iOS8.1] Unsure
 - Browser [e.g. stock browser, safari] Chrome
 - Version [e.g. 22] 11 

**Additional context**

**Comment by benawad** [comment]
That's a feature

**Comment by SkylinerWalker** [comment]
Okay thank you!
