### ISSUE TITLE
Defeating Poki too early makes mission impossible to complete

### ISSUE THREAD

**Issue by TheLordZee** [voidpet/bugs#597]
**Describe the bug**
One of the quests Char gives has you going to the Pavillion Basement to defeat a Spite named Poki. However, if you go to there before you get the quest and fight Poki, Poki doesn't respawn and you can't complete the quest once you do get it

**To Reproduce**
1. Go to the Pavillion Basement before you get the quest from Char
2. Fight and defeat Poki

**Expected behavior**
Either Poki shouldn't spawn prior to getting the quest or it should respawn

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave Desktop

**Comment by benawad** [comment]
Poki should respawn, did the pets before it respawn?

**Comment by TheLordZee** [comment]
Never mind. I didn't realize there was multiple layers to the basement and Poki was on the bottom layer.
