### ISSUE TITLE
Envy

### ISSUE THREAD

**Issue by Gh0stiiex** [voidpet/bugs#6]
The envy pet isn’t working at all it seems. Idk if that’s game design or an actual error

**Comment by benawad** [comment]
in what way is it not working?

**Comment by desidient** [comment]
There isn't a way to play with Envy/ interact with them

**Comment by maverick-dev-55** [comment]
@desidient there is no way to interact with any pet at all, the game isnt finished

**Comment by desidient** [comment]
@maverick-dev-55  I had just checked the discord server again right before you mentioned it haha but thank you!

**Comment by benawad** [comment]
coming soon
