### ISSUE TITLE
catched variant not registering on pet log

### ISSUE THREAD

**Issue by jspeh1** [voidpet/bugs#600]
i caught a ethereal but its not on the pet log
![image_2022-05-15_205625990](https://user-images.githubusercontent.com/105592354/168474005-093fd771-f05a-471e-9e60-7280de0f134e.png)
![image_2022-05-15_205645268](https://user-images.githubusercontent.com/105592354/168474016-74baaa43-4d3c-4c58-9962-db12129bc323.png)

**Comment by benawad** [comment]
Try changing the dropdown to sonder
