### ISSUE TITLE
My voidpets won't bounce when they're meant to

### ISSUE THREAD

**Issue by IdkwhyImherehelpme** [voidpet/bugs#602]
Iv been in this game since u only had one pet and all u could do was cuddle it and the other actions ect. so I should have the bouncing void pet thingy where your pet bounces, but I don't have it. My pets just stand still in battle . I don't have giga. I have told a few other people with the game about this and they are the ones that alerted me of this problem. Can you fix this please?

(My ingame username is Applecrumbl. If you need to contact me via discord my user is duckthedog and my nickname on the void pet fanserver is Void of Voids <3)

Thank you!!
If you need anymore details please contact me

**Comment by benawad** [comment]
updated
