### ISSUE TITLE
Quest will not complete even after finishing it

### ISSUE THREAD

**Issue by Milkie2** [voidpet/bugs#603]
I have a quest on talking to The Great Friend, and I did what I was told to do, talking to the Great Friend and answering the question. However, the quest was still considered incomplete. I have tried multiple times, but it was still not completed. I am not sure how to reproduce the bug and I have been informed by a friend that it was not normal. ^

![image](https://user-images.githubusercontent.com/105619590/168514652-7de8b647-4b34-455c-a3d1-c4543d6b903d.png)

![image](https://user-images.githubusercontent.com/105619590/168514677-6b2b70f7-b203-49be-b81f-29a6df56939a.png)

![image](https://user-images.githubusercontent.com/105619590/168514690-9645ae29-f440-42db-bcf8-4412d3a0b9a2.png)

**Comment by benawad** [comment]
try it again, just fixed it
