### ISSUE TITLE
Esse assignment #2 not updating

### ISSUE THREAD

**Issue by SammieJxne** [voidpet/bugs#604]
**Describe the bug**

Esse assignment #2 is not updating the kill count for 30 wild spite kills. It got up to 20/30, and is frozen there no many how many spites I kill. 

**To Reproduce**
Get to Esse’s second quest, once you get to 20/30 spite kills, it will not update further

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 iPhone 12 Pro Max, newest iOS and game versions 

**Additional context**

**Comment by benawad** [comment]
should be fixed now
