### ISSUE TITLE
Dark spiral bug

### ISSUE THREAD

**Issue by frickity-frack** [voidpet/bugs#606]
**Describe the bug**
I was in the 'see red' thingy, and after i had defeated the three voidpets on the screen (i was on like level 11 or something), and I opened the memory but the dark spiral that takes you to the next level was still on screen

**To Reproduce**
1. Go to something park pavillion, and trigger the 'dark spiral has appeared' event
2. Enter it, and defeat all three voidpets
3. when dark spiral reappears, go into memory

**Expected behavior**
It shouldn't be there

**Video or Screenshots**
![image](https://user-images.githubusercontent.com/103015157/168594040-203a4508-692c-4528-9c26-dcb65fa91279.png)

**Desktop**
 - Windows
 - Chrome

**Comment by benawad** [comment]
fixed
