### ISSUE TITLE
Application error screen

### ISSUE THREAD

**Issue by Chinzillers** [voidpet/bugs#607]
When I press explore on my home page it takes me to a white application error on my screen. This is happening on my phone and my laptop and it's been going on for a few hours now and I can't play. I've tried different browsers?

**Video or Screenshots**
![Screenshot_20220516-000655_Chrome](https://user-images.githubusercontent.com/105654926/168614415-d883fab7-dd0b-41f1-98d5-3b72ce725579.jpg)

**Desktop (please complete the following information):**
 - OS: android
 -  Browser: chrome and edge

**Smartphone (please complete the following information):**
 - Device: Samsung s21
 - OS: android
 - Browser

**Comment by benawad** [comment]
try refreshing

**Comment by benawad** [comment]
I just pushed an update that should fix this
