### ISSUE TITLE
The game wont let me continue and get a body

### ISSUE THREAD

**Issue by Athovik** [voidpet/bugs#610]
I started the game 20 minutes ago got anger and then started to play with him (I named him diablo) after almost maxing out all stats I realized I could explore so I did that read until I got to this page 

![Screenshot_20220516-114901_Chrome](https://user-images.githubusercontent.com/105671627/168661720-ef55244d-b438-4361-adec-874e5ae0de83.jpg)

It would not continue past that page I tried restarting my device and the web page, I even deleted my account and made a new one with envy (again named diablo) I maxed his stats completely this time tried exploring and it still will not move past this point.

**Comment by benawad** [comment]
should be fixed now, try refreshing
