### ISSUE TITLE
Voidpets becoming super small during battle

### ISSUE THREAD

**Issue by Manguruneza** [voidpet/bugs#611]
hi! i do hope this is the right way to do this, and i hope its clear enough. whenever battling a voidpet, clicking on a battle move causes the screen to become smaller. it might be a me issue, but i am unsure as ive tried to resize my screen/zoom size. it happens with pretty much every pet :(
- update, after i wrote this i found out it actually just happens whenever you click anything in battle

1. Go to a wild voidpet
2. Click on battle
3. select a move or two
4. the voidpets/their info above and healthbars become small or very small

i expected it to be normal as it how was, just selecting a move and having it normal.

linked proof!
![image](https://user-images.githubusercontent.com/105672709/168667084-fcd70d62-1983-424b-aa56-75ae625db223.png) before/entering battle

![image](https://user-images.githubusercontent.com/105672709/168667163-588e040a-414f-4711-abe3-4e7b7aaa48cc.png)
 after selecting

a few other times - 
![image](https://user-images.githubusercontent.com/105672709/168667375-6b646025-9601-45e0-a679-7a70aaba2743.png)
![image](https://user-images.githubusercontent.com/105672709/168667571-a7eb3bba-db4d-4632-b95d-bae518199f42.png)
![image](https://user-images.githubusercontent.com/105672709/168667983-0680b881-7459-4b95-9a1f-9729a3f76d1b.png)
![image](https://user-images.githubusercontent.com/105672709/168668044-8b446ef9-bfb9-4fed-a176-36a473fd4c7e.png) i switched to my dinosaur during battle....... why is the lonely so small :sob: 

 - OS: Microsoft windows 10 home
 - Browser: Firefox
 - Version: 100.0.1

i do hope this helps, or if theres any way to fix it. thank you!

**Comment by benawad** [comment]
I pushed an update for this, if you open voidpet in a new tab does this still happen for you?

**Comment by Manguruneza** [comment]
It seems that its been fixed! Thanks so much
