### ISSUE TITLE
Second voidpet 'grow-up animation' doesn't play

### ISSUE THREAD

**Issue by squidee100** [voidpet/bugs#619]
**Describe the bug**
When two voidpets grow-up at the same time (after a fight, quest, etc), the first 'grow-up animation' will play, but when clicking 'next' at the bottom of the modal, the second voidpet will appear as if the animation already finished.

**To Reproduce**
1. Level-up two voidpets at the same time.
2. Watch entire 'grow-up animation'
3. Click 'next' button
4. Second voidpet's animation won't play and will appear already grown up

**Expected behavior**
When clicking 'next' after watching the first 'grow-up animation', the second voidpet should play an animation showing it growing up.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome v101.0.4951.54

**Comment by TheTrickyNicky** [comment]
Its never played the grow-up animation for me either. I just assumed thats how it was.
