### ISSUE TITLE
Going to explore option causes screen to be partially covered

### ISSUE THREAD

**Issue by SeventyFox92475** [voidpet/bugs#62]
Device: iPhone SE 2020
Browser: Safari
Issue: When coming back to the pet from the explore option, there is a strip of gray that covers part of the screen
Attachment:

https://user-images.githubusercontent.com/45300419/152070144-68e8c28e-c044-46b5-bd95-c9b56df8e08d.MP4

**Comment by benawad** [comment]
fixed
