### ISSUE TITLE
Rarity chart shrinked

### ISSUE THREAD

**Issue by reeessh** [voidpet/bugs#623]
When I go to the Landing, the chart that is supposed to show how rare a vivid variant is, i can only see a tiny square.

**To Reproduce**
1. Go to Landing
3. Scroll down to 'For masters only'

**Expected behavior**
The chart is in a legible size.
**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by benawad** [comment]
What device are you on?

**Comment by benawad** [comment]
jk, fixed
