### ISSUE TITLE
Minor Animation Bug in Avatar Customization

### ISSUE THREAD

**Issue by poisongecko** [voidpet/bugs#626]
**Describe the bug**
When I am customizing my avatar, the animations will stop and start.

**To Reproduce**
1. Go to Avatar.
2. Watch as the animations stop and start when you add something to your avatar.

**Expected behavior**
I expected that the animations would continue indefinitely.

**Video or Screenshots**

I would attach a video but for some reason Github won't let me attach it :(

**Comment by benawad** [comment]
In the picker we only show the animation for 3 seconds
