### ISSUE TITLE
ghost road spawn problem

### ISSUE THREAD

**Issue by MocaNFriends** [voidpet/bugs#627]
**Describe the bug**
sometimes when i go to the something park , i would come across ghost road having 9 lonely in one time . 
**To Reproduce**
i cannot seem to " summon " the bug , it was by chance and we would just see 9 lonely on the ghost road floating .

**Expected behavior**
there should be only 3 , and as usual .

**Video or Screenshots**
i can ' t screenshot somehow , still new to the computer .

**Desktop (please complete the following information):**
 - thinkbook
 - google
 - i don ' t know  help -

**Additional context**
the bug is just weird spawning chances and i have came across this scene three times by now .

**Comment by benawad** [comment]
that's a feature
