### ISSUE TITLE
Voidpet Idle Animations in Battle 

### ISSUE THREAD

**Issue by RainGoYeet** [voidpet/bugs#629]
**Describe the bug**
When battling another Voidpet, the player's pet doesn't have an idle animation, while the opponent does. (Ex. An enemy anxious tapping and moving around like they do, while a player's anxious is completely still) 

**To Reproduce**
1. Find and initiate a fight with a void pet
2. Watch the idle animations of both the tamed pet and the wild pet

**Expected behavior**
All participants of a battle (player's pet and opponent pet) should have an idle animation and shouldn't just be standing still 

**Video or Screenshots**
https://photos.app.goo.gl/Sx4cmw6sp4ohGMhP8

**Smartphone (please complete the following information):**
 - Device: [Moto g pure] (?)
 - OS: no clue 
 - Browser [Google chrome]
 - Version [not sure- latest]

**Additional context**
It's possible that this is an issue only I am experiencing, but I don't have anyone to compare with

**Comment by benawad** [comment]
That's a giga feature https://voidpet.com/o/giga
