### ISSUE TITLE
"Application Error" when checking voidpet's drawing

### ISSUE THREAD

**Issue by Duckysss** [voidpet/bugs#63]
Whenever I choose to draw with my void pet and "check what they drew" it redirects me to this error page.

![Screenshot_20220201-153150_Chrome](https://user-images.githubusercontent.com/98856598/152070419-507514d3-50a5-4c37-b4e7-f7c0742e8d44.jpg)

**Comment by benawad** [comment]
What browser/phone are you using?

**Comment by Duckysss** [comment]
galaxy s10+.

**Comment by benawad** [comment]
I pushed an update, could you give it another try

**Comment by Duckysss** [comment]
It works now! :)
