### ISSUE TITLE
Where to get Pet Containers?

### ISSUE THREAD

**Issue by DucoTte** [voidpet/bugs#633]
After using up the capture containers given at the start, there's no way (or at least no way that I've found) to purchase or earn new ones. 

Maybe I'm just missing something, but I can't figure it out. I've only used a desktop up until now, and I haven't tried to test it on mobile.

**Comment by benawad** [comment]
![918EA9CE-6DC0-462A-87BF-39C28F260ED3](https://user-images.githubusercontent.com/7872329/169721396-e156da3f-5f88-4164-88f1-d06041fddcef.png)

tap on the pizza
