### ISSUE TITLE
Can't log into the game

### ISSUE THREAD

**Issue by RuzhUzhu** [voidpet/bugs#636]
**Describe the bug**
When I open the site, it doesn't show "Login with Discord" button, then "load failed" sign appears

**To Reproduce**
Open voidpet.com

**Expected behavior**
Access to the game

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.
![82399E8B-65F9-4BE7-9777-61AAF33012C0](https://user-images.githubusercontent.com/105927314/169963336-b7432726-1a3a-41f2-979e-46c745e92488.png)

**Desktop (please complete the following information):**
 - 

**Smartphone (please complete the following information):**
 - Device: [iPhone xr]
 - OS: [ iOS15.3]
 - Browser [safari]
 - Version [15]

**Additional context**
I've checked internet connection. Any other site or app works fine

**Comment by benawad** [comment]
Use https://voidpet.com/o/version to make sure you are on the latest version
