### ISSUE TITLE
Pets don't seem to be gaining exp?

### ISSUE THREAD

**Issue by kamiofthemoonsheart** [voidpet/bugs#637]
I don't know what's happening but my pets aren't gaining exp after battles? I know there's going to be a level cap, but they're all level 4? I even put my cursor to the bar to check, but the bar isn't moving. I just want my beloved sad (Spoon!) to get stronger.

 - OS: windows 10?
 - Browser firefox
 - Version ?

**Comment by benawad** [comment]
If a pet dies in a battle it will not get any XP, that could be why it didn't get any. Otherwise, it should be getting XP at the end of each battle (the bar might just move fractionally)
