### ISSUE TITLE
Animation voidpet

### ISSUE THREAD

**Issue by H1emdall** [voidpet/bugs#639]
**Describe the bug**
my voidpet’s don’t have animation but the wild ones do.

**To Reproduce**
1. Enter a fight with a void pet 
2. and you should see no animation for your voidpet

**Expected behavior**
Animation for all voidpets

iOS
safri
 

**Smartphone (please complete the following information):**
 - iPhone 11
 - iOS15.5
 -  safari
 - Current version 

**Additional context**
Just noticed my voidpet wasn’t moving compared to the one I was fighting .

**Comment by benawad** [comment]
that's a giga feature https://voidpet.com/o/giga
