### ISSUE TITLE
Typo at the end of the current "explore" page

### ISSUE THREAD

**Issue by HerbeMalveillante** [voidpet/bugs#64]
When starting exploring (https://voidpet.com/o/explore) , after going trough the mini-story, a paragraph appears saying "**We are working on it**" with the following text : 
`If you have made it this far and are still confused, then congratuations! You’ve made it through the first few features of our early access, which will be updated online whenever we build out new functionality!`

I just spotted that the word "congratulations" is misspelled : it's missing an `l` between the `u` and the `a`.

This is a minor inconvenience as this is just a typo in a probably temporary text, but I just wanted to let you know.

**Comment by benawad** [comment]
fixed
