### ISSUE TITLE
impossible to get containers

### ISSUE THREAD

**Issue by helpsab** [voidpet/bugs#640]
I ran out of containers so when I went to String to craft some, there wasn't the option to do that, there was only the chat and quest option. I can't find any other way to get containers and I need them for most of my quests
<img width="1016" alt="Screenshot 2022-05-29 at 13 19 57" src="https://user-images.githubusercontent.com/106473695/170866035-278cda43-2bf6-46b8-a5ea-04e054003ea9.png">

**Comment by benawad** [comment]
see #633
