### ISSUE TITLE
Pets still show up at the top after removing them from favorites

### ISSUE THREAD

**Issue by InvalidArgumentException** [voidpet/bugs#643]
When trying to remove a pet form the list of favorites, it removes the star but not the pet itself. It will always show up at the top of the list, even after refreshing.

![Screenshot 2022-06-01 at 13 59 04](https://user-images.githubusercontent.com/106672001/171399809-bb62ffe3-72b1-4788-9242-9dc1c4294a23.png)

**Comment by benawad** [comment]
fixed
