### ISSUE TITLE
Ball of Fury Crit Chance Broken

### ISSUE THREAD

**Issue by afisher06** [voidpet/bugs#644]
When I click info on ball of fury as a move it says that it adds 50% to my crit chance, but when I go to use it it does not actually add the visual component of adding to my crit chance. When I click lash out it does display the 6% increase in crit chance after it is played.

**To Reproduce**
1. Fight another voidpet with a pet that can use red chip moves
2. Click on ball of fury
3. Do damage but have no crit chance show up

**Expected behavior**
A visual to appear like the move lash out that the crit chance increased by 50%

**Video or Screenshots**
![image](https://user-images.githubusercontent.com/71358544/171771257-65b4a764-ec6b-4ea7-91a8-0561f812e505.png)
![image](https://user-images.githubusercontent.com/71358544/171771328-e7b6c0fe-a5fb-42d5-a61c-0e104ac4a943.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 - Browser Chrome
 - Version Latest

**Smartphone (please complete the following information):**
 - Device: Android Tablet
 - OS: Latest Android
 - Browser Chrome
 - Version: Latest

**Comment by soupy227** [comment]
The move doesnt add 50% to your crit damage. The move itself has a 50% chance to crit when you use it.
