### ISSUE TITLE
Pride scarves not loading in at all

### ISSUE THREAD

**Issue by soupy227** [voidpet/bugs#646]
I finally got a cosmic scarf, so i go to equip it onto my Sonder. Both the cosmic and rainbow scarf that i had obtained were absent from the menu, nit showing up on my voidpet, and the names for the items were on top instead of underneath. I havnt checked if this is an issue for any vp other than my sonder, though.
![Screenshot_20220603-233240_Chrome](https://user-images.githubusercontent.com/103346963/171979806-669a8053-98ce-420c-bffa-417a3ea549f9.jpg)

**Comment by soupy227** [comment]
I tried this again with my Anger and it did it again. It showed up the same as before, the rainbow and cosmic scarf not loading, so i dont think its an issue that has to do with the one voidpet.

**Comment by benawad** [comment]
Did refreshing or opening voidpet in a new tab fix it for you?

**Comment by soupy227** [comment]
Yep, it fixed itself.
