### ISSUE TITLE
Pride scarfs glitch

### ISSUE THREAD

**Issue by possumcr0ss** [voidpet/bugs#648]
**Describe the bug**
Pretty self explanatory. None of the pride scarfs will load in for me. It'll show the item name as usual but there's no image.

**To Reproduce**
1. Go to 'Memory'
2. Click on any pet
3. Click on neck
4. Select any pride scarf

**Expected behavior**
For the items to load in.

**Video or Screenshots**

![Screenshot_20220605-193129_Samsung Internet](https://user-images.githubusercontent.com/106937704/172080383-92897082-f380-4cd3-a8de-a5acc9fa59b0.jpg)
![Screenshot_20220605-193106_Samsung Internet](https://user-images.githubusercontent.com/106937704/172080385-2165bf0c-9048-469e-b7c3-994642eb22e0.jpg)

**Smartphone**
 - Device: Samsung Galaxy A20
 - OS: Android 
 - Browser: Stock browser

**Comment by benawad** [comment]
make sure you are on the latest version: https://voidpet.com/o/version
