### ISSUE TITLE
skill levels being deducted or not being registered.

### ISSUE THREAD

**Issue by ryufen** [voidpet/bugs#65]
When interacting with the pet, I get messages that say things such as "confidence boosted" but i don't see the changes other than a red circle around the number near the skill. The one time it did work was when serenity went from 10 to 11 but then went back down to 10 out of nowhere. I don't know if this is an intentional part of the game but I just wanted to report just in case.

**Comment by Sikaydah** [comment]
Having this same issue.

**Comment by benawad** [comment]
expected behavior
