### ISSUE TITLE
Duplication of Pets in Memory

### ISSUE THREAD

**Issue by KittyCatastrophe09** [voidpet/bugs#653]
**Describe the bug**
Sometimes pets are duplicated in the memory, at least visually.

**To Reproduce**
1. Go to your memory
2. After load more, I have a duplicate of one of my pets.

**Expected behavior**
No duplicates

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/77755379/173884865-008971a9-d427-48e3-a864-b9d80c53d196.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Microsoft Windows 11 Home
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 102.0.5005.115 

**Additional context**
It is hard to show, but whenever I change a costume for one "Penelope" it updates the other and they have exactly the same stats.
Definitely not a huge deal just wanted to point out that it did happen.

**Comment by benawad** [comment]
Are you able to reproduce this if you refresh?

**Comment by idkanymore6110** [comment]
Example of pet duplication even after refreshing:
https://user-images.githubusercontent.com/109921104/181151666-dd5bc5da-b9f5-40ce-ad72-52f164d52421.mp4

**Comment by benawad** [comment]
@idkanymore6110 can you try it again, I made a change that I think should fix it
