### ISSUE TITLE
Cogito germinate quest won't complete. No pets are dropping Germinate after I've leveled up 11 times

### ISSUE THREAD

**Issue by voidpetlover** [voidpet/bugs#656]
**Describe the bug**
Cogito in the game has a quest where you have to collect two germinate books. I received this quest early on in the game when I was lvl 2 or 3, I haven't been able to complete the quest and I've done many other quests and leveled up to level 13. Is this intended to be this difficult?

**To Reproduce**

**Expected behavior**

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by benawad** [comment]
Hint: you can get skill books from your existing pets.
