### ISSUE TITLE
Char's Checkmate Quest Cannot be Completed

### ISSUE THREAD

**Issue by CosmicSymbols** [voidpet/bugs#658]
**Describe the bug**
Envy pets required for the quest simply will not spawn anywhere in the currently available locations. The only time they are available are in the Seeing Red Portal at Snake Road Void Entrance, but those are uncatchable. Even in the catchable levels every 5 levels or so, Envies will not spawn there. I have been playing for nearly 3 days straight, and have yet to even see a catchable Envy.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Snake Road Void Entrance
2. Click on Seeing Red Portal after defeating all pets
3. Battle until at least the 5th Level
4. No Catchable Envies

**Expected behavior**
No Envies will spawn in any of the catchable levels

**Desktop:**
 - OS: Acer 19044.1766
 - Browser: Firefox & Chrome
 - Version 101.0.1 (FF) / 102.0.5005.115 (C)

**Additional context**
I understand that certain quests are meant to be more challenging than others, but Char's Envy quest has been one of the first quests I got when I first joined a month ago and it is still near impossible to complete without the Envies being able to spawn outside of The Snake Road Seeing Red levels. I have reached up to level 35 in Seeing Red multiple times and there still have not been any Envies in the catchable levels.

**Comment by benawad** [comment]
This is an optional quest that is meant to be very challenging. We may tune this in the future.
