### ISSUE TITLE
Skills not going up

### ISSUE THREAD

**Issue by Monobloc-Chair** [voidpet/bugs#66]
The update just launched, but when it says my pet boosts it's satisfaction or serenity, it doesn't go up. I'd this just me?

**Comment by Sikaydah** [comment]
Happens to me too. Even boosted my satisfaction to 11 last session, back down to 10 when I get back. Bond will not go any higher than it is now, which is just under reaching level 1. For skill levels I have in order top to bottom, 9 9 10 8 7. No matter how long I spend playing with the pet, none of these numbers are changing anymore, and they're even reversing progress if they do change.
