### ISSUE TITLE
Purchasing Item Issue?

### ISSUE THREAD

**Issue by Hydrangea0Petal** [voidpet/bugs#662]
Hi! When playing voidpet for the past few days I haven’t been able to purchase containers or food ever since the auction hall update thingy. Maybe I’ve just missed something or my device is a little old, but I can’t purchase containers or food anymore.

**Comment by benawad** [comment]
Could you record a video of what happens when you try to craft something

**Comment by Hydrangea0Petal** [comment]
I was missing an IOS update and my wifi was slow 😅 everything is fine now.

**Comment by Hydrangea0Petal** [comment]
> Could you record a video of what happens when you try to craft something

I was missing an IOS update and my wifi was slow 😅 everything is fine now. I’m sorry lol
