### ISSUE TITLE
Landing page won’t load. 

### ISSUE THREAD

**Issue by mmacmillan03** [voidpet/bugs#663]
**Describe the bug**
Login page to discord so I can assess the game isn’t loading just shows a blank screen from google, and when I had it saved on my phone as a bookmark it wouldn’t let me place just showed my profile and said I needed to login which wouldn’t let me login
**To Reproduce**

**Expected behavior**

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by benawad** [comment]
make sure you are on the latest version https://voidpet.com/o/version
