### ISSUE TITLE
My Arcane Pain 3, level 12, isn't gaining any XP from battles. I've done 3 in a row and the experience bar hasn't changed.

### ISSUE THREAD

**Issue by MasterCyborg612** [voidpet/bugs#664]
This is before 3 successful battles against Point on the hard difficulty.
![Screenshot 2022-06-30 10 55 56 PM](https://user-images.githubusercontent.com/104277227/176814733-545fd768-130d-49fb-9f14-da43859d98b6.png)

This is after 3 successful battles against Point on the hard difficulty.
![Screenshot 2022-06-30 11 26 33 PM](https://user-images.githubusercontent.com/104277227/176817625-e563436a-ef0f-40c8-b45d-30acf98e6347.png)
**Device**: ASUS 11.6" Chromebook C202SA Series YS02 11.6" 4GB 16GB
**Version:** 0.18.0
**Browser:** Chrome
**I expected it to level them up** and/or add experience to the XP-bar but those results didn't occur.
Please fix, thank you.

**Comment by benawad** [comment]
They are gaining XP, just small amounts
