### ISSUE TITLE
Voidpet level bug (visual?)

### ISSUE THREAD

**Issue by abyssalspire** [voidpet/bugs#668]
**Describe the bug**
Voidpet levels appearing as different numbers in different menus

**To Reproduce**
1. Go to the main menu
2. At the top of the menu, you should see your 3 lead Voidpets and their levels (mine are level 16)
3. Click on any of your lead Voidpets to see their information
4. Their levels appear incorrectly, for example, my level 16 voidpets appear to be level 15

**Expected behavior**
When viewing my Voidpet’s information, I was expecting to see the correct level and stats. I’m not sure if the level bug affects the stats of my Voidpets or not. 

**Video or Screenshots**
If applicable, add a video or screenshots to help explain your problem.

https://user-images.githubusercontent.com/109002136/178123426-d97cb10b-437b-4a35-881d-65112990876c.MOV

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 15.5
 - Browser: Safari
 - Version: Safari 15 (?)

**Additional context**
This bug may be influenced by the server overload due to the latest update

**Comment by benawad** [comment]
fixed
