### ISSUE TITLE
Bond not going up

### ISSUE THREAD

**Issue by Iamsamnow** [voidpet/bugs#67]
I’ve been playing with my voidpet for a while but it’s just stuck. It won’t go up to 1. I’m not sure if this is a bug or meant of purpose but it’s a bit annoying
![C70F51E6-2E64-4FCC-B4A9-26300CE4E1F7](https://user-images.githubusercontent.com/98870173/152105279-ff8f1d03-cf33-43d3-a4e1-e6b0e047540f.jpeg)

**Comment by benawad** [comment]
expected behavior
