### ISSUE TITLE
My Account is Gone

### ISSUE THREAD

**Issue by Mackenzie8452** [voidpet/bugs#670]
I reopened the browser window from the last time I logged in (admittedly, it's been a while because I hit level 14 and there was nothing new to do), and after a few glitches, it told me to login with discord and started me on a new account. I think my username was Kenzie, but I entered my discord (name and numbers) into the new one before having the idea of submitting a ticket. Hopefully my original can be restored?

**Comment by Nuclearsmilz** [comment]
Hi Ben, instead of making another post, i decided to add onto this post as i have the exact same issue.
the page i get is just an empty page with the text "{"message":"Internal Server Error"}"

My account link is supposed to be at https://voidpet.com/chronoblaze

**Comment by benawad** [comment]
@Mackenzie8452 Do you know what else your username may have been? I don't see a `Kenzie` user.

**Comment by benawad** [comment]
@Nuclearsmilz should be fixed now

**Comment by Nuclearsmilz** [comment]
Thanks Ben it's working now!

**Comment by Mackenzie8452** [comment]
It was Kenzie or Kenz? There have been a few updates since the last time I
logged in.

**Comment by Mackenzie8452** [comment]
Hello,

It could have included a 97 (Kenzie97 or Kenz97) as well.

**Comment by benawad** [comment]
@Mackenzie8452 `Kenzie#5758` is the discord associated with the `Kenzie97` user

**Comment by Mackenzie8452** [comment]
Strange. I've only ever had the one account, but I do recognize that one.
I'll see if I can get into it. Thank you!
