### ISSUE TITLE
Avatar/Pet Level

### ISSUE THREAD

**Issue by viocrence** [voidpet/bugs#671]
**Describe the bug**
pet level and avatar level are mixed up

**To Reproduce**
>Go to 'pet menu'
>pets are the same level as your avatar ex: lv 17
>click on pet
>they are their normal level ex: lv 15

**Smartphone**
 - Device: [e.g. iPhone6] iPhone10
 - OS: [e.g. iOS8.1] iOS
 - Browser [e.g. stock browser, safari] safari
 
![4365A66B-B64C-45B7-83EE-165179713E9C](https://user-images.githubusercontent.com/109005044/178126027-3358852c-78f3-44bd-9327-541a285a99ef.jpeg)
![FD50A0B9-3DBB-4283-961A-5D576DE25FB5](https://user-images.githubusercontent.com/109005044/178126028-0a7b797f-f8e3-4d1f-9b67-60c60d2da75a.jpeg)

**Comment by benawad** [comment]
should be fixed now
