### ISSUE TITLE
Trade

### ISSUE THREAD

**Issue by TINY-LINK** [voidpet/bugs#672]
When I accepted a offer someone else who offered didn't get there pets back and I can't decline it as the trade no longer exists.

**Comment by benawad** [comment]
So you received something, but they did not?

**Comment by TINY-LINK** [comment]
> So you received something, but they did not?

No I accepted someone else's offer but there was another person who offered who didn't get there stuff back
If that makes sense

**Comment by benawad** [comment]
Do you know the username of the user who didn't get their stuff back?

**Comment by TINY-LINK** [comment]
athena007 I believe
