### ISSUE TITLE
Infinite Perfect Throws

### ISSUE THREAD

**Issue by Minzythebean** [voidpet/bugs#675]
**Describe the bug**
A clear and concise description of what the bug is: Throwing food at wild pet will give the perfect throw announcement.

**To Reproduce**
1. Go to ‘Something Park North’
2. Throw a container at a pet and get a perfect throw. 
3. Change to a food item (mine was firecracker pop) and feed it to the pet you got a perfect throw on.

**Expected behavior** 
you’ll see that every time you throw a food item at the pet it will count as a perfect throw.

This was on mobile version.

**Comment by benawad** [comment]
Could you record a video of this, I'm having trouble recreating it

**Comment by Minzythebean** [comment]
Uploading IMG_0438.mp4…

**Comment by Minzythebean** [comment]
https://user-images.githubusercontent.com/104790561/178156216-4f1d61c9-e0f5-4921-97dd-0d25187d26b1.mp4

**Comment by benawad** [comment]
fixed, ty
