### ISSUE TITLE
Active Item Issue

### ISSUE THREAD

**Issue by H1ra3th** [voidpet/bugs#678]
The new "Active Item" update forces to choose the kind of interaction to have with Wild Voidpets (Fight, Aura Container, etc.) before knowing their name and level. I don't seem to have the option to disable the Active Item function, I don't currently know if it's a bug or I'm just failing to find it.

**Comment by benawad** [comment]
The best way to see name and level is to start battling the pet (you can retreat)

We are working on new ways to suss out pets
