### ISSUE TITLE
Lost Voidpets During Trade

### ISSUE THREAD

**Issue by redradishroot** [voidpet/bugs#679]
I offered three catalysmic sads, a celestial sad, and a ephemeral sad for someone's fathomless spite. They accepted someone else's offer and couldn't decline mine, so I don't have any of my sads back and neither do they.

**Comment by benawad** [comment]
sorry about the trade offers going missing, just fixed that bug
I can either offer to compensate you with vm or give you the what the original trade was
what would you prefer?

**Comment by redradishroot** [comment]
Ooh thanks! If I choose the vm, how much would I get?

**Comment by benawad** [comment]
40K

**Comment by redradishroot** [comment]
I'll take the vm, thanks :) My vp username is "athena007"

**Comment by benawad** [comment]
you should have it now

**Comment by redradishroot** [comment]
thanks i got it!
