### ISSUE TITLE
Vivid voidpet not appearing in the pet log

### ISSUE THREAD

**Issue by Khavic** [voidpet/bugs#680]
**Describe the bug**

I traded my elemental vivid for a fathomless + vm. At first everything was fine, the fathomless is in my memory and the vm got added. However, once I went to the pet log, the fathomless did not appear, though I checked and refreched, it's still not here. (It's my first fathomless ever.)

**To Reproduce**
1. Trade something for a vivid voidpet you never catched before
2. Check if it's in your memory
3. Check the pet log as well
4. See that it didn't appear

**Expected behavior**
To see the nex vivid in the pet log, since it's the first time you got one.

**Video or Screenshots**
![image](https://user-images.githubusercontent.com/109036234/178154268-c3ef186f-1ea7-4f58-a6f7-cde4da48f726.png)
![image](https://user-images.githubusercontent.com/109036234/178154281-a3950c47-f81b-457f-926a-de63ee047525.png)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Edge 103]
 - Version [11]

**Smartphone (please complete the following information):**
 - Device: [none]
 - OS: [none]
 - Browser [none]
 - Version [none]

**Additional context**

**Comment by benawad** [comment]
Thanks, just fixed this. What's your voidpet username, I'll update your pet log

**Comment by Khavic** [comment]
Hello, thank you for responding.
My username is Khavic.

**Comment by benawad** [comment]
done
