### ISSUE TITLE
Make the navigation buttons blacks

### ISSUE THREAD

**Issue by theabellona** [voidpet/bugs#684]
White navigation buttons are extremely hard to see. Can't see what directions are even available to move.

Make the buttons black or a different colour from white. They will be much easier to see/use then.

![image](https://user-images.githubusercontent.com/109048083/178169102-0c885f2a-5057-4d86-8cf3-d52d5f203464.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by benawad** [comment]
if your browser uses dark mode, they will be dark now
