### ISSUE TITLE
Received voidpets from trading and can't equip them to my team

### ISSUE THREAD

**Issue by ProfessorMilk** [voidpet/bugs#701]
I received 3 estrangements from trading and I'm unable to equip any of them to my team 
![Screenshot_20220714-075518_Chrome](https://user-images.githubusercontent.com/109297444/179014820-7b146d7b-7da5-46be-b165-c88992306ce7.jpg)

**Comment by benawad** [comment]
Main pets need to be lower or equal to your player level
