### ISSUE TITLE
Can't use voidpet on my team

### ISSUE THREAD

**Issue by ShibeVoid** [voidpet/bugs#702]
**Describe the bug**
I had a recent trade where I got an anger vp, but when I want to use it on my team it doesn't give me the arrow (^) option to put it on my team.

**To Reproduce**
1. Go to 'Memory'
2. Scroll down to the voidpet named "Sephora" (anger phantom lvl 17)
3. You will see that I have no option to put them on my main team/fight with them, but it allows me to do anything else.

**Expected behavior**
Being able to put this vp on my main team so I can fight with it.

**Video or Screenshots**
![image](https://user-images.githubusercontent.com/109317216/179100470-d440c97a-bff9-4174-af97-2496b7767d27.png)

**Desktop (please complete the following information):**
 - OS: Dell/microsoft
 - Browser Chrome
 - Version latest

**Additional context**
I don't know if this should be an issue but this is a pet I got from a trade I opened. However, this doesn't happen to the rest of vp I got on trades nor any other of my voidpets. Also my username is ShibeVoid

**Comment by benawad** [comment]
You can only add pets to your main party that are less than or equal to your player level
