### ISSUE TITLE
Can't level up past level 64

### ISSUE THREAD

**Issue by Koyd333** [voidpet/bugs#704]
**Describe the bug**
Can't level up past 64 for either my voidpets or player character

**To Reproduce**
1. Try to level up from level 64
2. Exp resets to 0

**Expected behavior**
I level up to level 65.

**Video or Screenshots**
https://cdn.discordapp.com/attachments/939571879121944616/997566666735104000/2022-07-15_14-10-43.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 101

**Comment by benawad** [comment]
should be fixed now
