### ISSUE TITLE
selling an auction hasnt given me my vm

### ISSUE THREAD

**Issue by crikitz** [voidpet/bugs#706]
**Describe the bug**
i sold an item for 1000vm and it didn't give me the vm i should've gotten. ive tried refreshing the page and just waiting, but it seems that my vm is updating just fine, it just refused to give me the vm.

**Expected behavior**
i expected it to give me my vm as it always did, and should

**Video or Screenshots**
![image](https://user-images.githubusercontent.com/107601751/179322484-17881eb4-968b-408d-93ff-610022c6d5fd.png)
![image](https://user-images.githubusercontent.com/107601751/179322451-4283145a-2c4f-4ae3-993c-1e6220ada646.png)

**Comment by benawad** [comment]
sent you vm
