### ISSUE TITLE
Removing move book(s) from a voidpet and not showing up in your/my inventory.

### ISSUE THREAD

**Issue by BigToeOfJoe** [voidpet/bugs#708]
**Describe the bug**
So when I am removing a movebook from a voidpet which is clicking on the "-" button and usually I would get the books in my inventory but not non of the books I am taking back is ending up in my inventory after I click save.

**To Reproduce**
1. Go to 'a voidpet's "training" section'
2. Click on '-'
3. Scroll down to 'Not really down but up and save'
4. See error which then you check my/your inventory to not see the book there

**Expected behavior**
I expected the book(s) to come back to my inventory after I took them off of a voidpet/vp.

**Video or Screenshots**
Inventory before
<img width="316" alt="Screenshot 2022-07-15 223651" src="https://user-images.githubusercontent.com/109399058/179335889-c95ce4dd-738d-4bdb-8338-b4543d3b8055.png">
take or remove a movebook
<img width="323" alt="Screenshot 2022-07-15 223730" src="https://user-images.githubusercontent.com/109399058/179335979-9eea1789-6416-4b65-9321-faa68b77a3bd.png">
<img width="320" alt="Screenshot 2022-07-15 223749" src="https://user-images.githubusercontent.com/109399058/179336053-75d7b35b-7e21-4da2-8ac7-c46dc27b3f97.png">
save
<img width="328" alt="Screenshot 2022-07-15 223809" src="https://user-images.githubusercontent.com/109399058/179336118-a1b0748b-919c-46f5-9b1c-3ad60c384795.png">
inventory after
<img width="316" alt="Screenshot 2022-07-15 223651" src="https://user-images.githubusercontent.com/109399058/179336171-37ae68ea-2479-4dca-a47d-04c7c87e788e.png">

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]
 - Version [lastest version]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by benawad** [comment]
removing a move no longer gives you the book back
