### ISSUE TITLE
5 ice slash on 1 vp

### ISSUE THREAD

**Issue by smogg-s** [voidpet/bugs#710]
**Describe the bug**
while i was messing around with my lonely's moves, i somehow got 5 ice slash on the lonely. ive tried reloading and the 5 ice slash was still there, and now my lonely is living on a pure ice slash build.

**To Reproduce**
1. go to the move set
2. remove ice slash, save, and then add another ice slash
3. message should appear saying "remove from inventory failed"
4. see error

**Expected behavior**
i expected that i wouldve gotten 4 ice slash and not over the move limit

**Video or Screenshots**
![image](https://user-images.githubusercontent.com/109423781/179357865-9bcc930b-4b82-42ba-baee-a6676342ec29.png)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]
 - Version [21H2]

bug happened on computer

**Additional context**
i also tried going into battle to confirm that i actually had 5 ice slash, and yep, i got ice slash every time. i only have 5 moves on my lonely, and its all ice slash

**Comment by smogg-s** [comment]
oh and, my os is windows 11, made a typo there

**Comment by benawad** [comment]
you should be able to remove it now
