### ISSUE TITLE
Voidpet HP drop

### ISSUE THREAD

**Issue by greyisntacolor** [voidpet/bugs#711]
My Voidpets' HP had dropped dramatically. My Anger is at level 16 and was at 300 HP this morning. I check back later mid "Seeing Red" grind only to lose the battle because my pets HP has dropped to what it was when they were at levels 7 and below. There are level 4 pets with higher HP stats than my level 16s??

**Comment by benawad** [comment]
The healths needed to be recalibrated for max level 100. Some of the wild pets may be cached
