### ISSUE TITLE
While catching wild pets they disappear suddenly

### ISSUE THREAD

**Issue by AmberLess** [voidpet/bugs#713]
Edit: I have seen this happening with multiple wild pets. If this is a feature of the game and they run away it.would be nice to maybe have it state that they ran away. 

When trying to catch any wild sad pet they disappear instead of being caught. This happens in all areas and uses up items.

**To Reproduce**
1) Try to catch a wild sad by using any type of container 
2) See them blip off the screen 

**Expected behavior**
After a certain amount of good okay or perfect throws, I expect to be able to catch a wild sad like I can with all other wild pets

 I use a Chrome browser to play.

**Comment by benawad** [comment]
this is part of the game, there is a chance they flee

we will be making a better user experience for it though
