### ISSUE TITLE
Seeing red bug

### ISSUE THREAD

**Issue by Zirls** [voidpet/bugs#721]
I was on seeing red 3 at Something Park Playground and when I checked on one of voidpets I was back to normal Something Park Playground. this sometimes takes you to Something Park Bench too. 

Laptop
 - OS - macOS
 - Browser - Opera
 - Version - latest version

**Comment by Zirls** [comment]
I just realized that you could use the up and down keys to move even while you're in the menu, even in seeing red.

**Comment by benawad** [comment]
fixed
