### ISSUE TITLE
Seeing Red Bug

### ISSUE THREAD

**Issue by r4yv3nw1ng5** [voidpet/bugs#722]
**Describe the bug**
When trying to go into Seeing Red, nothing happens.

**To Reproduce**
1. Go to any part of the map
2. Defeat all of the pets in that area
3. No Seeing Red portal shows up (for me)

**Expected behavior**
I expected a portal to appear and to click on it to enter Seeing Red.

**Video or Screenshots**

https://user-images.githubusercontent.com/109699476/180085670-2aaf9d88-f87e-4f0b-bfce-b7be6edd76ba.mov

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Google Chrome
 - Version 103.0.5060.134 (should be the latest)

**Additional context**
I don't know if the way to enter has changed, so all of this might be wrong
I'm trying to complete Esse quest #4 if that makes a difference

**Comment by benawad** [comment]
refreshing stops showing red from appearing
