### ISSUE TITLE
Elemental accessories were not returned after trade expired

### ISSUE THREAD

**Issue by Qexotto1** [voidpet/bugs#723]
I had put both an elemental crown and elemental scarf up for trade (in the same trade) and upon it expired, I received the usual notification, but the accessories were not returned to my inventory, even after refreshing.

1. Put elemental accessories up for trade
2. Wait for trade to expire, and receive notification.
3. Refresh page, and see that accessories were not returned to me

**Expected behavior**
It was expected that upon the trade expiring, my elemental crown & scarf would be returned to my inventory.

**Smartphone (please complete the following information):**
 - Device: iPad
 - OS: iOS 15
 - Browser Safari
 - Version 15

**Comment by Qexotto1** [comment]
my voidpet user is Qexotto

**Comment by benawad** [comment]
added them back to your inventory
