### ISSUE TITLE
My items disappear when my trade expires

### ISSUE THREAD

**Issue by Spookyz1** [voidpet/bugs#729]
Describe the bug below and provide your Voidpet username.
My username is Hours. So what's been happening is whenever I put items up for trade and the Trade expires, my items disappear. They're not in my inventory anymore. This has happend a lot times and somehow I only noticed today when my inventory was basically empty.

**Comment by benawad** [comment]
What items are you missing?

**Comment by Spookyz1** [comment]
Arcane scarf. Jaded scarf. 2 squishy plasma. 2 rainbow scarf. Cosmic scarf.
2 Sparkling plasma. Cotton candy scarf. Berry scarf.  That's about it. Lmk
if you want proof

**Comment by benawad** [comment]
sent
