### ISSUE TITLE
Forgetting Multiple Pets

### ISSUE THREAD

**Issue by Lawfulsinner** [voidpet/bugs#730]
Username: LawfulSinner

I forgot 64 lonelies in one go, to make space because my memory felt cluttered. And instead of getting 64 wishes like I would’ve if I did it individually, I only got 1 wish.

**Comment by Zirls** [comment]
I believe it's a visual glitch. I let go of 6 estrangements and it said only got one but when I checked I actually got the right amount.

**Comment by Lawfulsinner** [comment]
> I believe it's a visual glitch. I let go of 6 estrangements and it said only got one but when I checked I actually got the right amount.

I didn’t get the right amount. I checked.

**Comment by benawad** [comment]
fixed and reimbursed you 100 lonely wishes @Lawfulsinner
