### ISSUE TITLE
Disappearing wishes

### ISSUE THREAD

**Issue by shurrupax** [voidpet/bugs#732]
NOT A VISUAL BUG, whenever you mass delete voidpets, you only get 1 wish.
![00B5BF9F-6E74-472F-BD54-EE36FF20D983](https://user-images.githubusercontent.com/109847142/180596099-782eeb64-130f-4a61-86df-cb5d4a84a05b.png)
i had 30 wishes, deleted a few, refreshed the page and i still have 31 instead of 33.

**Comment by benawad** [comment]
fixed now
