### ISSUE TITLE
Couldn't obtain the red reflecting glass after the QUEST "Mirror mirror" was finished

### ISSUE THREAD

**Issue by sussycitizen** [voidpet/bugs#733]
Idk if it is just my rigged luck or an actual bug. But, i couldn't find ANY red reflecting glass. Even while i'm seeing red

**Comment by benawad** [comment]
were you in the right seeing red location?

**Comment by sussycitizen** [comment]
I'm not

**Comment by sussycitizen** [comment]
Bc i never paid attention where the quest asked me to get it from, so i
went straight for the lake
