### ISSUE TITLE
Broken Trade

### ISSUE THREAD

**Issue by MossBeloved** [voidpet/bugs#737]
Describe the bug below and provide your Voidpet username.
About three-four days ago I offered on a trade that had four Arcane vivids Pride, Spite, Lonely, and Paranoia. I offered 1300 vm. an Illusive Spite, a Normal level 21 Sonder, and a Ethereal Pride. The trade is still on "Very long" timer, and I haven't been accepted or denied yet, but all my pets and vm are still up on the offer. I'd really like my vm and pets back :]

My VP name is MossBeloved
![ev 1](https://user-images.githubusercontent.com/110106972/181255919-21e673fc-2762-41bc-b4a6-db0e6ab322ed.png)
![ev 2](https://user-images.githubusercontent.com/110106972/181255922-71a9921b-8442-4516-ba31-33add2dc1d4f.png)

**Comment by benawad** [comment]
looks like the trade is gone now
