### ISSUE TITLE
Movebooks error in battles sometimes

### ISSUE THREAD

**Issue by idkanymore6110** [voidpet/bugs#739]
Describe the bug below and provide your Voidpet username.
IGN: idkanymore6110

I think this isn't the first time I've noticed this, but my sonder has 4x Ball of despair and 1x Refine, yet in a battle (against Minnie's Dad), I've had Refine show up twice in the same turn.
![image](https://user-images.githubusercontent.com/109921104/181637128-dba4e32e-5846-489f-bc3c-d14d9a8cf4b1.png)
![image](https://user-images.githubusercontent.com/109921104/181637148-76f4bf4a-3ed4-434f-81d3-a5bc1f4e7c50.png)

**Comment by idkanymore6110** [comment]
![image](https://user-images.githubusercontent.com/109921104/181657445-1cd30338-c145-47ff-9b09-29b112ab39c7.png)
![image](https://user-images.githubusercontent.com/109921104/181657449-84eae183-f4eb-45cf-9490-0c166ef8d3ef.png)

**Comment by benawad** [comment]
Expected behavior if you have less than 8 total moves.
