### ISSUE TITLE
No seeing red

### ISSUE THREAD

**Issue by Orathiel** [voidpet/bugs#744]
I've played the game since like the first 50k sign ups, and I know how seeing red works and everything, but since like yesterday seeing red just doesn't show up
Idk why, and I've tried exiting the game and coming back, logging out and then back in, but it isn't working at all:/ I use it very often to vm grind and vivid grind pls help wjxnsjf
Edit: my username is Orathiel

**Comment by Zirls** [comment]
While bonking three voidpets dont refresh the page during battle.
