### ISSUE TITLE
Downbad eyes

### ISSUE THREAD

**Issue by MayBeete** [voidpet/bugs#745]
My discord username is MayBee#7196
My Voidpets username is MayBeeE

I noticed that the eyebrows of Downbad stage 3 tails are offset and are placed in the heart of the eye
There is only this problem with the third stage for every Downbad
![3](https://user-images.githubusercontent.com/110329132/182018053-77c8c33e-8cbb-4e4d-8ddd-ef039fb5b7e2.png)

**Comment by benawad** [comment]
fixed
