### ISSUE TITLE
"Perfect throw" on screen

### ISSUE THREAD

**Issue by Clarisse2207** [voidpet/bugs#746]
If I do a "Perfect throw" or multiple the pop up won t ever leave. If i fight a voidpet or i leave the map it stay here.
Not a big problem but technically it s a bug so 🤷‍♀️

![Screenshot_20220801-210540_Ecosia](https://user-images.githubusercontent.com/105777005/182226113-622bc2eb-d16d-4b79-9139-70a263c5774a.jpg)

**Comment by Clarisse2207** [comment]
My voidpet username is Clarisse2207 srry I forgot

**Comment by Zirls** [comment]
Making a weak or other throw should make it go away also just tapping on it should make it go away.

**Comment by Clarisse2207** [comment]
Okay I m so sorry that I didn t even try to touch it I m gonna delete the post rnThx you so much Envoyé de mon Galaxy S21 5G Orange
-------- Message d'origine --------De : Zirls ***@***.***> Date : 01/08/2022  22:03  (GMT+01:00) À : voidpet/bugs ***@***.***> Cc : Clarisse2207 ***@***.***>, Author ***@***.***> Objet : Re: [voidpet/bugs] "Perfect throw" on screen (Issue #746) 
Making a weak or other throw should make it go away also just tapping on it should make it go away.
