### ISSUE TITLE
Pet not being able to use move that it was able to use before

### ISSUE THREAD

**Issue by P0TAT0oo** [voidpet/bugs#747]
My discord username is VerifyPotato#6724
My Voidpets username is p0tat0

I was grinding for vm so i removed a couple of my sanctimony's non-earth moves in training so i would easily defeat sonders and sads with earth type moves. After finishing I wanted to add my non-earth type moves back but I noticed that the move Refined was missing. 

This might not be bug and I'm just dumb but if this is something that i can avoid in the future i would prefer so.

![Screenshot 2022-08-01 11 18 30 PM](https://user-images.githubusercontent.com/110447813/182305412-a689fd9b-04f3-470d-8f3b-1241f497f92f.png)

![Screenshot 2022-08-01 11 18 49 PM](https://user-images.githubusercontent.com/110447813/182305504-b7621849-c730-4e1f-9a02-02edf7ee6b95.png)

**Comment by Zirls** [comment]
When removing moves/books you don't get them back. If I were you I would remove a move If know I have the book so they can relearn it anytime.

**Comment by benawad** [comment]
^
