### ISSUE TITLE
Cannot see what voidpet drew on pc

### ISSUE THREAD

**Issue by axolotls99** [voidpet/bugs#75]
On mobile, you can see what your voidpet drew when doing that activity, but on pc the drawing flashes away before you can see it

**Comment by Friedmashedpotatoes** [comment]
I'm on mobile and can't see the drawing, haven't tested on pc yet so idk

**Comment by benawad** [comment]
Could you post a video of this

**Comment by axolotls99** [comment]
https://photos.app.goo.gl/Xj8tga29XMPB7hmu7
I've never used github before I hope that works

**Comment by axolotls99** [comment]
It is fixed now

**Comment by axolotls99** [comment]
It is broken again now on Brave, Chrome, and Firefox, but it still works on brave browser on my phone

**Comment by benawad** [comment]
Just pushed an update, could you see if that fixes it

**Comment by axolotls99** [comment]
Yep it's good now :)
