### ISSUE TITLE
Didn't receive my 16k vm back after offering for an elemental scarf and not getting it

### ISSUE THREAD

**Issue by marshall1ee** [voidpet/bugs#751]
user: marshalllee
i offered 16kvm for an ele scarf and notifs didn't say whether trde was accepted declined or expired but there was no sign of the scarf or my 16kvm in my inven. rlly srry that I don't have any proof there's nothing in notifs and I didn't ss my VM amount. glitch alrdy happened before with my likes to win phantom spite but it got returned. would rlly appreciate if I got my VM back. thanks

**Comment by benawad** [comment]
was it a trade or bid on auction house?

**Comment by marshall1ee** [comment]
it was a trade and there was no notif regarding what happened to it and the vm

**Comment by benawad** [comment]
refunded you the vm

**Comment by marshall1ee** [comment]
thank you so much :)
