### ISSUE TITLE
Quest and voidmatter bug

### ISSUE THREAD

**Issue by HollisBones** [voidpet/bugs#752]
For the quest bug, I'm trying to do strings first assignment: Defeat wild pets, problem is that when I defeat a pet it doesn't count for the quest, no matter what I do it's stuck at 0

for the voidmatter bug, I'm defeating pets and whatnot but I'm not getting any voidmatter, like none at all.

**Comment by Zirls** [comment]
For the quest I think you have to defeat wild voidpets at a specific spot and for voidmatter it's just luck.
