### ISSUE TITLE
One of my voidpets are gone

### ISSUE THREAD

**Issue by Zirls** [voidpet/bugs#753]
I had a stage 5 sonder but i cant see it from my memory however, notifications say that they are still in my memory and i can look at it from there.( it will say Could not find pet. when not in your memory) 
Username - zirl
<img width="518" alt="Screen Shot 2022-08-05 at 11 44 54 AM" src="https://user-images.githubusercontent.com/109664684/183123638-9c34be96-d0b4-45bc-bf8c-914fdedfed45.png">
<img width="399" alt="Screen Shot 2022-08-05 at 11 44 29 AM" src="https://user-images.githubusercontent.com/109664684/183123646-7cce96ce-afb5-469c-9043-ac516ca6e0f6.png">
<img width="431" alt="Screen Shot 2022-08-05 at 11 44 22 AM" src="https://user-images.githubusercontent.com/109664684/183123647-bef06aba-88d2-4df1-a1d5-8c91dcc5d52e.png">

**Comment by benawad** [comment]
The current owner of that pet is `HoneyBumbleBees`. Did you trade it?

**Comment by benawad** [comment]
Looks like you traded it to `pumpkinNoodle`?

**Comment by Zirls** [comment]
> Looks like you traded it to `pumpkinNoodle`?

I do have an accepted trade from them! I guess I just forgot sorry! Nevertheless, a bit unusual that you can see still the vp you got from a trade and then traded away.
