### ISSUE TITLE
Arrowkeys work while memory and petlog are open

### ISSUE THREAD

**Issue by idkanymore6110** [voidpet/bugs#755]
Describe the bug below and provide your Voidpet username.
IGN: idkanymore6110
Bug: Several times when farming voidpets, I checked my memory and petlog and used arrowkeys to scroll up and down the lists, and came back to see that I had moved to an adjacent area. The video shows below that using arrow keys can actually move you from one area to another, even if the petlog is open, which caused all farming progress to be despawned if I didn't go back within the minute.

https://user-images.githubusercontent.com/109921104/183272879-a880fbbc-5142-4f7f-81ef-f6c465a09acf.mp4

**Comment by idkanymore6110** [comment]
Edit: Arrowkeys seem to work in all menus except for auction, if a video is required let me know.

**Comment by Zirls** [comment]
It's been like this for a while now. Hopefully, it will be changed without completely disabling the arrow keys like in seeing red. For now, try not to use the arrow keys at all when doing anything in the menu (it can happen in any of the menus except for auction)

**Comment by benawad** [comment]
should be fixed now
