### ISSUE TITLE
Cannot craft Rainbow Scarf

### ISSUE THREAD

**Issue by RaineFlower** [voidpet/bugs#756]
Username: tallshorty

When crafting Rainbow Scarf in Customize, a red error bar at the top of the screen says "Item is not for purchase" after I confirm I wanted to craft. The Rainbow Scarf then looks as if I own it, but when pressing the Save Button another red error bar at the top of the screen says "You don't own one of those items". I have tried this process on an Anger, a Pride, and a Spite.

**Comment by benawad** [comment]
Rainbow scarf was a special pride month item that is no longer for sale. I'll hide it in that screen.
