### ISSUE TITLE
arrow keys not working

### ISSUE THREAD

**Issue by Hinomori-Shiho** [voidpet/bugs#757]
Describe the bug below and provide your Voidpet username.
when I try to use the arrow keys or WASD it doesn't work, the only way to move around is using the mouse or touching the screen

*WINDOWS 10*
VP USER ~ Lumeria

**Comment by benawad** [comment]
If you refresh the game and try using the arrow keys does it work? Or do they stop working after you open some menus?

**Comment by benawad** [comment]
should be fixed now
