### ISSUE TITLE
Just a small visual glitch

### ISSUE THREAD

**Issue by Zirls** [voidpet/bugs#758]
The back of my chareters hair is floating 💀
my user is zirl 
Edit: Even going back home shows the glitch.
<img width="280" alt="Screen Shot 2022-08-08 at 7 09 17 PM" src="https://user-images.githubusercontent.com/109664684/183535298-1c9d18d1-9b89-4e0b-8e83-f91b56dd0124.png">

**Comment by benawad** [comment]
should be fixed now
