### ISSUE TITLE
Finding Trader Username

### ISSUE THREAD

**Issue by redradishroot** [voidpet/bugs#765]
Basically someone needed to log a fathomless envy + illusive envy and I put it up for trade.
 
<img width="859" alt="Screen Shot 2022-08-15 at 5 01 41 PM" src="https://user-images.githubusercontent.com/109033213/184717723-d3a84b7c-24c4-44e3-b527-09bde2a5424f.png">

I received an offer of 1.3k vm + phantom scarf and accepted, thinking that it was the person I talked to. 
<img width="440" alt="image" src="https://user-images.githubusercontent.com/109033213/184717986-4e000916-b2f2-41e4-a9b5-5b9f2efe17d2.png">
The original trader had never actually made an offer and I understand it's my fault for not actually confirming :(

I don't have the IGN of the person who traded with me, and was wondering if it's possible for me to find it so I can buy back the two pets? I've kinda grown attached to specifically the fathomless envy. I definitely understand if it doesn't work! Thanks :)

IGN - athena007

**Comment by benawad** [comment]
Unfortunately, we do not keep logs of completed trades
