### ISSUE TITLE
Snake road Institute Path 

### ISSUE THREAD

**Issue by g4yfrogs** [voidpet/bugs#769]
Describe the bug below and provide your Voidpet username.
On the Snake road Institute Path I cannot go into "seeing red". My username is g4yfrogs

<img width="1440" alt="Screen Shot 2022-09-02 at 12 54 56 PM" src="https://user-images.githubusercontent.com/112723042/188210682-2639a817-bdb1-44a3-b0c7-041bb37466b3.png">

**Comment by benawad** [comment]
make sure you don't refresh between defeating voidpets
