### ISSUE TITLE
Random letters

### ISSUE THREAD

**Issue by ForbiddenBerri** [voidpet/bugs#77]
**Describe the bug**
I was trying to get a body in the game, as I reached the end, the bottom of the page had "random" words and just looked all glitched

**To Reproduce**
1. Go to Explore
2. Click to continue until you reach the last page talking about the developers continuing the game
3. Scroll down to the bottom of the page

**Expected behavior**
I expected it to have the usual background image

**Video or Screenshots**
![Screenshot_20220203-121517_Samsung Internet](https://user-images.githubusercontent.com/98974917/152395429-ac18f41b-40eb-48a5-9935-7b5f1a9c3dd2.png)

**Smartphone (please complete the following information):**
 - Device : Samsung S20 FE
 - OS : 11
 - Browser : Safari
 - Version : 16.0.6.23

**Comment by benawad** [comment]
If you turn off dark mode, does it still appear?
