### ISSUE TITLE
Lost VM while bidding

### ISSUE THREAD

**Issue by MossBeloved** [voidpet/bugs#772]
I was bidding against someone for a Fathomless scarf, at the time I had around 13k-20k VM 6k going to the scarf, but when I checked I only had 1k VM and no scarf. I re-logged, tried a new browser and even waited an hour and still nothing. I'm now have no idea what happened to my vm, the ss showed is my vm after the bidding war, and my inventory with no scarf. 

VP User - MossBeloved
Discord User - MossBeloved#7502

![Screenshot_20220915-015852-928](https://user-images.githubusercontent.com/110106972/190340851-792bcb20-c79c-45bb-9c12-fb6beb80044c.png)
![Screenshot_20220915-015840-241](https://user-images.githubusercontent.com/110106972/190340855-2f3594a4-0416-4c41-a0ac-ace762a7d3c4.png)

**Comment by benawad** [comment]
sorry about that, I refunded you vm
