### ISSUE TITLE
Too many creatures 

### ISSUE THREAD

**Issue by Vivi0w0** [voidpet/bugs#775]
ViviUwU
There is more then three wild creatures on ghost road 
![943C7A3C-4CC7-4270-8A02-F4D8EE3F1E4E](https://user-images.githubusercontent.com/113735897/190831200-578edf5c-a2de-4c33-9df2-c8f3f4cfc02b.png)

**Comment by Vivi0w0** [comment]
https://user-images.githubusercontent.com/113735897/190831290-c1d9add6-f5f3-460f-aa46-61faa7c7f419.MOV

**Comment by benawad** [comment]
this is called a raid and is a feature
