### ISSUE TITLE
Wishes after Battle, or after chase not showing up

### ISSUE THREAD

**Issue by Superredpanda** [voidpet/bugs#780]
Describe the bug below and provide your Void username.
 

I don't know if its because I was playing on my phone then switched to computer. I have been playing for a few hours on my computer and I went to evolve my anger pet ( because i thought i would have enough ) It didn't have any added to the wishes to it though playing voidpets and I have been fighting angers for about a hour at least and nothing. Also I though it was me and imagining it and so i went to go back to grinding and its been about 30 minutes and still no anger wishes added. It has also happened for Curious wishes too.

**Comment by Superredpanda** [comment]
username 
Superpanda

**Comment by benawad** [comment]
Seeing red does not drop items

**Comment by Superredpanda** [comment]
Oh okay
