### ISSUE TITLE
Cant catch stage 2 voidpet and above

### ISSUE THREAD

**Issue by Iceteaholic** [voidpet/bugs#793]
Describe the bug below and provide your Voidpet username.
voidpet user: Iceteaholic
For a quest I'm supposed to catch a stage 2 spite. But when I try to catch even when the container says perfect it won't catch it. I don't know if I'm doing something wrong or if this is a bug.

**Comment by benawad** [comment]
Try lowering there hp or feeding them to have a higher chance to catch them
