### ISSUE TITLE
tesseract background 

### ISSUE THREAD

**Issue by Zirls** [voidpet/bugs#794]
I played this game for a long while and tesseract container was removed. Due to this, the background is still purple and this shows up for other voidpets that were caught as well with a tesseract container.

<img width="278" alt="Screenshot 2022-12-17 at 9 04 38 PM" src="https://user-images.githubusercontent.com/109664684/208279372-0d58d0c5-6b56-4375-8a03-84d9dfd81ca3.png">
<img width="278" alt="Screenshot 2022-12-17 at 9 04 44 PM" src="https://user-images.githubusercontent.com/109664684/208279370-c8f846c9-4a84-4d7e-938c-0f4e0ddd32ca.png">
<img width="278" alt="Screenshot 2022-12-17 at 9 09 35 PM" src="https://user-images.githubusercontent.com/109664684/208279390-56b8812e-1832-421d-ac2b-e4eeb8b3e49a.png">

**Comment by benawad** [comment]
Purple is any psyche container
