### ISSUE TITLE
can precede in the tutorial

### ISSUE THREAD

**Issue by GlitchedDuo** [voidpet/bugs#795]
ToonDamien

It wants me to feed my void pet but i have no food and cant seem to find any?

<img width="245" alt="image" src="https://user-images.githubusercontent.com/110046033/208807256-ea55b52e-2a28-4b40-9a40-0b59bb3d17a9.png">
<img width="258" alt="image" src="https://user-images.githubusercontent.com/110046033/208807282-947de1a4-a985-4f79-aeec-d784f73ea824.png">
<img width="298" alt="image" src="https://user-images.githubusercontent.com/110046033/208807316-d0f0268b-6f51-4a5f-9a1b-ebd2989c8693.png">

<img width="268" alt="image" src="https://user-images.githubusercontent.com/110046033/208807366-d32dc628-ddfe-4778-83d6-5b389343b043.png">

**Comment by benawad** [comment]
Why did you close this, are you no longer stuck?

**Comment by GlitchedDuo** [comment]
i am no longer stuck :)
