### ISSUE TITLE
Cannot read properties of null (reading 'user')

### ISSUE THREAD

**Issue by Shpackk** [voidpet/bugs#798]
Source of bug - https://voidpet.com/benawad
<img width="440" alt="Screenshot 2023-01-13 at 17 48 24" src="https://user-images.githubusercontent.com/76433892/212361207-27eeaa87-60ed-4eee-b8c8-d956074d0f2b.png">
Clicking the 'info' (or more) button, besides 'Gunter 🐧 likes to rescue those in danger. ' text - results in error (screenshot below)
<img width="422" alt="Screenshot 2023-01-13 at 17 49 11" src="https://user-images.githubusercontent.com/76433892/212361365-11cf31f5-9e27-4b68-b776-efe504186440.png">

P.S. it reproduces on all of them pets.

**Comment by benawad** [comment]
Thanks, should be fixed now
