### ISSUE TITLE
Birthday Of Pets Are Wrong; EDIT: Close This Because I Was Wrong

### ISSUE THREAD

**Issue by SamarthCat** [voidpet/bugs#80]
**Describe the bug**
I created a pet on February 4th but the pets birthday says 🎂 7 January 

**To Reproduce**
1. Make a new voidpet
2. Go to More about PetName 👀
3. You will see a date next to a cake and it will be wrong

**Expected behavior**
The birthday should be the day you created the voidpet

**Video or Screenshots**
![image](https://user-images.githubusercontent.com/79756986/152556451-32851a6d-a76c-4fd7-805f-e9010285822d.png)
![image](https://user-images.githubusercontent.com/79756986/152556604-b70ad526-ee30-48cf-af06-5e8841454868.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera GX
 - Version: 82

**Comment by SamarthCat** [comment]
EDIT: Ok I was wrong I just watched https://www.youtube.com/watch?v=Jylk6ggjtlw&ab_channel=BenAwad and I realised the birthdays are random sorry for wasting your time.

**Comment by benawad** [comment]
It's ok, the logic: the day you met your Voidpet is not the day they were born.
