### ISSUE TITLE
Food Bug

### ISSUE THREAD

**Issue by HeZiChla** [voidpet/bugs#802]
Jey i have a food Bug in the Tutorial. I cant Feed the Retreated Void Pet. I tried to refresh the page multiple times but it don't work. What a pity. Now im really sad. Name on Voidpet is: HeZiChla

**Comment by benawad** [comment]
Could you send a video of that happening

**Comment by HeZiChla** [comment]
![Screenshot_20230129_094351_Chrome](https://user-images.githubusercontent.com/123833120/215315311-97f64230-38b0-4fae-ba39-98d80aed4e2b.jpg)
![Screenshot_20230129_094346_Chrome](https://user-images.githubusercontent.com/123833120/215315314-fb863344-c741-45e8-bb74-de66c2131dc9.jpg)
![Screenshot_20230129_094331_Chrome](https://user-images.githubusercontent.com/123833120/215315318-d318e422-483b-44f4-b763-89fdce166f76.jpg)
![Screenshot_20230129_094325_Chrome](https://user-images.githubusercontent.com/123833120/215315320-23f7683e-997a-43df-8be3-95874e5d6ab8.jpg)
Here are some Screenshots from that Bug

**Comment by benawad** [comment]
try refreshing, you should have food now
