### ISSUE TITLE
stuck on tutorial

### ISSUE THREAD

**Issue by gh0stcl0wn** [voidpet/bugs#804]
I didn't understand the catch mechanic at first and ran out of capsules and am now stuck in the tutorial my username is ghostclown

**Comment by benawad** [comment]
sent you 20 more

**Comment by gh0stcl0wn** [comment]
I did not receive them, I am still stuck

**Comment by benawad** [comment]
did you refresh?

**Comment by gh0stcl0wn** [comment]
yes multiple times

**Comment by benawad** [comment]
https://voidpet.com/ghostclown

is this you?

**Comment by gh0stcl0wn** [comment]
yes that's me

**Comment by benawad** [comment]
ok I sent you more
