### ISSUE TITLE
No longer a Giga member but still being charged

### ISSUE THREAD

**Issue by Rells35** [voidpet/bugs#807]
I'm sorry if this isn't where I should be putting this, but I'm not too sure where else I should put it. I used to be a giga member but had to cancel due to losing my job, but I'm still being charged for the membership. I went to look to see if I cancelled it properly on the website but my account says I don't have giga anymore. I'm really not sure what I can do now so if someone could help me with this I would be really thankful

**Comment by benawad** [comment]
What's your username?

**Comment by Rells35** [comment]
Rells

**Comment by benawad** [comment]
You are all cancelled now and refunded the last charge

**Comment by Rells35** [comment]
thank you so much!
