### ISSUE TITLE
voidpet refuses to let me remove my payment information, charges me despite cancelling

### ISSUE THREAD

**Issue by lapinamoric** [voidpet/bugs#812]
my voidpet username is lapinamoric. no matter what i try, ever since i connected the app, voidpet continues to charge me for giga while not giving me the giga benefits on the website or the app. there is no way to change this through the website, even though i cancelled my subscription through apple. for a while, it double charged me. there is seemingly no way to remove my payment information, either.

**Comment by benawad** [comment]
You have giga on the website now. If you close and open your app you should have giga on their as well (assuming your account is connected in settings). Would you like me to cancel your giga subscription or would you like to keep it?

**Comment by lapinamoric** [comment]
i would prefer to have my giga cancelled, thank you very much. i may resubscribe in the future, but these issues have left me wanting some breathing room.

**Comment by benawad** [comment]
Cancelled and refunded the last 2 charges. Sorry for the inconveniences, let me know if I can be of any other help.
