### ISSUE TITLE
Mysterious Second Account Inaccessible

### ISSUE THREAD

**Issue by baublebeee** [voidpet/bugs#815]
I made a Voidpet (desktop) account with the username baubleBee maybe around a year ago and didn't play on it very often. More recently, I picked the game back up, but when I was trying to log in it made me pick a new username. I figured it was because the first account was so old and maybe the game had updated a lot more since then, so I made a new account under baubleBeee and I have been playing on that one. However, after I did that, it seems like the only way to log into my account is through discord, which now only logs me into the old baubleBee account I made years ago again, leaving the newer one I've used more seemingly inaccessible. 

I don't have any alt discord accounts, so I don't know how or why I ended up having to make the second account only to not even be able to log into it again. I know I can delete my old account, but it gives the warning that if I do that I might not be able to make a new account again and I'm a bit afraid this will lock me out of _both_ accounts. Is there any way to get this fixed?

**Comment by benawad** [comment]
baubleBee is connected to the discord `baublebee#0`

baubleBeee is connected to the discord `mummblet1gmail.com_23729#0`

**Comment by baublebeee** [comment]
> baubleBee is connected to the discord `baublebee#0`
> 
> baubleBeee is connected to the discord `mummblet1gmail.com_23729#0`

The baubleBeee account's Discord username is just the email that I use to log into the baubleBee Discord account. Is there anything I can do about switching which account connects to what login? I'd much rather continue to use the baubleBeee account, but when I try to log into the site it automatically routes logging in through Discord and puts me back through to the original baubleBee account.

**Comment by benawad** [comment]
swapped them for you
