### ISSUE TITLE
Not receiving MoveBooks

### ISSUE THREAD

**Issue by Mull20** [voidpet/bugs#816]
Describe the bug below and provide your Voidpet username.
I went to swap some moves out temporarily on my Anger, and when I went to teach it Fume again, I didn't have the available books. I've experimented, and so far it seems like I'm not receiving any movebooks when I try to put them in my inventory. I could really use some help. I've lost a lot of time and value

My voidpet username is Madanach

**Comment by benawad** [comment]
Once learned move books are used up
