### ISSUE TITLE
Weird visual bug when trying to perform activities

### ISSUE THREAD

**Issue by ognjenMarinkovic27** [voidpet/bugs#84]
My friend was trying to lift with her pet and noticed this weird visual bug. She also says that she cannot improve her heart level

https://user-images.githubusercontent.com/37124521/152620501-5d916b77-6d92-45cb-8099-2bd6a4311f64.mp4

**Comment by ognjenMarinkovic27** [comment]
https://github.com/voidpet/bugs/issues/73#issue-1121999227 is related

**Comment by benawad** [comment]
give it another try, should be fixed now

**Comment by ognjenMarinkovic27** [comment]
hell yeah ben u da man
