### ISSUE TITLE
Wrong date of birth

### ISSUE THREAD

**Issue by 10054bondoc** [voidpet/bugs#85]
![Screenshot_20220206-084434_Chrome](https://user-images.githubusercontent.com/63565824/152663948-61ab8d78-23c5-4c3a-9aea-eeec55143905.jpg)

The error was initially wrong zodiac sign but I checked it again today and now it's the date. I only signed up 9 days ago.

**Comment by Timothy-Ganoza** [comment]
I think the birthdate is random. I just signed up today and my void pet's birthday is October 25.
![image](https://user-images.githubusercontent.com/38800640/152667217-cf1d2e3a-d7b5-4a1e-b222-f53e9c0ebf59.png)
****

**Comment by benawad** [comment]
The day you met your pet is different than when they were born
