### ISSUE TITLE
Game refuses to allow me to play w/ pet

### ISSUE THREAD

**Issue by H0nkme** [voidpet/bugs#90]
It plays a second of the animation then gives up it doesn't do the +/- bits of playing either :(

**Comment by benawad** [comment]
Could you record a video of what it looks like

**Comment by H0nkme** [comment]
I can not unfortunately; but it plays like the first two frames after you click the button and then that's it ^^;

**Comment by H0nkme** [comment]
It's still not working and now it's kicking me out of the game entirely making me re log in

**Comment by H0nkme** [comment]
Game is still not letting me play :(

**Comment by H0nkme** [comment]
Managed to get this 

https://media.discordapp.net/attachments/923681834846539796/941722534733299772/mobizen_20220211_104718.mp4

**Comment by benawad** [comment]
Could you refresh and see if it lets you play with your pet now.

If not what's your Voidpet username?

**Comment by H0nkme** [comment]
I have refreshed; My username is Honkme ^^

**Comment by H0nkme** [comment]
Unfortunately it's now not showing my pet at all when I go to play

**Comment by H0nkme** [comment]
![Screenshot_20220212-001231-995](https://user-images.githubusercontent.com/99282837/153716824-745224a3-9b53-4f5a-9019-88068b8cdd36.png)

**Comment by benawad** [comment]
Could you try logging out and logging in again.

**Comment by H0nkme** [comment]
I did just now and it's doing the same thing with not showing me lad ^^

**Comment by Kroppeb** [comment]
Could you check what you see at [api.voidpet.com](api.voidpet.com)

**Comment by H0nkme** [comment]
![Screenshot_20220212-195432-773](https://user-images.githubusercontent.com/99282837/153733751-89dd75d3-de3f-47e4-809e-df149b080820.png)

**Comment by benawad** [comment]
Could you take a screenshot of what you see at `voidpet.com` and then screenshot what you see after you hit the play button.

**Comment by benawad** [comment]
Every time you refresh on voidpet.com do you have to login?

could you try using Firefox/brave or another browser to see if the same issue is there

**Comment by H0nkme** [comment]
The game works on fire fox the issue is my main browser is chrome

**Comment by benawad** [comment]
I would try uninstalling chrome and reinstalling it, might clear a cache issue or something if it works on Firefox that means it has something to do with your browser

**Comment by H0nkme** [comment]
It works!! TYSM!
