### ISSUE TITLE
Lifting Lines

### ISSUE THREAD

**Issue by j14jow911** [voidpet/bugs#93]
**Describe the bug**
For some strange reason when playing on safari if you are lifting weights with your pet little black lines appear on the sides of the moving weight. This only occurs on safari and not google chrome

**To Reproduce**
1 Open voidpets on safari
2 press lift with the pet.
3 the lines appear sometimes

**Video or Screenshots**
<img width="289" alt="Screen Shot 2022-02-09 at 11 36 10 AM" src="https://user-images.githubusercontent.com/99350551/153246513-8da9b1c0-c120-40f3-a9b2-f08e68982f19.png">

**Desktop (please complete the following information):**
 - OS: MacOS/IOS
 - Browser: safari
 - Version Idk

**Comment by benawad** [comment]
should be fixed now
