### ISSUE TITLE
Bond Cap Not Increasing After Rollover

### ISSUE THREAD

**Issue by aeleria** [voidpet/bugs#95]
**Describe the bug**
After choosing the Envy starter, and playing with Envy daily for about six days, Envy has only progressed in the first two days to 3/4ths of the way through level 2. The bond has only appeared to progress to a certain cap, and has completely stopped. User has spent multiple hours in total dedicated to interacting with the pet with no change. 

**To Reproduce**
Any attempts to play with the starter have resulted in the correct dialogue boxes, but no improvements in score after positive dialogue has been achieved. This has gone on for the last few days. 

**Expected behavior**
I would have expected Envy to have increased in bonding level after rollover. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 98.0.4758.82

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 15.2.1
 - Browser: Chrome
 - Version: 98.0.4758.85

**Comment by Kroppeb** [comment]
There no longer is a rollover (might never have been any). Instead you have to wait 13 hours after the last bond points you got

**Comment by benawad** [comment]
What is your Voidpet name, I'll check

**Comment by Kroppeb** [comment]
> What is your Voidpet username, I'll check

Might be `aeleria` as it's an existing user?

**Comment by benawad** [comment]
They seem to have an Anxious instead of an Envy

**Comment by aeleria** [comment]
The username is teamjeni! Also, update, the pet hit level 3 today! If you did something, I think it worked! Thank you!
