### ISSUE TITLE
Page Footer Excluded Outside Primary App Route

### ISSUE THREAD

**Issue by j-wenning** [voidpet/bugs#98]
**Describe the bug**
The page footers for Landing, Home, and Discord links do not display under any routes of the app besides the user route.

**Expected behavior**
Assumedly these links would be preferred to be present under all card tabs(?).

**Video or Screenshots**
<img width="462" alt="Screen Shot 2022-02-11 at 15 13 32" src="https://user-images.githubusercontent.com/58379242/153683146-a7370257-8d5a-4883-ae10-03d466e47c5c.png">
<img width="438" alt="Screen Shot 2022-02-11 at 15 13 53" src="https://user-images.githubusercontent.com/58379242/153683167-49d7f57d-3d4c-4bf8-bd60-9157eb9d5263.png">
<img width="470" alt="Screen Shot 2022-02-11 at 15 14 06" src="https://user-images.githubusercontent.com/58379242/153683184-22877560-c219-4a0b-89c9-77c5f69e5df5.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser: Google Chrome
 - Version: 98.0.4758.80

**Additional context**
Not sure if this actually constitutes a bug report but I figured it may be worth bringing some attention to, seeing as store plugs usually want to be as accessible as possible.

**Comment by benawad** [comment]
changed
